#define MICROPY_HW_BOARD_NAME "ESP32 module with GSM"
#define MICROPY_HW_MCU_NAME "ESP32"
#define MODULE_EXAMPLE_ENABLED (1)
#define CONFIG_MICROPY_USE_GSM (1)
#define CONFIG_MICROPY_TASK_PRIORITY (5)
