# cmake file for Arduino Nano RP2040 Connect.
set(MICROPY_PY_BLUETOOTH  1)
set(MICROPY_BLUETOOTH_NIMBLE  1)
set(MICROPY_PY_NETWORK_NINAW10 1)
set(MICROPY_HW_ENABLE_DOUBLE_TAP 1)
set(MICROPY_FROZEN_MANIFEST ${MICROPY_BOARD_DIR}/manifest.py)

if(NOT DEFINED MICROPY_HW_FLASH_STORAGE_BYTES)
    set(MICROPY_HW_FLASH_STORAGE_BYTES 14680064)  # 14 * 1024 * 1024
endif()
