# cmake file for Arduino Nano RP2040 Connect.
set(MICROPY_PY_BLUETOOTH  1)
set(MICROPY_BLUETOOTH_NIMBLE  1)
set(MICROPY_PY_NETWORK_NINAW10 1)
set(MICROPY_HW_ENABLE_DOUBLE_TAP 1)
set(MICROPY_FROZEN_MANIFEST ${MICROPY_BOARD_DIR}/manifest.py)
