#ifndef MICROPY_INCLUDED_AMEBA_BOARDS_PKE8721DAF_MPCONFIGBOARD_H
#define MICROPY_INCLUDED_AMEBA_BOARDS_PKE8721DAF_MPCONFIGBOARD_H

#define MICROPY_HW_BOARD_NAME   "PKE8721DAF"
#define MICROPY_HW_MCU_NAME     "RTL8721DAF"

// RGB LED: controlled by PA14 / PA15 / PA16
#define MICROPY_HW_LED_RED      (14)
#define MICROPY_HW_LED_GREEN    (15)
#define MICROPY_HW_LED_BLUE     (16)

// Default UART: PA30 = RX, PA31 = TX (LOGUART)
#define MICROPY_HW_UART_TX      (31)
#define MICROPY_HW_UART_RX      (30)

#endif // MICROPY_INCLUDED_AMEBA_BOARDS_PKE8721DAF_MPCONFIGBOARD_H
