CIRCUITPY_CREATOR_ID = 123
CIRCUITPY_CREATION_ID = 123

IDF_TARGET = esp32c3

INTERNAL_FLASH_FILESYSTEM = 1

CIRCUITPY_ESP_FLASH_MODE = dio
CIRCUITPY_ESP_FLASH_FREQ = 80m
CIRCUITPY_ESP_FLASH_SIZE = 4MB
