# build a minimal interpreter
COPT = -Os -DNDEBUG

PROG = micropython-minimal

FROZEN_MANIFEST =

MICROPY_PY_BTREE = 0
MICROPY_PY_FFI = 0
MICROPY_PY_SOCKET = 0
MICROPY_PY_THREAD = 0
MICROPY_PY_TERMIOS = 0
MICROPY_PY_USSL = 0
MICROPY_USE_READLINE = 0
