#define MICROPY_HW_BOARD_NAME "SparkFun SAMD21 Dev Breakout"
#define MICROPY_HW_MCU_NAME   "SAMD21G18A"

#define MICROPY_HW_XOSC32K          (1)

#define MICROPY_HW_DEFAULT_UART_ID  (0)
#define MICROPY_HW_DEFAULT_I2C_ID   (3)
#define MICROPY_HW_DEFAULT_SPI_ID   (4)
