#define MICROPY_HW_BOARD_NAME "Teensy 4.0"
#define MICROPY_HW_MCU_NAME   "MIMXRT1062DVJ6A"

#define BOARD_FLASH_SIZE (2 * 1024 * 1024)

#define MICROPY_HW_LED_PINMUX   IOMUXC_GPIO_B0_03_GPIO2_IO03 // D13
#define MICROPY_HW_LED_PORT     GPIO2
#define MICROPY_HW_LED_PIN      3
