# Location of top-level MicroPython directory
MPY_DIR = ../../..

# Name of module
MOD = features4

# Source files (.c or .py)
SRC = features4.c

# Architecture to build for (x86, x64, armv7m, xtensa, xtensawin, rv32imc)
ARCH = x64

# Include to get the rules for compiling and linking the module
include $(MPY_DIR)/py/dynruntime.mk
