ESPIDF = /home/travis/build/ilyamordasov/micropython/ports/esp32/esp-idf
#PORT = /dev/ttyUSB0
#FLASH_MODE = qio
#FLASH_SIZE = 4MB
#CROSS_COMPILE = xtensa-esp32-elf-
SDKCONFIG = sdkconfig.myboard

include Makefile
