#include "modnetwork2.h"
#include "esp_wifi.h"
#include "lwip/dns.h"
#include "py/mperrno.h"

#if ESP_IDF_VERSION_MINOR >= 3

STATIC const mp_rom_map_elem_t mp_module_network2_globals_table[] = {
    { MP_ROM_QSTR(MP_QSTR___name__), MP_ROM_QSTR(MP_QSTR_network2) },

    { MP_ROM_QSTR(MP_QSTR_WIFI_MODE_NULL), MP_ROM_INT(WIFI_MODE_NULL) },
    { MP_ROM_QSTR(MP_QSTR_WIFI_MODE_STA), MP_ROM_INT(WIFI_MODE_STA) },
    { MP_ROM_QSTR(MP_QSTR_WIFI_MODE_AP), MP_ROM_INT(WIFI_MODE_AP) },
    // { MP_ROM_QSTR(MP_QSTR_WIFI_MODE_APSTA), MP_ROM_INT(WIFI_MODE_APSTA) },   // currently not implemented

    { MP_ROM_QSTR(MP_QSTR_AUTH_OPEN), MP_ROM_INT(WIFI_AUTH_OPEN) },
    { MP_ROM_QSTR(MP_QSTR_AUTH_WEP), MP_ROM_INT(WIFI_AUTH_WEP) },
    { MP_ROM_QSTR(MP_QSTR_AUTH_WPA_PSK), MP_ROM_INT(WIFI_AUTH_WPA_PSK) },
    { MP_ROM_QSTR(MP_QSTR_AUTH_WPA2_PSK), MP_ROM_INT(WIFI_AUTH_WPA2_PSK) },
    { MP_ROM_QSTR(MP_QSTR_AUTH_WPA_WPA2_PSK), MP_ROM_INT(WIFI_AUTH_WPA_WPA2_PSK) },
    { MP_ROM_QSTR(MP_QSTR_AUTH_WPA2_ENTERPRISE), MP_ROM_INT(WIFI_AUTH_WPA2_ENTERPRISE) },
    { MP_ROM_QSTR(MP_QSTR_AUTH_WPA3_PSK), MP_ROM_INT(WIFI_AUTH_WPA3_PSK) },
    { MP_ROM_QSTR(MP_QSTR_AUTH_WPA2_WPA3_PSK), MP_ROM_INT(WIFI_AUTH_WPA2_WPA3_PSK) },

    // See esp_wifi_types.h for more info
    { MP_ROM_QSTR(MP_QSTR_PROMIS_FILTER_MASK_ALL), MP_ROM_INT(WIFI_PROMIS_FILTER_MASK_ALL) },
    { MP_ROM_QSTR(MP_QSTR_PROMIS_FILTER_MASK_MGMT), MP_ROM_INT(WIFI_PROMIS_FILTER_MASK_MGMT) },
    { MP_ROM_QSTR(MP_QSTR_PROMIS_FILTER_MASK_CTRL), MP_ROM_INT(WIFI_PROMIS_FILTER_MASK_CTRL) },
    { MP_ROM_QSTR(MP_QSTR_PROMIS_FILTER_MASK_DATA), MP_ROM_INT(WIFI_PROMIS_FILTER_MASK_DATA) },
    { MP_ROM_QSTR(MP_QSTR_PROMIS_FILTER_MASK_MISC), MP_ROM_INT(WIFI_PROMIS_FILTER_MASK_MISC) },
    { MP_ROM_QSTR(MP_QSTR_PROMIS_FILTER_MASK_DATA_MPDU), MP_ROM_INT(WIFI_PROMIS_FILTER_MASK_DATA_MPDU) },
    { MP_ROM_QSTR(MP_QSTR_PROMIS_FILTER_MASK_DATA_AMPDU), MP_ROM_INT(WIFI_PROMIS_FILTER_MASK_DATA_AMPDU) },
    { MP_ROM_QSTR(MP_QSTR_PROMIS_FILTER_MASK_FCSFAIL), MP_ROM_INT(WIFI_PROMIS_FILTER_MASK_FCSFAIL) },
    { MP_ROM_QSTR(MP_QSTR_PROMIS_CTRL_FILTER_MASK_ALL), MP_ROM_INT(WIFI_PROMIS_CTRL_FILTER_MASK_ALL) },
    { MP_ROM_QSTR(MP_QSTR_PROMIS_CTRL_FILTER_MASK_WRAPPER), MP_ROM_INT(WIFI_PROMIS_CTRL_FILTER_MASK_WRAPPER) },
    { MP_ROM_QSTR(MP_QSTR_PROMIS_CTRL_FILTER_MASK_BAR), MP_ROM_INT(WIFI_PROMIS_CTRL_FILTER_MASK_BAR) },
    { MP_ROM_QSTR(MP_QSTR_PROMIS_CTRL_FILTER_MASK_BA), MP_ROM_INT(WIFI_PROMIS_CTRL_FILTER_MASK_BA) },
    { MP_ROM_QSTR(MP_QSTR_PROMIS_CTRL_FILTER_MASK_PSPOLL), MP_ROM_INT(WIFI_PROMIS_CTRL_FILTER_MASK_PSPOLL) },
    { MP_ROM_QSTR(MP_QSTR_PROMIS_CTRL_FILTER_MASK_RTS), MP_ROM_INT(WIFI_PROMIS_CTRL_FILTER_MASK_RTS) },
    { MP_ROM_QSTR(MP_QSTR_PROMIS_CTRL_FILTER_MASK_CTS), MP_ROM_INT(WIFI_PROMIS_CTRL_FILTER_MASK_CTS) },
    { MP_ROM_QSTR(MP_QSTR_PROMIS_CTRL_FILTER_MASK_ACK), MP_ROM_INT(WIFI_PROMIS_CTRL_FILTER_MASK_ACK) },
    { MP_ROM_QSTR(MP_QSTR_PROMIS_CTRL_FILTER_MASK_CFEND), MP_ROM_INT(WIFI_PROMIS_CTRL_FILTER_MASK_CFEND) },
    { MP_ROM_QSTR(MP_QSTR_PROMIS_CTRL_FILTER_MASK_CFENDACK), MP_ROM_INT(WIFI_PROMIS_CTRL_FILTER_MASK_CFENDACK) },

    { MP_ROM_QSTR(MP_QSTR_PHY_LAN8720), MP_ROM_INT(PHY_LAN8720) },
    { MP_ROM_QSTR(MP_QSTR_PHY_IP101), MP_ROM_INT(PHY_IP101) },
    { MP_ROM_QSTR(MP_QSTR_PHY_RTL8201), MP_ROM_INT(PHY_RTL8201) },
    { MP_ROM_QSTR(MP_QSTR_PHY_DP83848), MP_ROM_INT(PHY_DP83848) },
    { MP_ROM_QSTR(MP_QSTR_PHY_KSZ8041), MP_ROM_INT(PHY_KSZ8041) },

    { MP_ROM_QSTR(MP_QSTR_Wifi), MP_ROM_PTR(&wifi_network_if_type) },
};

STATIC MP_DEFINE_CONST_DICT(mp_module_network2_globals, mp_module_network2_globals_table);

const mp_obj_module_t mp_module_network2 = {
    .base = { &mp_type_module },
    .globals = (mp_obj_dict_t *)&mp_module_network2_globals,
};

MP_REGISTER_MODULE(MP_QSTR_network2, mp_module_network2, ESP_IDF_VERSION_MINOR >= 3);// MODULE_NETWORK2_ENABLED);
#endif
