/*
 * This file is part of the MicroPython project, http://micropython.org/
 *
 * The MIT License (MIT)
 *
 * Copyright (c) 2019 Lucian Copeland for Adafruit Industries
 * Copyright (c) 2019 Artur Pacholec
 * Copyright (c) 2023 Scott Shawcroft for Adafruit Industries
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */


// define FORMAT_PIN(pin_name) and then include this file.

FORMAT_PIN(GPIO_EMC_B1_00)
FORMAT_PIN(GPIO_EMC_B1_01)
FORMAT_PIN(GPIO_EMC_B1_02)
FORMAT_PIN(GPIO_EMC_B1_03)
FORMAT_PIN(GPIO_EMC_B1_04)
FORMAT_PIN(GPIO_EMC_B1_05)
FORMAT_PIN(GPIO_EMC_B1_06)
FORMAT_PIN(GPIO_EMC_B1_07)
FORMAT_PIN(GPIO_EMC_B1_08)
FORMAT_PIN(GPIO_EMC_B1_09)
FORMAT_PIN(GPIO_EMC_B1_10)
FORMAT_PIN(GPIO_EMC_B1_11)
FORMAT_PIN(GPIO_EMC_B1_12)
FORMAT_PIN(GPIO_EMC_B1_13)
FORMAT_PIN(GPIO_EMC_B1_14)
FORMAT_PIN(GPIO_EMC_B1_15)
FORMAT_PIN(GPIO_EMC_B1_16)
FORMAT_PIN(GPIO_EMC_B1_17)
FORMAT_PIN(GPIO_EMC_B1_18)
FORMAT_PIN(GPIO_EMC_B1_19)
FORMAT_PIN(GPIO_EMC_B1_20)
FORMAT_PIN(GPIO_EMC_B1_21)
FORMAT_PIN(GPIO_EMC_B1_22)
FORMAT_PIN(GPIO_EMC_B1_23)
FORMAT_PIN(GPIO_EMC_B1_24)
FORMAT_PIN(GPIO_EMC_B1_25)
FORMAT_PIN(GPIO_EMC_B1_26)
FORMAT_PIN(GPIO_EMC_B1_27)
FORMAT_PIN(GPIO_EMC_B1_28)
FORMAT_PIN(GPIO_EMC_B1_29)
FORMAT_PIN(GPIO_EMC_B1_30)
FORMAT_PIN(GPIO_EMC_B1_31)
FORMAT_PIN(GPIO_EMC_B1_32)
FORMAT_PIN(GPIO_EMC_B1_33)
FORMAT_PIN(GPIO_EMC_B1_34)
FORMAT_PIN(GPIO_EMC_B1_35)
FORMAT_PIN(GPIO_EMC_B1_36)
FORMAT_PIN(GPIO_EMC_B1_37)
FORMAT_PIN(GPIO_EMC_B1_38)
FORMAT_PIN(GPIO_EMC_B1_39)
FORMAT_PIN(GPIO_EMC_B1_40)
FORMAT_PIN(GPIO_EMC_B1_41)

FORMAT_PIN(GPIO_EMC_B2_00)
FORMAT_PIN(GPIO_EMC_B2_01)
FORMAT_PIN(GPIO_EMC_B2_02)
FORMAT_PIN(GPIO_EMC_B2_03)
FORMAT_PIN(GPIO_EMC_B2_04)
FORMAT_PIN(GPIO_EMC_B2_05)
FORMAT_PIN(GPIO_EMC_B2_06)
FORMAT_PIN(GPIO_EMC_B2_07)
FORMAT_PIN(GPIO_EMC_B2_08)
FORMAT_PIN(GPIO_EMC_B2_09)
FORMAT_PIN(GPIO_EMC_B2_10)
FORMAT_PIN(GPIO_EMC_B2_11)
FORMAT_PIN(GPIO_EMC_B2_12)
FORMAT_PIN(GPIO_EMC_B2_13)
FORMAT_PIN(GPIO_EMC_B2_14)
FORMAT_PIN(GPIO_EMC_B2_15)
FORMAT_PIN(GPIO_EMC_B2_16)
FORMAT_PIN(GPIO_EMC_B2_17)
FORMAT_PIN(GPIO_EMC_B2_18)
FORMAT_PIN(GPIO_EMC_B2_19)
FORMAT_PIN(GPIO_EMC_B2_20)

FORMAT_PIN(GPIO_AD_00)
FORMAT_PIN(GPIO_AD_01)
FORMAT_PIN(GPIO_AD_02)
FORMAT_PIN(GPIO_AD_03)
FORMAT_PIN(GPIO_AD_04)
FORMAT_PIN(GPIO_AD_05)
FORMAT_PIN(GPIO_AD_06)
FORMAT_PIN(GPIO_AD_07)
FORMAT_PIN(GPIO_AD_08)
FORMAT_PIN(GPIO_AD_09)
FORMAT_PIN(GPIO_AD_10)
FORMAT_PIN(GPIO_AD_11)
FORMAT_PIN(GPIO_AD_12)
FORMAT_PIN(GPIO_AD_13)
FORMAT_PIN(GPIO_AD_14)
FORMAT_PIN(GPIO_AD_15)
FORMAT_PIN(GPIO_AD_16)
FORMAT_PIN(GPIO_AD_17)
FORMAT_PIN(GPIO_AD_18)
FORMAT_PIN(GPIO_AD_19)
FORMAT_PIN(GPIO_AD_20)
FORMAT_PIN(GPIO_AD_21)
FORMAT_PIN(GPIO_AD_22)
FORMAT_PIN(GPIO_AD_23)
FORMAT_PIN(GPIO_AD_24)
FORMAT_PIN(GPIO_AD_25)
FORMAT_PIN(GPIO_AD_26)
FORMAT_PIN(GPIO_AD_27)
FORMAT_PIN(GPIO_AD_28)
FORMAT_PIN(GPIO_AD_29)
FORMAT_PIN(GPIO_AD_30)
FORMAT_PIN(GPIO_AD_31)
FORMAT_PIN(GPIO_AD_32)
FORMAT_PIN(GPIO_AD_33)
FORMAT_PIN(GPIO_AD_34)
FORMAT_PIN(GPIO_AD_35)

FORMAT_PIN(GPIO_SD_B1_00)
FORMAT_PIN(GPIO_SD_B1_01)
FORMAT_PIN(GPIO_SD_B1_02)
FORMAT_PIN(GPIO_SD_B1_03)
FORMAT_PIN(GPIO_SD_B1_04)
FORMAT_PIN(GPIO_SD_B1_05)

FORMAT_PIN(GPIO_SD_B2_00)
FORMAT_PIN(GPIO_SD_B2_01)
FORMAT_PIN(GPIO_SD_B2_02)
FORMAT_PIN(GPIO_SD_B2_03)
FORMAT_PIN(GPIO_SD_B2_04)
FORMAT_PIN(GPIO_SD_B2_05)
FORMAT_PIN(GPIO_SD_B2_06)
FORMAT_PIN(GPIO_SD_B2_07)
FORMAT_PIN(GPIO_SD_B2_08)
FORMAT_PIN(GPIO_SD_B2_09)
FORMAT_PIN(GPIO_SD_B2_10)
FORMAT_PIN(GPIO_SD_B2_11)

FORMAT_PIN(GPIO_DISP_B1_00)
FORMAT_PIN(GPIO_DISP_B1_01)
FORMAT_PIN(GPIO_DISP_B1_02)
FORMAT_PIN(GPIO_DISP_B1_03)
FORMAT_PIN(GPIO_DISP_B1_04)
FORMAT_PIN(GPIO_DISP_B1_05)
FORMAT_PIN(GPIO_DISP_B1_06)
FORMAT_PIN(GPIO_DISP_B1_07)
FORMAT_PIN(GPIO_DISP_B1_08)
FORMAT_PIN(GPIO_DISP_B1_09)
FORMAT_PIN(GPIO_DISP_B1_10)
FORMAT_PIN(GPIO_DISP_B1_11)

FORMAT_PIN(GPIO_DISP_B2_00)
FORMAT_PIN(GPIO_DISP_B2_01)
FORMAT_PIN(GPIO_DISP_B2_02)
FORMAT_PIN(GPIO_DISP_B2_03)
FORMAT_PIN(GPIO_DISP_B2_04)
FORMAT_PIN(GPIO_DISP_B2_05)
FORMAT_PIN(GPIO_DISP_B2_06)
FORMAT_PIN(GPIO_DISP_B2_07)
FORMAT_PIN(GPIO_DISP_B2_08)
FORMAT_PIN(GPIO_DISP_B2_09)
FORMAT_PIN(GPIO_DISP_B2_10)
FORMAT_PIN(GPIO_DISP_B2_11)
FORMAT_PIN(GPIO_DISP_B2_12)
FORMAT_PIN(GPIO_DISP_B2_13)
FORMAT_PIN(GPIO_DISP_B2_14)
FORMAT_PIN(GPIO_DISP_B2_15)
