USB_VID = 0x303A
USB_PID = 0x8142

USB_PRODUCT = "Deneyap Mini"
USB_MANUFACTURER = "Turkish Technology Team Foundation"

IDF_TARGET = esp32s2

CIRCUITPY_ESP_FLASH_MODE = dio
CIRCUITPY_ESP_FLASH_FREQ = 80m
CIRCUITPY_ESP_FLASH_SIZE = 4MB
CIRCUITPY_ESPCAMERA = 0
