include("$(PORT_DIR)/boards/manifest.py")

package("Chatter2", base_path="$(PORT_DIR)/libraries")
package("BatCtrl", base_path="$(PORT_DIR)/libraries")
package("Batmobile", base_path="$(PORT_DIR)/libraries")
package("ByteBoi", base_path="$(PORT_DIR)/libraries")
package("Wheelson", base_path="$(PORT_DIR)/libraries")
package("Synthia", base_path="$(PORT_DIR)/libraries")
package("Chatter", base_path="$(PORT_DIR)/libraries")
package("CircuitPet", base_path="$(PORT_DIR)/libraries")
package("Spencer", base_path="$(PORT_DIR)/libraries")
package("JayD", base_path="$(PORT_DIR)/libraries")
