USB_VID = 0x16D0
USB_PID = 0x07F2
USB_PRODUCT = "Autosport Labs ESP32-CAN-X2"
USB_MANUFACTURER = "Autosport Labs"

IDF_TARGET = esp32s3

CIRCUITPY_ESP_FLASH_SIZE = 8MB
CIRCUITPY_ESP_FLASH_MODE = qio
CIRCUITPY_ESP_FLASH_FREQ = 80m

CIRCUITPY_ESP_PSRAM_SIZE = 8MB
CIRCUITPY_ESP_PSRAM_MODE = opi
CIRCUITPY_ESP_PSRAM_FREQ = 80m
