USB_VID = 0x2e8a
USB_PID = 0x1023
USB_PRODUCT = "Challenger RP2040 LoRa"
USB_MANUFACTURER = "Invector Labs"

CHIP_VARIANT = RP2040
CHIP_FAMILY = rp2

EXTERNAL_FLASH_DEVICES = "W25Q64JVxQ"

CIRCUITPY__EVE = 1

FROZEN_MPY_DIRS += $(TOP)/frozen/Adafruit_CircuitPython_RFM9x
