CIRCUITPY_CREATOR_ID =  0x19981000
CIRCUITPY_CREATION_ID = 0x00BB0001

IDF_TARGET = esp32c3

CIRCUITPY_ESP_FLASH_MODE=dio
CIRCUITPY_ESP_FLASH_FREQ=80m
CIRCUITPY_ESP_FLASH_SIZE=4MB

CIRCUITPY_LEGACY_4MB_FLASH_LAYOUT = 1

CIRCUITPY_ESP_USB_SERIAL_JTAG = 1
