USB_VID = 0x239A
USB_PID = 0x814C
USB_PRODUCT = "ESP32-S3-EV-LCD-Board"
USB_MANUFACTURER = "Espressif"

IDF_TARGET = esp32s3

CIRCUITPY_ESP_FLASH_MODE = dio
CIRCUITPY_ESP_FLASH_FREQ = 80m
CIRCUITPY_ESP_FLASH_SIZE = 16MB

CIRCUITPY_ESP_PSRAM_SIZE = 8MB
CIRCUITPY_ESP_PSRAM_MODE = opi
CIRCUITPY_ESP_PSRAM_FREQ = 120m

CIRCUITPY_DOTCLOCKFRAMEBUFFER = 1
UF2_BOOTLOADER = 0
