/*
 * This file is part of the MicroPython project, http://micropython.org/
 *
 * The MIT License (MIT)
 *
 * Copyright (c) 2019 Lucian Copeland for Adafruit Industries
 * Copyright (c) 2019 Artur Pacholec
 * Copyright (c) 2023 Scott Shawcroft for Adafruit Industries
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */


// define FORMAT_PIN(pin_name) and then include this file.

FORMAT_PIN(GPIO_EMC_00)
FORMAT_PIN(GPIO_EMC_01)
FORMAT_PIN(GPIO_EMC_02)
FORMAT_PIN(GPIO_EMC_03)
FORMAT_PIN(GPIO_EMC_04)
FORMAT_PIN(GPIO_EMC_05)
FORMAT_PIN(GPIO_EMC_06)
FORMAT_PIN(GPIO_EMC_07)
FORMAT_PIN(GPIO_EMC_08)
FORMAT_PIN(GPIO_EMC_09)
FORMAT_PIN(GPIO_EMC_10)
FORMAT_PIN(GPIO_EMC_11)
FORMAT_PIN(GPIO_EMC_12)
FORMAT_PIN(GPIO_EMC_13)
FORMAT_PIN(GPIO_EMC_14)
FORMAT_PIN(GPIO_EMC_15)
FORMAT_PIN(GPIO_EMC_16)
FORMAT_PIN(GPIO_EMC_17)
FORMAT_PIN(GPIO_EMC_18)
FORMAT_PIN(GPIO_EMC_19)
FORMAT_PIN(GPIO_EMC_20)
FORMAT_PIN(GPIO_EMC_21)
FORMAT_PIN(GPIO_EMC_22)
FORMAT_PIN(GPIO_EMC_23)
FORMAT_PIN(GPIO_EMC_24)
FORMAT_PIN(GPIO_EMC_25)
FORMAT_PIN(GPIO_EMC_26)
FORMAT_PIN(GPIO_EMC_27)
FORMAT_PIN(GPIO_EMC_28)
FORMAT_PIN(GPIO_EMC_29)
FORMAT_PIN(GPIO_EMC_30)
FORMAT_PIN(GPIO_EMC_31)
FORMAT_PIN(GPIO_EMC_32)
FORMAT_PIN(GPIO_EMC_33)
FORMAT_PIN(GPIO_EMC_34)
FORMAT_PIN(GPIO_EMC_35)
FORMAT_PIN(GPIO_EMC_36)
FORMAT_PIN(GPIO_EMC_37)
FORMAT_PIN(GPIO_EMC_38)
FORMAT_PIN(GPIO_EMC_39)
FORMAT_PIN(GPIO_EMC_40)
FORMAT_PIN(GPIO_EMC_41)

FORMAT_PIN(GPIO_AD_B0_00)
FORMAT_PIN(GPIO_AD_B0_01)
FORMAT_PIN(GPIO_AD_B0_02)
FORMAT_PIN(GPIO_AD_B0_03)
FORMAT_PIN(GPIO_AD_B0_04)
FORMAT_PIN(GPIO_AD_B0_05)
FORMAT_PIN(GPIO_AD_B0_06)
FORMAT_PIN(GPIO_AD_B0_07)
FORMAT_PIN(GPIO_AD_B0_08)
FORMAT_PIN(GPIO_AD_B0_09)
FORMAT_PIN(GPIO_AD_B0_10)
FORMAT_PIN(GPIO_AD_B0_11)
FORMAT_PIN(GPIO_AD_B0_12)
FORMAT_PIN(GPIO_AD_B0_13)
FORMAT_PIN(GPIO_AD_B0_14)
FORMAT_PIN(GPIO_AD_B0_15)

FORMAT_PIN(GPIO_AD_B1_00)
FORMAT_PIN(GPIO_AD_B1_01)
FORMAT_PIN(GPIO_AD_B1_02)
FORMAT_PIN(GPIO_AD_B1_03)
FORMAT_PIN(GPIO_AD_B1_04)
FORMAT_PIN(GPIO_AD_B1_05)
FORMAT_PIN(GPIO_AD_B1_06)
FORMAT_PIN(GPIO_AD_B1_07)
FORMAT_PIN(GPIO_AD_B1_08)
FORMAT_PIN(GPIO_AD_B1_09)
FORMAT_PIN(GPIO_AD_B1_10)
FORMAT_PIN(GPIO_AD_B1_11)
FORMAT_PIN(GPIO_AD_B1_12)
FORMAT_PIN(GPIO_AD_B1_13)
FORMAT_PIN(GPIO_AD_B1_14)
FORMAT_PIN(GPIO_AD_B1_15)

FORMAT_PIN(GPIO_B0_00)
FORMAT_PIN(GPIO_B0_01)
FORMAT_PIN(GPIO_B0_02)
FORMAT_PIN(GPIO_B0_03)
FORMAT_PIN(GPIO_B0_04)
FORMAT_PIN(GPIO_B0_05)
FORMAT_PIN(GPIO_B0_06)
FORMAT_PIN(GPIO_B0_07)
FORMAT_PIN(GPIO_B0_08)
FORMAT_PIN(GPIO_B0_09)
FORMAT_PIN(GPIO_B0_10)
FORMAT_PIN(GPIO_B0_11)
FORMAT_PIN(GPIO_B0_12)
FORMAT_PIN(GPIO_B0_13)
FORMAT_PIN(GPIO_B0_14)
FORMAT_PIN(GPIO_B0_15)

FORMAT_PIN(GPIO_B1_00)
FORMAT_PIN(GPIO_B1_01)
FORMAT_PIN(GPIO_B1_02)
FORMAT_PIN(GPIO_B1_03)
FORMAT_PIN(GPIO_B1_04)
FORMAT_PIN(GPIO_B1_05)
FORMAT_PIN(GPIO_B1_06)
FORMAT_PIN(GPIO_B1_07)
FORMAT_PIN(GPIO_B1_08)
FORMAT_PIN(GPIO_B1_09)
FORMAT_PIN(GPIO_B1_10)
FORMAT_PIN(GPIO_B1_11)
FORMAT_PIN(GPIO_B1_12)
FORMAT_PIN(GPIO_B1_13)
FORMAT_PIN(GPIO_B1_14)
FORMAT_PIN(GPIO_B1_15)

FORMAT_PIN(GPIO_SD_B0_00)
FORMAT_PIN(GPIO_SD_B0_01)
FORMAT_PIN(GPIO_SD_B0_02)
FORMAT_PIN(GPIO_SD_B0_03)
FORMAT_PIN(GPIO_SD_B0_04)
FORMAT_PIN(GPIO_SD_B0_05)

FORMAT_PIN(GPIO_SD_B1_00)
FORMAT_PIN(GPIO_SD_B1_01)
FORMAT_PIN(GPIO_SD_B1_02)
FORMAT_PIN(GPIO_SD_B1_03)
FORMAT_PIN(GPIO_SD_B1_04)
FORMAT_PIN(GPIO_SD_B1_05)
FORMAT_PIN(GPIO_SD_B1_06)
FORMAT_PIN(GPIO_SD_B1_07)
FORMAT_PIN(GPIO_SD_B1_08)
FORMAT_PIN(GPIO_SD_B1_09)
FORMAT_PIN(GPIO_SD_B1_10)
FORMAT_PIN(GPIO_SD_B1_11)
FORMAT_PIN(USB_OTG1_DN)
FORMAT_PIN(USB_OTG1_DP)
FORMAT_PIN(USB_OTG2_DN)
FORMAT_PIN(USB_OTG2_DP)
