USB_VID = 0x239A
USB_PID = 0x805C
USB_PRODUCT = "Pyboard Version 1.1"
USB_MANUFACTURER = "George Robotic"
USB_DEVICES = "CDC,MSC"

INTERNAL_FLASH_FILESYSTEM = 1
LONGINT_IMPL = NONE

MCU_SERIES = m4
MCU_VARIANT = stm32f4
MCU_SUB_VARIANT = stm32f405xx
MCU_PACKAGE = 64
CMSIS_MCU = STM32F405xx
LD_FILE = boards/STM32F405_fs.ld

