# Hardware features.
CONFIG_PINCTRL=y
CONFIG_GPIO=y
CONFIG_WATCHDOG=y
CONFIG_CONSOLE_SUBSYS=y
CONFIG_CONSOLE_GETCHAR=y
CONFIG_CONSOLE_GETCHAR_BUFSIZE=1024
CONFIG_CONSOLE_PUTCHAR_BUFSIZE=1024
CONFIG_I2C=y
CONFIG_I2C_TARGET=y
CONFIG_SPI=y
CONFIG_MEMC=y
CONFIG_ENTROPY_GENERATOR=y

# MicroPython config
CONFIG_MICROPY_HEAP_SIZE=16384
CONFIG_MAIN_STACK_SIZE=16384
CONFIG_MICROPY_CONFIG_ROM_LEVEL_FULL_FEATURES=y
CONFIG_MICROPY_FROZEN_MANIFEST="boards/bflb/manifest.py"

# Threads
CONFIG_THREAD_LOCAL_STORAGE=y

# File System Configuration
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_FILE_SYSTEM=y
CONFIG_FILE_SYSTEM_LITTLEFS=y
CONFIG_FILE_SYSTEM_MKFS=y
CONFIG_MICROPY_VFS_FAT=y
CONFIG_MICROPY_VFS_LFS1=n
CONFIG_MICROPY_VFS_LFS2=n
# Default heap for littlefs is too small
CONFIG_FS_LITTLEFS_FC_HEAP_SIZE=8192

# Bluetooth
CONFIG_BT=y
CONFIG_BT_DEVICE_NAME_DYNAMIC=y
CONFIG_BT_DEVICE_APPEARANCE_DYNAMIC=y
CONFIG_BT_GATT_DYNAMIC_DB=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_CENTRAL=y
CONFIG_BT_GATT_CLIENT=y
CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=n
CONFIG_BT_DIS=y
CONFIG_BT_DIS_PNP=n
CONFIG_BT_SMP=y
CONFIG_BT_BUF_ACL_RX_SIZE=672
CONFIG_BT_BUF_ACL_TX_SIZE=672
CONFIG_BT_L2CAP_TX_MTU=672
CONFIG_BT_BUF_CMD_TX_SIZE=255
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=6
CONFIG_BT_HCI_TX_STACK_SIZE=2048
CONFIG_BT_RX_STACK_SIZE=4096
CONFIG_BT_BUF_ACL_TX_COUNT=4
CONFIG_BT_BUF_EVT_RX_COUNT=5

# Networking
CONFIG_NETWORKING=y
CONFIG_WIFI=y
CONFIG_NET_IPV4=y
CONFIG_NET_IPV6=y
CONFIG_NET_UDP=y
CONFIG_NET_TCP=y
CONFIG_NET_SOCKETS=y
CONFIG_NET_HOSTNAME_DYNAMIC=y
CONFIG_WIFI_USAGE_MODE_STA_AP=y
CONFIG_NET_SOCKETS_INET_RAW=y
CONFIG_NET_SOCKETS_SOCKOPT_TLS=y
CONFIG_NET_SOCKETS_TLS_MAX_CONTEXTS=2
CONFIG_MBEDTLS_SSL_VARIABLE_BUFFER_LENGTH=y
CONFIG_MBEDTLS_SSL_IN_CONTENT_LEN=16384
CONFIG_MBEDTLS_SSL_OUT_CONTENT_LEN=16384
CONFIG_ZVFS_POLL_MAX=10
CONFIG_NET_IF_MAX_IPV6_COUNT=2
CONFIG_NET_IF_MAX_IPV4_COUNT=2

# Safeguard an amount of LIBC malloc space
CONFIG_COMMON_LIBC_MALLOC=y
CONFIG_COMMON_LIBC_MALLOC_ARENA_SIZE=16384

# DNS
CONFIG_DNS_RESOLVER=y
CONFIG_DNS_RESOLVER_AUTO_INIT=y
CONFIG_DNS_RESOLVER_ADDITIONAL_QUERIES=2
CONFIG_DNS_RESOLVER_MAX_SERVERS=2
CONFIG_NET_SOCKETS_DNS_TIMEOUT=4000

# DHCP configuration.
CONFIG_NET_DHCPV4=y
CONFIG_NET_DHCPV6=y
CONFIG_NET_DHCPV4_SERVER=y

# Use less heap than recommended, but using all of is very unlikely
CONFIG_HEAP_MEM_POOL_SIZE=45056
CONFIG_HEAP_MEM_POOL_IGNORE_MIN=y
CONFIG_SYS_HEAP_RUNTIME_STATS=y

# Required for socket.pkt_get_info()
CONFIG_NET_BUF_POOL_USAGE=y

# Fix BLE / WiFi Crypto config clash
CONFIG_MBEDTLS_PSA_P256M_DRIVER_ENABLED=n

# Don't use 40KB of RAM for nothing
CONFIG_MBEDTLS_PSA_STATIC_KEY_SLOTS=n
