# Hardware features.
CONFIG_PINCTRL=y
CONFIG_GPIO=y
CONFIG_WATCHDOG=y
CONFIG_CONSOLE_SUBSYS=y
CONFIG_CONSOLE_GETCHAR=y
CONFIG_CONSOLE_GETCHAR_BUFSIZE=1024
CONFIG_CONSOLE_PUTCHAR_BUFSIZE=1024
CONFIG_I2C=y
CONFIG_I2C_TARGET=y
CONFIG_SPI=y
CONFIG_MEMC=y
CONFIG_ENTROPY_GENERATOR=y

# Disable networking.
CONFIG_NETWORKING=n

# MicroPython config.
CONFIG_MICROPY_HEAP_SIZE=196608
CONFIG_MAIN_STACK_SIZE=16384
CONFIG_MICROPY_CONFIG_ROM_LEVEL_FULL_FEATURES=y
CONFIG_MICROPY_FROZEN_MANIFEST="boards/bflb/manifest.py"

# Threads
CONFIG_THREAD_CUSTOM_DATA=y

# File System Configuration
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_FILE_SYSTEM=y
CONFIG_FILE_SYSTEM_LITTLEFS=y
CONFIG_FILE_SYSTEM_MKFS=y
CONFIG_MICROPY_VFS_FAT=y
CONFIG_MICROPY_VFS_LFS1=n
CONFIG_MICROPY_VFS_LFS2=n
# Default heap for littlefs is too small
CONFIG_FS_LITTLEFS_FC_HEAP_SIZE=8192

# Bluetooth
CONFIG_BT=y
CONFIG_BT_DEVICE_NAME_DYNAMIC=y
CONFIG_BT_DEVICE_APPEARANCE_DYNAMIC=y
CONFIG_BT_GATT_DYNAMIC_DB=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_CENTRAL=y
CONFIG_BT_GATT_CLIENT=y
CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=n
CONFIG_BT_DIS=y
CONFIG_BT_DIS_PNP=n
CONFIG_BT_SMP=y
CONFIG_BT_BUF_ACL_RX_SIZE=672
CONFIG_BT_BUF_ACL_TX_SIZE=672
CONFIG_BT_L2CAP_TX_MTU=672
CONFIG_BT_BUF_CMD_TX_SIZE=255
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=6
CONFIG_BT_HCI_TX_STACK_SIZE=2048
CONFIG_BT_RX_STACK_SIZE=4096
CONFIG_BT_BUF_ACL_TX_COUNT=8
CONFIG_BT_BUF_EVT_RX_COUNT=16
