# Hardware features.
CONFIG_PINCTRL=y
CONFIG_GPIO=y
CONFIG_WATCHDOG=y
CONFIG_I2C=y
CONFIG_I2C_TARGET=n
CONFIG_SPI=y
CONFIG_ENTROPY_GENERATOR=y

# Disable networking.
CONFIG_NETWORKING=n

# MicroPython config.
CONFIG_MICROPY_HEAP_SIZE=17500
CONFIG_MAIN_STACK_SIZE=8192
CONFIG_MICROPY_CONFIG_ROM_LEVEL_BASIC_FEATURES=y
CONFIG_MICROPY_CONFIGFILE="boards/bflb/BL70xA0.h"

# File System Configuration
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_FILE_SYSTEM=y
CONFIG_FILE_SYSTEM_LITTLEFS=y
CONFIG_FILE_SYSTEM_MKFS=y
CONFIG_MICROPY_VFS_FAT=n
CONFIG_MICROPY_VFS_LFS1=n
CONFIG_MICROPY_VFS_LFS2=n
# Default heap for littlefs is too small
CONFIG_FS_LITTLEFS_FC_HEAP_SIZE=4096

# Console Configuration
CONFIG_CONSOLE_SUBSYS=y
CONFIG_UART_CONSOLE=y
CONFIG_CONSOLE_GETCHAR=y
CONFIG_CONSOLE_GETCHAR_BUFSIZE=512
CONFIG_CONSOLE_PUTCHAR_BUFSIZE=128

# BLE
CONFIG_BT=y
CONFIG_BT_DEVICE_NAME_DYNAMIC=y
CONFIG_BT_DEVICE_APPEARANCE_DYNAMIC=y
CONFIG_BT_GATT_DYNAMIC_DB=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_CENTRAL=n
CONFIG_BT_GATT_CLIENT=n
CONFIG_BT_DIS=n
CONFIG_BT_DIS_PNP=n
CONFIG_BT_BUF_ACL_RX_SIZE=256
CONFIG_BT_BUF_ACL_TX_SIZE=256
CONFIG_BT_L2CAP_TX_MTU=256
CONFIG_BT_BUF_CMD_TX_SIZE=255
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=6
CONFIG_BT_BUF_ACL_TX_COUNT=2
CONFIG_BT_BUF_EVT_RX_COUNT=4

# We have entropy
CONFIG_TEST_RANDOM_GENERATOR=n
