USB_VID = 0x04D8
USB_PID = 0xE799
USB_PRODUCT = "Maker Zero SAMD21"
USB_MANUFACTURER = "Cytron"

CHIP_VARIANT = SAMD21G18A
CHIP_FAMILY = samd21

INTERNAL_FLASH_FILESYSTEM = 1
LONGINT_IMPL = NONE
CIRCUITPY_FULL_BUILD = 0
