USB_VID = 0x239A
USB_PID = 0x8150
USB_PRODUCT = "Feather RP2350"
USB_MANUFACTURER = "Adafruit"

CHIP_VARIANT = RP2350
CHIP_PACKAGE = A
CHIP_FAMILY = rp2

EXTERNAL_FLASH_DEVICES = "GD25Q64C,W25Q64JVxQ"

CIRCUITPY_ALARM = 0
CIRCUITPY_RGBMATRIX = 0
CIRCUITPY_USB_HOST = 0

CIRCUITPY_FLOPPYIO = 0
CIRCUITPY_PICODVI = 1
