USB_VID = 0x239A
USB_PID = 0x805E
USB_PRODUCT = "STM32F411VE Discovery Board - CPy"
USB_MANUFACTURER = "STMicroelectronics"
USB_DEVICES = "CDC,MSC"

INTERNAL_FLASH_FILESYSTEM = 1

MCU_SERIES = F4
MCU_VARIANT = STM32F411xE
MCU_PACKAGE = LQFP100_f4

LD_COMMON = boards/common_default.ld
LD_FILE = boards/STM32F411_fs.ld
