CIRCUITPY_CREATOR_ID = 0x4496E3F4
CIRCUITPY_CREATION_ID = 0x00320024


CIRCUITPY_ESPCAMERA = 0

CIRCUITPY_ESP_FLASH_MODE=dio
CIRCUITPY_ESP_FLASH_FREQ=40m
CIRCUITPY_ESP_FLASH_SIZE=4MB

CIRCUITPY_LEGACY_4MB_FLASH_LAYOUT = 1

IDF_TARGET = esp32
