FROZEN_MANIFEST ?= boards/manifest.py
MICROPY_PY_NETWORK_IFX_WCM = 1
MICROPY_PY_NETWORK = 1
MICROPY_PSOC6_LWIP = 1
MICROPY_PY_SSL = 1
MICROPY_PSOC6_SSL_MBEDTLS = 1
MICROPY_PY_EXT_FLASH = 1
BOARD_VERSION=release-v4.0.0

# Variables to support make-pins
PIN_PACKAGE_FILE = cyhal_psoc6_02_124_bga.h
