USB_VID = 0x239A
USB_PID = 0x8158
USB_PRODUCT = "TRRS Trinkey M0"
USB_MANUFACTURER = "Adafruit Industries LLC"

CHIP_VARIANT = SAMD21E18A
CHIP_FAMILY = samd21

INTERNAL_FLASH_FILESYSTEM = 1
LONGINT_IMPL = NONE

CIRCUITPY_FULL_BUILD = 0

CIRCUITPY_BUSIO_SPI = 0
CIRCUITPY_BUSIO_UART = 0
CIRCUITPY_KEYPAD = 1
CIRCUITPY_KEYPAD_DEMUX = 0
CIRCUITPY_KEYPAD_KEYMATRIX = 0
CIRCUITPY_KEYPAD_SHIFTREGISTERKEYS = 0
CIRCUITPY_PWMIO = 0
CIRCUITPY_RAINBOWIO = 0
CIRCUITPY_ROTARYIO = 0
CIRCUITPY_RTC = 0

# Include these Python libraries in firmware.
# Currently at least one large translation is too large to include NeoPixel.
# FROZEN_MPY_DIRS += $(TOP)/frozen/Adafruit_CircuitPython_NeoPixel
FROZEN_MPY_DIRS += $(TOP)/frozen/Adafruit_CircuitPython_HID
