#!/usr/bin/env bash

CPYTHON3=python3.3
MP_CPY=../../unix-cpy/cpy

RM=/bin/rm

mkdir -p output

function run_test_on_dir() {
    echo ""
    echo "Testing directory $1..."
    echo ""

    for file in $1/*.py
    do
        basename=$(basename $file .py)

        $CPYTHON3 -B -c "import compileall; compileall.compile_file('$file', quiet=True)"
        #/usr/lib/python3.3/compileall.py $file
        $CPYTHON3 -B unpyc.py $1/__pycache__/$basename.cpython-33.pyc > output/$basename.pycout

        $MP_CPY $file | $CPYTHON3 -B check.py output/$basename.pycout
    done

    echo ""
}

run_test_on_dir mp-tests
run_test_on_dir pylib-tests
