USB_VID = 0x04D8
USB_PID = 0xEC64
USB_PRODUCT = "CircuitBrains Deluxe"
USB_MANUFACTURER = "Kevin Neubauer"

CHIP_VARIANT = SAMD51J19A
CHIP_FAMILY = samd51

QSPI_FLASH_FILESYSTEM = 1
EXTERNAL_FLASH_DEVICES = "W25Q64JVxQ, S25FL064L"
LONGINT_IMPL = MPZ

CIRCUITPY_PS2IO = 1
