USB_VID = 0x3343
USB_PID = 0x83CF
USB_PRODUCT = "Firebeetle 2 ESP32-S3"
USB_MANUFACTURER = "DFRobot"

IDF_TARGET = esp32s3

CIRCUITPY_ESP_FLASH_MODE = qio
CIRCUITPY_ESP_FLASH_FREQ = 80m
CIRCUITPY_ESP_FLASH_SIZE = 16MB

CIRCUITPY_ESP_PSRAM_SIZE = 8MB
CIRCUITPY_ESP_PSRAM_MODE = opi
CIRCUITPY_ESP_PSRAM_FREQ = 120m

FROZEN_MPY_DIRS += $(TOP)/frozen/CircuitPython_AXP313A
