# SPDX-FileCopyrightText: 2014 MicroPython & CircuitPython contributors (https://github.com/adafruit/circuitpython/graphs/contributors)
#
# SPDX-License-Identifier: MIT

# This configuration file tells Rosie where to find prebuilt .bin files (Travis
# builds them) and where to find the tests.

binaries:
    prebuilt_s3:
        bucket: adafruit-circuit-python
        file_pattern: bin/{board}/adafruit-circuitpython-{board}-*-{short_sha}.{extension}
    rosie_upload:
        file_pattern: adafruit-circuitpython-{board}-*{short_sha}.{extension}

circuitpython_tests:
    test_directories:
        - tests/basics
        - tests/circuitpython
    test_helper:
        - tests/skip_if.py
