USB_VID = 0x239A
USB_PID = 0x8148
USB_PRODUCT = "Qualia-S3-RGB666"
USB_MANUFACTURER = "Adafruit"

IDF_TARGET = esp32s3

CIRCUITPY_ESP_FLASH_MODE = dio
CIRCUITPY_ESP_FLASH_FREQ = 80m
CIRCUITPY_ESP_FLASH_SIZE = 16MB

CIRCUITPY_DOTCLOCKFRAMEBUFFER = 1
