// This file was automatically generated by make-pins.py
//
// --af ch32f30x_af.csv
// --board ch32v307_evt_pins.csv
// --prefix prefix.c

// prefix.c becomes the initial portion of the generated pins file.

#include <stdio.h>

#include "py/obj.h"
#include "py/mphal.h"
#include "pin.h"

#define AF(af_idx, af_fn, af_unit, af_type, af_ptr) \
{ \
    { &pin_af_type }, \
    .name = MP_QSTR_AF ## af_idx ## _ ## af_fn ## af_unit, \
    .idx = (af_idx), \
    .fn = AF_FN_ ## af_fn, \
    .unit = (af_unit), \
    .type = AF_PIN_TYPE_ ## af_fn ## _ ## af_type, \
    .reg = (af_ptr) \
}

#define PIN(p_port, p_pin, p_af, p_adc_num, p_adc_channel) \
{ \
    { &pin_type }, \
    .name = MP_QSTR_ ## p_port ## p_pin, \
    .port = PORT_ ## p_port, \
    .pin = (p_pin), \
    .num_af = (sizeof(p_af) / sizeof(pin_af_obj_t)), \
    .pin_mask = (1 << ((p_pin) & 0x0f)), \
    .gpio = GPIO ## p_port, \
    .af = p_af, \
    .adc_num = p_adc_num, \
    .adc_channel = p_adc_channel, \
}

// const pin_af_obj_t pin_E2_af[] = {
  //( 3, TIM     , 10, BKIN_2    , TIM10   ), // TIM10_BKIN_2
  //(12, FSMC    ,  0, A23       , FSMC    ), // FSMC_A23
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
// };

const pin_obj_t pin_E2_obj = PIN(E, 2, NULL, 0, 0);

// const pin_af_obj_t pin_E3_af[] = {
  //( 3, TIM     , 10, CH1N_2    , TIM10   ), // TIM10_CH1N_2
  //(12, FSMC    ,  0, A19       , FSMC    ), // FSMC_A19
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
// };

const pin_obj_t pin_E3_obj = PIN(E, 3, NULL, 0, 0);

// const pin_af_obj_t pin_E4_af[] = {
  //( 3, TIM     , 10, CH2N_2    , TIM10   ), // TIM10_CH2N_2
  //(12, FSMC    ,  0, A20       , FSMC    ), // FSMC_A20
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
// };

const pin_obj_t pin_E4_obj = PIN(E, 4, NULL, 0, 0);

// const pin_af_obj_t pin_E5_af[] = {
  //( 3, TIM     , 10, CH3N_2    , TIM10   ), // TIM10_CH3N_2
  //(12, FSMC    ,  0, A21       , FSMC    ), // FSMC_A21
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
// };

const pin_obj_t pin_E5_obj = PIN(E, 5, NULL, 0, 0);

// const pin_af_obj_t pin_E6_af[] = {
  //(12, FSMC    ,  0, A22       , FSMC    ), // FSMC_A22
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
// };

const pin_obj_t pin_E6_obj = PIN(E, 6, NULL, 0, 0);

// const pin_af_obj_t pin_C13_af[] = {
  //( 0, TAMPER-RTC,  0,           , TAMPER-RTC), // TAMPER-RTC
  //( 3, TIM     ,  8, CH4_1     , TIM8    ), // TIM8_CH4_1
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
// };

const pin_obj_t pin_C13_obj = PIN(C, 13, NULL, 0, 0);

// const pin_af_obj_t pin_C14_af[] = {
  //( 0, OSC     , 32, IN        , OSC32   ), // OSC32_IN
  //( 3, TIM     ,  9, CH4_1     , TIM9    ), // TIM9_CH4_1
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
// };

const pin_obj_t pin_C14_obj = PIN(C, 14, NULL, 0, 0);

// const pin_af_obj_t pin_C15_af[] = {
  //( 0, OSC     , 32, OUT       , OSC32   ), // OSC32_OUT
  //( 3, TIM     , 10, CH4_1     , TIM10   ), // TIM10_CH4_1
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
// };

const pin_obj_t pin_C15_obj = PIN(C, 15, NULL, 0, 0);

// const pin_af_obj_t pin_D0_af[] = {
  //( 0, OSC     ,  0, IN        , OSC     ), // OSC_IN
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
// };

const pin_obj_t pin_D0_obj = PIN(D, 0, NULL, 0, 0);

// const pin_af_obj_t pin_D1_af[] = {
  //( 0, OSC     ,  0, OUT       , OSC     ), // OSC_OUT
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
// };

const pin_obj_t pin_D1_obj = PIN(D, 1, NULL, 0, 0);

const pin_af_obj_t pin_C0_af[] = {
  AF( 3, TIM     ,  9, CH1N      , TIM9    ), // TIM9_CH1N
#if defined(MICROPY_HW_UART6_TX)
  AF( 8, UART    ,  6, TX        , UART6   ), // UART6_TX
#endif
  //(11, ETH     ,  0, RGMII_RXC , ETH     ), // ETH_RGMII_RXC
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_C0_obj = PIN(C, 0, pin_C0_af, PIN_ADC1, 10);

const pin_af_obj_t pin_C1_af[] = {
  AF( 3, TIM     ,  9, CH2N      , TIM9    ), // TIM9_CH2N
#if defined(MICROPY_HW_UART6_TX)
  AF( 8, UART    ,  6, RX        , UART6   ), // UART6_RX
#endif
  //(11, ETH     ,  0, MII_MDC   , ETH     ), // ETH_MII_MDC
  //(11, ETH     ,  0, RMII_MDC  , ETH     ), // ETH_RMII_MDC
  //(11,  ETH    ,  0, RGMII_RXCTL,  ETH    ), //  ETH_RGMII_RXCTL
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_C1_obj = PIN(C, 1, pin_C1_af, PIN_ADC1, 11);

const pin_af_obj_t pin_C2_af[] = {
  AF( 3, TIM     ,  9, CH3N      , TIM9    ), // TIM9_CH3N
#if defined(MICROPY_HW_UART7_TX)
  AF( 8, UART    ,  7, TX        , UART7   ), // UART7_TX
#endif
  //(11, ETH     ,  0, MII_TXD2  , ETH     ), // ETH_MII_TXD2
  //(11, ETH     ,  0, RGMII_RXD0, ETH     ), // ETH_RGMII_RXD0
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_C2_obj = PIN(C, 2, pin_C2_af, PIN_ADC1, 12);

const pin_af_obj_t pin_C3_af[] = {
  AF( 3, TIM     , 10, CH3       , TIM10   ), // TIM10_CH3
#if defined(MICROPY_HW_UART7_TX)
  AF( 8, UART    ,  7, RX        , UART7   ), // UART7_RX
#endif
  //(11, ETH     ,  0, MII_TX_CLK, ETH     ), // ETH_MII_TX_CLK
  //(11, ETH     ,  0, RGMII_RXD1, ETH     ), // ETH_RGMII_RXD1
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_C3_obj = PIN(C, 3, pin_C3_af, PIN_ADC1, 13);

const pin_af_obj_t pin_A0_af[] = {
  //( 0, WKUP    ,  0,           , WKUP    ), // WKUP
  AF( 1, TIM     ,  2, CH1_ETR   , TIM2    ), // TIM2_CH1_ETR
  //( 1, TIM     ,  2, CH1_ETR_2 , TIM2    ), // TIM2_CH1_ETR_2
  AF( 2, TIM     ,  5, CH1       , TIM5    ), // TIM5_CH1
  AF( 3, TIM     ,  8, ETR       , TIM8    ), // TIM8_ETR
  //( 3, TIM     ,  8, ETR_1     , TIM8    ), // TIM8_ETR_1
#if defined(MICROPY_HW_UART2_TX)
  AF( 7, USART   ,  2, CTS       , USART2  ), // USART2_CTS
#endif
  //(11, ETH     ,  0, MII_CRS_WKUP, ETH     ), // ETH_MII_CRS_WKUP
  //(11, ETH     ,  0, RGMII_RXD2, ETH     ), // ETH_RGMII_RXD2
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_A0_obj = PIN(A, 0, pin_A0_af, PIN_ADC1, 0);

const pin_af_obj_t pin_A1_af[] = {
  AF( 1, TIM     ,  2, CH2       , TIM2    ), // TIM2_CH2
  //( 1, TIM     ,  2, CH2_2     , TIM2    ), // TIM2_CH2_2
  AF( 2, TIM     ,  5, CH2       , TIM5    ), // TIM5_CH2
  //( 3, TIM     ,  9, BKIN_1    , TIM9    ), // TIM9_BKIN_1
#if defined(MICROPY_HW_UART2_TX)
  AF( 7, USART   ,  2, RTS       , USART2  ), // USART2_RTS
#endif
  //(11, ETH     ,  0, MII_RX_CLK, ETH     ), // ETH_MII_RX_CLK
  //(11, ETH     ,  0, RMII_REF_CLK, ETH     ), // ETH_RMII_REF_CLK
  //(11, ETH     ,  0, RGMII_RXD3, ETH     ), // ETH_RGMII_RXD3
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_A1_obj = PIN(A, 1, pin_A1_af, PIN_ADC1, 1);

const pin_af_obj_t pin_A2_af[] = {
  AF( 1, TIM     ,  2, CH3       , TIM2    ), // TIM2_CH3
  //( 1, TIM     ,  2, CH3_1     , TIM2    ), // TIM2_CH3_1
  AF( 2, TIM     ,  5, CH3       , TIM5    ), // TIM5_CH3
  AF( 3, TIM     ,  9, CH1_ETR   , TIM9    ), // TIM9_CH1_ETR
  //( 3, TIM     ,  9, CH1_ETR_1 , TIM9    ), // TIM9_CH1_ETR_1
#if defined(MICROPY_HW_UART2_TX)
  AF( 7, USART   ,  2, TX        , USART2  ), // USART2_TX
#endif
  //(11, ETH     ,  0, MII_MDIO  , ETH     ), // ETH_MII_MDIO
  //(11, ETH     ,  0, RMII_MDIO , ETH     ), // ETH_RMII_MDIO
  //(11, ETH     ,  0, RGMII_GTXC, ETH     ), // ETH_RGMII_GTXC
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_A2_obj = PIN(A, 2, pin_A2_af, PIN_ADC1, 2);

const pin_af_obj_t pin_A3_af[] = {
  AF( 1, TIM     ,  2, CH4       , TIM2    ), // TIM2_CH4
  //( 1, TIM     ,  2, CH4_1     , TIM2    ), // TIM2_CH4_1
  AF( 2, TIM     ,  5, CH4       , TIM5    ), // TIM5_CH4
  AF( 3, TIM     ,  9, CH2       , TIM9    ), // TIM9_CH2
  //( 3, TIM     ,  9, CH2_1     , TIM9    ), // TIM9_CH2_1
#if defined(MICROPY_HW_UART2_TX)
  AF( 7, USART   ,  2, RX        , USART2  ), // USART2_RX
#endif
  //(11, ETH     ,  0, MII_COL   , ETH     ), // ETH_MII_COL
  //(11, ETH     ,  0, RGMII_TXEN, ETH     ), // ETH_RGMII_TXEN
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_A3_obj = PIN(A, 3, pin_A3_af, PIN_ADC1, 3);

const pin_af_obj_t pin_A4_af[] = {
  AF( 3, TIM     ,  9, CH3       , TIM9    ), // TIM9_CH3
  //( 3, TIM     ,  9, CH3_1     , TIM9    ), // TIM9_CH3_1
#if defined(MICROPY_HW_SPI1_SCK)
  AF( 5, SPI     ,  1, NSS       , SPI1    ), // SPI1_NSS
#endif
#if defined(MICROPY_HW_SPI3_SCK)
  AF( 6, SPI     ,  3, NSS       , SPI3    ), // SPI3_NSS
#endif
#if defined(MICROPY_HW_I2S3)
  AF( 6, I2S     ,  3, WS        , I2S3    ), // I2S3_WS
#endif
#if defined(MICROPY_HW_UART2_TX)
  AF( 7, USART   ,  2, CK        , USART2  ), // USART2_CK
#endif
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_A4_obj = PIN(A, 4, pin_A4_af, PIN_ADC1, 4);

const pin_af_obj_t pin_A5_af[] = {
  //( 3, TIM     , 10, CH1N_1    , TIM10   ), // TIM10_CH1N_1
#if defined(MICROPY_HW_SPI1_SCK)
  AF( 5, SPI     ,  1, SCK       , SPI1    ), // SPI1_SCK
#endif
  //( 7, USART   ,  1, CTS_2     , USART1  ), // USART1_CTS_2
  //( 7, USART   ,  1, CK_3      , USART1  ), // USART1_CK_3
  //(13, DVP     ,  0, VSYNC     , DVP     ), // DVP_VSYNC
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_A5_obj = PIN(A, 5, pin_A5_af, PIN_ADC1, 5);

const pin_af_obj_t pin_A6_af[] = {
  //( 1, TIM     ,  1, BKIN_1    , TIM1    ), // TIM1_BKIN_1
  AF( 2, TIM     ,  3, CH1       , TIM3    ), // TIM3_CH1
  AF( 3, TIM     ,  8, BKIN      , TIM8    ), // TIM8_BKIN
  //( 3, TIM     , 10, CH2N_1    , TIM10   ), // TIM10_CH2N_1
#if defined(MICROPY_HW_SPI1_SCK)
  AF( 5, SPI     ,  1, MISO      , SPI1    ), // SPI1_MISO
#endif
  //( 7, USART   ,  1, TX_3      , USART1  ), // USART1_TX_3
  //( 8, UART    ,  7, TX_1      , UART7   ), // UART7_TX_1
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_A6_obj = PIN(A, 6, pin_A6_af, PIN_ADC1, 6);

const pin_af_obj_t pin_A7_af[] = {
  //( 1, TIM     ,  1, CH1N_1    , TIM1    ), // TIM1_CH1N_1
  AF( 2, TIM     ,  3, CH2       , TIM3    ), // TIM3_CH2
  AF( 3, TIM     ,  8, CH1N      , TIM8    ), // TIM8_CH1N
  //( 3, TIM     , 10, CH3N_1    , TIM10   ), // TIM10_CH3N_1
#if defined(MICROPY_HW_SPI1_SCK)
  AF( 5, SPI     ,  1, MOSI      , SPI1    ), // SPI1_MOSI
#endif
  //( 7, USART   ,  1, RX_3      , USART1  ), // USART1_RX_3
  //( 8, UART    ,  7, RX_1      , UART7   ), // UART7_RX_1
  //(11, ETH     ,  0, RMII_CRS_DV, ETH     ), // ETH_RMII_CRS_DV
  //(11, ETH     ,  0, RGMII_TXD0, ETH     ), // ETH_RGMII_TXD0
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_A7_obj = PIN(A, 7, pin_A7_af, PIN_ADC1, 7);

const pin_af_obj_t pin_C4_af[] = {
  AF( 3, TIM     ,  9, CH4       , TIM9    ), // TIM9_CH4
  //( 7, USART   ,  1, CTS_3     , USART1  ), // USART1_CTS_3
#if defined(MICROPY_HW_UART8_TX)
  AF( 8, UART    ,  8, TX        , UART8   ), // UART8_TX
#endif
  //(11, ETH     ,  0, MII_RXD0  , ETH     ), // ETH_MII_RXD0
  //(11, ETH     ,  0, RMII_RXD0 , ETH     ), // ETH_RMII_RXD0
  //(11, ETH     ,  0, RGMII_TXD1, ETH     ), // ETH_RGMII_TXD1
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_C4_obj = PIN(C, 4, pin_C4_af, PIN_ADC1, 14);

const pin_af_obj_t pin_C5_af[] = {
  AF( 3, TIM     ,  9, BKIN      , TIM9    ), // TIM9_BKIN
  //( 7, USART   ,  1, RTS_3     , USART1  ), // USART1_RTS_3
#if defined(MICROPY_HW_UART8_TX)
  AF( 8, UART    ,  8, RX        , UART8   ), // UART8_RX
#endif
  //(11, ETH     ,  0, MII_RXD1  , ETH     ), // ETH_MII_RXD1
  //(11, ETH     ,  0, RMII_RXD1 , ETH     ), // ETH_RMII_RXD1
  //(11, ETH     ,  0, RGMII_TXD2, ETH     ), // ETH_RGMII_TXD2
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_C5_obj = PIN(C, 5, pin_C5_af, PIN_ADC1, 15);

const pin_af_obj_t pin_B0_af[] = {
  //( 1, TIM     ,  1, CH2N_1    , TIM1    ), // TIM1_CH2N_1
  AF( 2, TIM     ,  3, CH3       , TIM3    ), // TIM3_CH3
  //( 2, TIM     ,  3, CH3_2     , TIM3    ), // TIM3_CH3_2
  AF( 3, TIM     ,  8, CH2N      , TIM8    ), // TIM8_CH2N
  //( 3, TIM     ,  9, CH1N_1    , TIM9    ), // TIM9_CH1N_1
  //( 8, UART    ,  4, TX_1      , UART4   ), // UART4_TX_1
  //(11, ETH     ,  0, MII_RXD2  , ETH     ), // ETH_MII_RXD2
  //(11, ETH     ,  0, RGMII_TXD3, ETH     ), // ETH_RGMII_TXD3
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_B0_obj = PIN(B, 0, pin_B0_af, PIN_ADC1, 8);

const pin_af_obj_t pin_B1_af[] = {
  //( 1, TIM     ,  1, CH3N_1    , TIM1    ), // TIM1_CH3N_1
  AF( 2, TIM     ,  3, CH4       , TIM3    ), // TIM3_CH4
  //( 2, TIM     ,  3, CH4_2     , TIM3    ), // TIM3_CH4_2
  AF( 3, TIM     ,  8, CH3N      , TIM8    ), // TIM8_CH3N
  //( 3, TIM     ,  9, CH2N_1    , TIM9    ), // TIM9_CH2N_1
  //( 8, UART    ,  4, RX_1      , UART4   ), // UART4_RX_1
  //(11, ETH     ,  0, MII_RXD3  , ETH     ), // ETH_MII_RXD3
  //(11, ETH     ,  0, RGMII_125IN, ETH     ), // ETH_RGMII_125IN
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_B1_obj = PIN(B, 1, pin_B1_af, PIN_ADC1, 9);

// const pin_af_obj_t pin_B2_af[] = {
  //( 0, BOOT    ,  1,           , BOOT1   ), // BOOT1
  //( 3, TIM     ,  9, CH3N_1    , TIM9    ), // TIM9_CH3N_1
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
// };

const pin_obj_t pin_B2_obj = PIN(B, 2, NULL, 0, 0);

// const pin_af_obj_t pin_E7_af[] = {
  //( 1, TIM     ,  1, ETR_3     , TIM1    ), // TIM1_ETR_3
  //( 8, UART    ,  5, TX_2      , UART5   ), // UART5_TX_2
  //(12, FSMC    ,  0, D4        , FSMC    ), // FSMC_D4
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
// };

const pin_obj_t pin_E7_obj = PIN(E, 7, NULL, 0, 0);

// const pin_af_obj_t pin_E8_af[] = {
  //( 1, TIM     ,  1, CH1N_3    , TIM1    ), // TIM1_CH1N_3
  //( 8, UART    ,  5, RX_2      , UART5   ), // UART5_RX_2
  //(12, FSMC    ,  0, D5        , FSMC    ), // FSMC_D5
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
// };

const pin_obj_t pin_E8_obj = PIN(E, 8, NULL, 0, 0);

// const pin_af_obj_t pin_E9_af[] = {
  //( 1, TIM     ,  1, CH1_3     , TIM1    ), // TIM1_CH1_3
  //( 8, UART    ,  6, TX_2      , UART6   ), // UART6_TX_2
  //(12, FSMC    ,  0, D6        , FSMC    ), // FSMC_D6
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
// };

const pin_obj_t pin_E9_obj = PIN(E, 9, NULL, 0, 0);

// const pin_af_obj_t pin_E10_af[] = {
  //( 1, TIM     ,  1, CH2N_3    , TIM1    ), // TIM1_CH2N_3
  //( 8, UART    ,  6, RX_2      , UART6   ), // UART6_RX_2
  //(12, FSMC    ,  0, D7        , FSMC    ), // FSMC_D7
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
// };

const pin_obj_t pin_E10_obj = PIN(E, 10, NULL, 0, 0);

// const pin_af_obj_t pin_E11_af[] = {
  //( 1, TIM     ,  1, CH2_3     , TIM1    ), // TIM1_CH2_3
  //( 8, UART    ,  7, TX_2      , UART7   ), // UART7_TX_2
  //(12, FSMC    ,  0, D8        , FSMC    ), // FSMC_D8
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
// };

const pin_obj_t pin_E11_obj = PIN(E, 11, NULL, 0, 0);

// const pin_af_obj_t pin_E12_af[] = {
  //( 1, TIM     ,  1, CH3N_3    , TIM1    ), // TIM1_CH3N_3
  //( 8, UART    ,  7, RX_2      , UART7   ), // UART7_RX_2
  //(12, FSMC    ,  0, D9        , FSMC    ), // FSMC_D9
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
// };

const pin_obj_t pin_E12_obj = PIN(E, 12, NULL, 0, 0);

// const pin_af_obj_t pin_E13_af[] = {
  //( 1, TIM     ,  1, CH3_3     , TIM1    ), // TIM1_CH3_3
  //( 8, UART    ,  8, TX_2      , UART8   ), // UART8_TX_2
  //(12, FSMC    ,  0, D10       , FSMC    ), // FSMC_D10
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
// };

const pin_obj_t pin_E13_obj = PIN(E, 13, NULL, 0, 0);

// const pin_af_obj_t pin_E14_af[] = {
  //( 1, TIM     ,  1, CH4_3     , TIM1    ), // TIM1_CH4_3
  //( 8, UART    ,  8, RX_2      , UART8   ), // UART8_RX_2
  //(12, FSMC    ,  0, D11       , FSMC    ), // FSMC_D11
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
// };

const pin_obj_t pin_E14_obj = PIN(E, 14, NULL, 0, 0);

// const pin_af_obj_t pin_E15_af[] = {
  //( 1, TIM     ,  1, BKIN_3    , TIM1    ), // TIM1_BKIN_3
  //(12, FSMC    ,  0, D12       , FSMC    ), // FSMC_D12
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
// };

const pin_obj_t pin_E15_obj = PIN(E, 15, NULL, 0, 0);

const pin_af_obj_t pin_B10_af[] = {
  //( 1, TIM     ,  2, CH3_2     , TIM2    ), // TIM2_CH3_2
  //( 1, TIM     ,  2, CH3_3     , TIM2    ), // TIM2_CH3_3
  //( 3, TIM     , 10, BKIN_1    , TIM10   ), // TIM10_BKIN_1
#if defined(MICROPY_HW_I2C2_SCL)
  AF( 4, I2C     ,  2, SCL       , I2C2    ), // I2C2_SCL
#endif
#if defined(MICROPY_HW_UART3_TX)
  AF( 7, USART   ,  3, TX        , USART3  ), // USART3_TX
#endif
  //(11, ETH     ,  0, MII_RX_ER , ETH     ), // ETH_MII_RX_ER
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_B10_obj = PIN(B, 10, pin_B10_af, 0, 0);

const pin_af_obj_t pin_B11_af[] = {
  //( 1, TIM     ,  2, CH4_2     , TIM2    ), // TIM2_CH4_2
  //( 1, TIM     ,  2, CH4_3     , TIM2    ), // TIM2_CH4_3
  //( 3, TIM     , 10, ETR_1     , TIM10   ), // TIM10_ETR_1
#if defined(MICROPY_HW_I2C2_SCL)
  AF( 4, I2C     ,  2, SDA       , I2C2    ), // I2C2_SDA
#endif
#if defined(MICROPY_HW_UART3_TX)
  AF( 7, USART   ,  3, RX        , USART3  ), // USART3_RX
#endif
  //(11, ETH     ,  0, MII_TX_EN , ETH     ), // ETH_MII_TX_EN
  //(11, ETH     ,  0, RMII_TX_EN, ETH     ), // ETH_RMII_TX_EN
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_B11_obj = PIN(B, 11, pin_B11_af, 0, 0);

const pin_af_obj_t pin_B12_af[] = {
  AF( 1, TIM     ,  1, BKIN      , TIM1    ), // TIM1_BKIN
  //( 4, I2C     ,  2, SMBA      , I2C2    ), // I2C2_SMBA
#if defined(MICROPY_HW_SPI2_SCK)
  AF( 5, SPI     ,  2, NSS       , SPI2    ), // SPI2_NSS
#endif
#if defined(MICROPY_HW_I2S2)
  AF( 5, I2S     ,  2, WS        , I2S2    ), // I2S2_WS
#endif
#if defined(MICROPY_HW_UART3_TX)
  AF( 7, USART   ,  3, CK        , USART3  ), // USART3_CK
#endif
#if defined(MICROPY_HW_CAN2_TX)
  AF( 9, CAN     ,  2, RX        , CAN2    ), // CAN2_RX
#endif
  //(11, ETH     ,  0, MII_TXD0  , ETH     ), // ETH_MII_TXD0
  //(11, ETH     ,  0, RMII_TXD0 , ETH     ), // ETH_RMII_TXD0
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_B12_obj = PIN(B, 12, pin_B12_af, 0, 0);

const pin_af_obj_t pin_B13_af[] = {
  AF( 1, TIM     ,  1, CH1N      , TIM1    ), // TIM1_CH1N
#if defined(MICROPY_HW_SPI2_SCK)
  AF( 5, SPI     ,  2, SCK       , SPI2    ), // SPI2_SCK
#endif
#if defined(MICROPY_HW_I2S2)
  AF( 5, I2S     ,  2, CK        , I2S2    ), // I2S2_CK
#endif
  //( 7, USART   ,  3, CTS_1     , USART3  ), // USART3_CTS_1
#if defined(MICROPY_HW_UART3_TX)
  AF( 7, USART   ,  3, CTS       , USART3  ), // USART3_CTS
#endif
#if defined(MICROPY_HW_CAN2_TX)
  AF( 9, CAN     ,  2, TX        , CAN2    ), // CAN2_TX
#endif
  //(11, ETH     ,  0, MII_TXD1  , ETH     ), // ETH_MII_TXD1
  //(11, ETH     ,  0, RMII_TXD1 , ETH     ), // ETH_RMII_TXD1
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_B13_obj = PIN(B, 13, pin_B13_af, 0, 0);

const pin_af_obj_t pin_B14_af[] = {
  AF( 1, TIM     ,  1, CH2N      , TIM1    ), // TIM1_CH2N
#if defined(MICROPY_HW_SPI2_SCK)
  AF( 5, SPI     ,  2, MISO      , SPI2    ), // SPI2_MISO
#endif
  //( 7, USART   ,  3, RTS_1     , USART3  ), // USART3_RTS_1
#if defined(MICROPY_HW_UART3_TX)
  AF( 7, USART   ,  3, RTS       , USART3  ), // USART3_RTS
#endif
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_B14_obj = PIN(B, 14, pin_B14_af, 0, 0);

const pin_af_obj_t pin_B15_af[] = {
  AF( 1, TIM     ,  1, CH3N      , TIM1    ), // TIM1_CH3N
#if defined(MICROPY_HW_SPI2_SCK)
  AF( 5, SPI     ,  2, MOSI      , SPI2    ), // SPI2_MOSI
#endif
#if defined(MICROPY_HW_I2S2)
  AF( 5, I2S     ,  2, SD        , I2S2    ), // I2S2_SD
#endif
  //( 7, USART   ,  1, TX_2      , USART1  ), // USART1_TX_2
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_B15_obj = PIN(B, 15, pin_B15_af, 0, 0);

// const pin_af_obj_t pin_D8_af[] = {
  //( 3, TIM     ,  9, CH1N_2    , TIM9    ), // TIM9_CH1N_2
  //( 7, USART   ,  3, TX_3      , USART3  ), // USART3_TX_3
  //(11, ETH     ,  0, MII_RX_DV , ETH     ), // ETH_MII_RX_DV
  //(11, ETH     ,  0, RMII_CRS_DV, ETH     ), // ETH_RMII_CRS_DV
  //(12, FSMC    ,  0, D13       , FSMC    ), // FSMC_D13
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
// };

const pin_obj_t pin_D8_obj = PIN(D, 8, NULL, 0, 0);

// const pin_af_obj_t pin_D9_af[] = {
  //( 3, TIM     ,  9, CH1_ETR_2 , TIM9    ), // TIM9_CH1_ETR_2
  //( 7, USART   ,  3, RX_3      , USART3  ), // USART3_RX_3
  //(11, ETH     ,  0, MII_RXD0  , ETH     ), // ETH_MII_RXD0
  //(11, ETH     ,  0, RMII_RXD0 , ETH     ), // ETH_RMII_RXD0
  //(12, FSMC    ,  0, D14       , FSMC    ), // FSMC_D14
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
// };

const pin_obj_t pin_D9_obj = PIN(D, 9, NULL, 0, 0);

// const pin_af_obj_t pin_D10_af[] = {
  //( 3, TIM     ,  9, CH2N_2    , TIM9    ), // TIM9_CH2N_2
  //( 7, USART   ,  3, CK_3      , USART3  ), // USART3_CK_3
  //(11, ETH     ,  0, MII_RXD1  , ETH     ), // ETH_MII_RXD1
  //(11, ETH     ,  0, RMII_RXD1 , ETH     ), // ETH_RMII_RXD1
  //(12, FSMC    ,  0, D15       , FSMC    ), // FSMC_D15
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
// };

const pin_obj_t pin_D10_obj = PIN(D, 10, NULL, 0, 0);

// const pin_af_obj_t pin_D11_af[] = {
  //( 3, TIM     ,  9, CH2_2     , TIM9    ), // TIM9_CH2_2
  //( 7, USART   ,  3, CTS_3     , USART3  ), // USART3_CTS_3
  //(11, ETH     ,  0, MII_RXD2  , ETH     ), // ETH_MII_RXD2
  //(12, FSMC    ,  0, A16       , FSMC    ), // FSMC_A16
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
// };

const pin_obj_t pin_D11_obj = PIN(D, 11, NULL, 0, 0);

// const pin_af_obj_t pin_D12_af[] = {
  //( 2, TIM     ,  4, CH1_1     , TIM4    ), // TIM4_CH1_1
  //( 3, TIM     ,  9, CH3N_2    , TIM9    ), // TIM9_CH3N_2
  //( 7, USART   ,  3, RTS_3     , USART3  ), // USART3_RTS_3
  //(11, ETH     ,  0, MII_RXD3  , ETH     ), // ETH_MII_RXD3
  //(12, FSMC    ,  0, A17       , FSMC    ), // FSMC_A17
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
// };

const pin_obj_t pin_D12_obj = PIN(D, 12, NULL, 0, 0);

// const pin_af_obj_t pin_D13_af[] = {
  //( 2, TIM     ,  4, CH2_1     , TIM4    ), // TIM4_CH2_1
  //( 3, TIM     ,  9, CH3_2     , TIM9    ), // TIM9_CH3_2
  //(12, FSMC    ,  0, A18       , FSMC    ), // FSMC_A18
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
// };

const pin_obj_t pin_D13_obj = PIN(D, 13, NULL, 0, 0);

// const pin_af_obj_t pin_D14_af[] = {
  //( 2, TIM     ,  4, CH3_1     , TIM4    ), // TIM4_CH3_1
  //( 3, TIM     ,  9, BKIN_2    , TIM9    ), // TIM9_BKIN_2
  //(12, FSMC    ,  0, D0        , FSMC    ), // FSMC_D0
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
// };

const pin_obj_t pin_D14_obj = PIN(D, 14, NULL, 0, 0);

// const pin_af_obj_t pin_D15_af[] = {
  //( 2, TIM     ,  4, CH4_1     , TIM4    ), // TIM4_CH4_1
  //( 3, TIM     ,  9, CH4_2     , TIM9    ), // TIM9_CH4_2
  //(12, FSMC    ,  0, D1        , FSMC    ), // FSMC_D1
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
// };

const pin_obj_t pin_D15_obj = PIN(D, 15, NULL, 0, 0);

const pin_af_obj_t pin_C6_af[] = {
  //( 2, TIM     ,  3, CH1_3     , TIM3    ), // TIM3_CH1_3
  AF( 3, TIM     ,  8, CH1       , TIM8    ), // TIM8_CH1
#if defined(MICROPY_HW_I2S2)
  AF( 5, I2S     ,  2, MCK       , I2S2    ), // I2S2_MCK
#endif
  //(11, ETH     ,  0, RXP       , ETH     ), // ETH_RXP
  //(12, SDIO    ,  0, D6        , SDIO    ), // SDIO_D6
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_C6_obj = PIN(C, 6, pin_C6_af, 0, 0);

const pin_af_obj_t pin_C7_af[] = {
  //( 2, TIM     ,  3, CH2_3     , TIM3    ), // TIM3_CH2_3
  AF( 3, TIM     ,  8, CH2       , TIM8    ), // TIM8_CH2
#if defined(MICROPY_HW_I2S3)
  AF( 5, I2S     ,  3, MCK       , I2S3    ), // I2S3_MCK
#endif
  //(11, ETH     ,  0, RXN       , ETH     ), // ETH_RXN
  //(12, SDIO    ,  0, D7        , SDIO    ), // SDIO_D7
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_C7_obj = PIN(C, 7, pin_C7_af, 0, 0);

const pin_af_obj_t pin_C8_af[] = {
  //( 2, TIM     ,  3, CH3_3     , TIM3    ), // TIM3_CH3_3
  AF( 3, TIM     ,  8, CH3       , TIM8    ), // TIM8_CH3
  //(11, ETH     ,  0, TXP       , ETH     ), // ETH_TXP
  //(12, SDIO    ,  0, D0        , SDIO    ), // SDIO_D0
  //(13, DVP     ,  0, D2        , DVP     ), // DVP_D2
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_C8_obj = PIN(C, 8, pin_C8_af, 0, 0);

const pin_af_obj_t pin_C9_af[] = {
  //( 2, TIM     ,  3, CH4_3     , TIM3    ), // TIM3_CH4_3
  AF( 3, TIM     ,  8, CH4       , TIM8    ), // TIM8_CH4
  //(11, ETH     ,  0, TXN       , ETH     ), // ETH_TXN
  //(12, SDIO    ,  0, D1        , SDIO    ), // SDIO_D1
  //(13, DVP     ,  0, D3        , DVP     ), // DVP_D3
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_C9_obj = PIN(C, 9, pin_C9_af, 0, 0);

const pin_af_obj_t pin_A8_af[] = {
  //( 0, MCO     ,  0,           , MCO     ), // MCO
  AF( 1, TIM     ,  1, CH1       , TIM1    ), // TIM1_CH1
  //( 1, TIM     ,  1, CH1_1     , TIM1    ), // TIM1_CH1_1
#if defined(MICROPY_HW_UART1_TX)
  AF( 7, USART   ,  1, CK        , USART1  ), // USART1_CK
#endif
  //( 7, USART   ,  1, CK_1      , USART1  ), // USART1_CK_1
  //( 7, USART   ,  1, RX_2      , USART1  ), // USART1_RX_2
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_A8_obj = PIN(A, 8, pin_A8_af, 0, 0);

const pin_af_obj_t pin_A9_af[] = {
  AF( 1, TIM     ,  1, CH2       , TIM1    ), // TIM1_CH2
  //( 1, TIM     ,  1, CH2_1     , TIM1    ), // TIM1_CH2_1
#if defined(MICROPY_HW_UART1_TX)
  AF( 7, USART   ,  1, TX        , USART1  ), // USART1_TX
#endif
  //( 7, USART   ,  1, RTS_2     , USART1  ), // USART1_RTS_2
  //(10, OTG     ,  0, FS_VBUS   , OTG     ), // OTG_FS_VBUS
  //(13, DVP     ,  0, D0        , DVP     ), // DVP_D0
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_A9_obj = PIN(A, 9, pin_A9_af, 0, 0);

const pin_af_obj_t pin_A10_af[] = {
  AF( 1, TIM     ,  1, CH3       , TIM1    ), // TIM1_CH3
  //( 1, TIM     ,  1, CH3_1     , TIM1    ), // TIM1_CH3_1
#if defined(MICROPY_HW_UART1_TX)
  AF( 7, USART   ,  1, RX        , USART1  ), // USART1_RX
#endif
  //( 7, USART   ,  1, CK_2      , USART1  ), // USART1_CK_2
  //(10, OTG     ,  0, FS_ID     , OTG     ), // OTG_FS_ID
  //(13, DVP     ,  0, D1        , DVP     ), // DVP_D1
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_A10_obj = PIN(A, 10, pin_A10_af, 0, 0);

const pin_af_obj_t pin_A11_af[] = {
  //( 1, TIM     ,  1, CH4_1     , TIM1    ), // TIM1_CH4_1
  AF( 1, TIM     ,  1, CH4       , TIM1    ), // TIM1_CH4
#if defined(MICROPY_HW_UART1_TX)
  AF( 7, USART   ,  1, CTS       , USART1  ), // USART1_CTS
#endif
  //( 7, USART   ,  1, CTS_1     , USART1  ), // USART1_CTS_1
#if defined(MICROPY_HW_CAN1_TX)
  AF( 9, CAN     ,  1, RX        , CAN1    ), // CAN1_RX
#endif
  //(10, USBDM   ,  0,           , USBDM   ), // USBDM
  //(10, OTG     ,  0, FS_DM     , OTG     ), // OTG_FS_DM
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_A11_obj = PIN(A, 11, pin_A11_af, 0, 0);

const pin_af_obj_t pin_A12_af[] = {
  //( 1, TIM     ,  1, ETR_1     , TIM1    ), // TIM1_ETR_1
  AF( 1, TIM     ,  1, ETR       , TIM1    ), // TIM1_ETR
  AF( 3, TIM     , 10, CH1N      , TIM10   ), // TIM10_CH1N
#if defined(MICROPY_HW_UART1_TX)
  AF( 7, USART   ,  1, RTS       , USART1  ), // USART1_RTS
#endif
  //( 7, USART   ,  1, RTS_1     , USART1  ), // USART1_RTS_1
#if defined(MICROPY_HW_CAN1_TX)
  AF( 9, CAN     ,  1, TX        , CAN1    ), // CAN1_TX
#endif
  //(10, USBDP   ,  0,           , USBDP   ), // USBDP
  //(10, OTG     ,  0, FS_DP     , OTG     ), // OTG_FS_DP
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_A12_obj = PIN(A, 12, pin_A12_af, 0, 0);

const pin_af_obj_t pin_A13_af[] = {
  //( 0, SWDIO   ,  0,           , SWDIO   ), // SWDIO
  AF( 3, TIM     , 10, CH2N      , TIM10   ), // TIM10_CH2N
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_A13_obj = PIN(A, 13, pin_A13_af, 0, 0);

const pin_af_obj_t pin_A14_af[] = {
  //( 0, SWCLK   ,  0,           , SWCLK   ), // SWCLK
  //( 3, TIM     ,  8, CH2N_1    , TIM8    ), // TIM8_CH2N_1
  AF( 3, TIM     , 10, CH3N      , TIM10   ), // TIM10_CH3N
  //( 8, UART    ,  8, TX_1      , UART8   ), // UART8_TX_1
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_A14_obj = PIN(A, 14, pin_A14_af, 0, 0);

const pin_af_obj_t pin_A15_af[] = {
  //( 2, TIM     ,  2, CH1_ETR_1 , TIM2    ), // TIM2_CH1_ETR_1
  //( 2, TIM     ,  2, CH1_ETR_3 , TIM2    ), // TIM2_CH1_ETR_3
  //( 3, TIM     ,  8, CH3N_1    , TIM8    ), // TIM8_CH3N_1
#if defined(MICROPY_HW_SPI1_SCK)
  AF( 5, SPI     ,  1, NSS       , SPI1    ), // SPI1_NSS
#endif
#if defined(MICROPY_HW_SPI3_SCK)
  AF( 6, SPI     ,  3, NSS       , SPI3    ), // SPI3_NSS
#endif
#if defined(MICROPY_HW_I2S3)
  AF( 6, I2S     ,  3, WS        , I2S3    ), // I2S3_WS
#endif
  //( 8, UART    ,  8, RX_1      , UART8   ), // UART8_RX_1
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_A15_obj = PIN(A, 15, pin_A15_af, 0, 0);

const pin_af_obj_t pin_C10_af[] = {
  AF( 3, TIM     , 10, ETR       , TIM10   ), // TIM10_ETR
#if defined(MICROPY_HW_SPI3_SCK)
  AF( 6, SPI     ,  3, SCK       , SPI3    ), // SPI3_SCK
#endif
#if defined(MICROPY_HW_I2S3)
  AF( 6, I2S     ,  3, CK        , I2S3    ), // I2S3_CK
#endif
  //( 7, USART   ,  3, TX_1      , USART3  ), // USART3_TX_1
#if defined(MICROPY_HW_UART4_TX)
  AF( 8, UART    ,  4, TX        , UART4   ), // UART4_TX
#endif
  //(12, SDIO    ,  0, D2        , SDIO    ), // SDIO_D2
  //(13, DVP     ,  0, D8        , DVP     ), // DVP_D8
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_C10_obj = PIN(C, 10, pin_C10_af, 0, 0);

const pin_af_obj_t pin_C11_af[] = {
  AF( 3, TIM     , 10, CH4       , TIM10   ), // TIM10_CH4
#if defined(MICROPY_HW_SPI3_SCK)
  AF( 6, SPI     ,  3, MISO      , SPI3    ), // SPI3_MISO
#endif
  //( 7, USART   ,  3, RX_1      , USART3  ), // USART3_RX_1
#if defined(MICROPY_HW_UART4_TX)
  AF( 8, UART    ,  4, RX        , UART4   ), // UART4_RX
#endif
  //(12, SDIO    ,  0, D3        , SDIO    ), // SDIO_D3
  //(13, DVP     ,  0, D4        , DVP     ), // DVP_D4
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_C11_obj = PIN(C, 11, pin_C11_af, 0, 0);

const pin_af_obj_t pin_C12_af[] = {
  AF( 3, TIM     , 10, BKIN      , TIM10   ), // TIM10_BKIN
#if defined(MICROPY_HW_SPI3_SCK)
  AF( 6, SPI     ,  3, MOSI      , SPI3    ), // SPI3_MOSI
#endif
#if defined(MICROPY_HW_I2S3)
  AF( 6, I2S     ,  3, SD        , I2S3    ), // I2S3_SD
#endif
  //( 7, USART   ,  3, CK_1      , USART3  ), // USART3_CK_1
#if defined(MICROPY_HW_UART5_TX)
  AF( 8, UART    ,  5, TX        , UART5   ), // UART5_TX
#endif
  //(12, SDIO    ,  0, CK        , SDIO    ), // SDIO_CK
  //(13, DVP     ,  0, D9        , DVP     ), // DVP_D9
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_C12_obj = PIN(C, 12, pin_C12_af, 0, 0);

const pin_af_obj_t pin_D2_af[] = {
  AF( 2, TIM     ,  3, ETR       , TIM3    ), // TIM3_ETR
  //( 2, TIM     ,  3, ETR_2     , TIM3    ), // TIM3_ETR_2
  //( 2, TIM     ,  3, ETR_3     , TIM3    ), // TIM3_ETR_3
#if defined(MICROPY_HW_UART5_TX)
  AF( 8, UART    ,  5, RX        , UART5   ), // UART5_RX
#endif
  //(12, SDIO    ,  0, CMD       , SDIO    ), // SDIO_CMD
  //(13, DVP     ,  0, D11       , DVP     ), // DVP_D11
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_D2_obj = PIN(D, 2, pin_D2_af, 0, 0);

// const pin_af_obj_t pin_D3_af[] = {
  //( 3, TIM     , 10, CH2_2     , TIM10   ), // TIM10_CH2_2
  //( 7, USART   ,  2, CTS_1     , USART2  ), // USART2_CTS_1
  //(12, FSMC    ,  0, CLK       , FSMC    ), // FSMC_CLK
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
// };

const pin_obj_t pin_D3_obj = PIN(D, 3, NULL, 0, 0);

// const pin_af_obj_t pin_D4_af[] = {
  //( 7, USART   ,  2, RTS_1     , USART2  ), // USART2_RTS_1
  //(12, FSMC    ,  0, NOE       , FSMC    ), // FSMC_NOE
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
// };

const pin_obj_t pin_D4_obj = PIN(D, 4, NULL, 0, 0);

// const pin_af_obj_t pin_D5_af[] = {
  //( 3, TIM     , 10, CH3_2     , TIM10   ), // TIM10_CH3_2
  //( 7, USART   ,  2, TX_1      , USART2  ), // USART2_TX_1
  //(12, FSMC    ,  0, NWE       , FSMC    ), // FSMC_NWE
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
// };

const pin_obj_t pin_D5_obj = PIN(D, 5, NULL, 0, 0);

// const pin_af_obj_t pin_D6_af[] = {
  //( 7, USART   ,  2, RX_1      , USART2  ), // USART2_RX_1
  //(12, FSMC    ,  0, NWAIT     , FSMC    ), // FSMC_NWAIT
  //(13, DVP     ,  0, D10       , DVP     ), // DVP_D10
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
// };

const pin_obj_t pin_D6_obj = PIN(D, 6, NULL, 0, 0);

// const pin_af_obj_t pin_D7_af[] = {
  //( 3, TIM     , 10, CH4_2     , TIM10   ), // TIM10_CH4_2
  //( 7, USART   ,  2, CK_1      , USART2  ), // USART2_CK_1
  //(12, FSMC    ,  0, NE1       , FSMC    ), // FSMC_NE1
  //(12, FSMC    ,  0, NCE2      , FSMC    ), // FSMC_NCE2
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
// };

const pin_obj_t pin_D7_obj = PIN(D, 7, NULL, 0, 0);

const pin_af_obj_t pin_B3_af[] = {
  //( 1, TIM     ,  2, CH2_1     , TIM2    ), // TIM2_CH2_1
  //( 3, TIM     , 10, CH1_1     , TIM10   ), // TIM10_CH1_1
#if defined(MICROPY_HW_SPI1_SCK)
  AF( 5, SPI     ,  1, SCK       , SPI1    ), // SPI1_SCK
#endif
#if defined(MICROPY_HW_SPI3_SCK)
  AF( 6, SPI     ,  3, SCK       , SPI3    ), // SPI3_SCK
#endif
#if defined(MICROPY_HW_I2S3)
  AF( 6, I2S     ,  3, CK        , I2S3    ), // I2S3_CK
#endif
  //(10, TIM     ,  2, CH2_3     , TIM2    ), // TIM2_CH2_3
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_B3_obj = PIN(B, 3, pin_B3_af, 0, 0);

const pin_af_obj_t pin_B4_af[] = {
  //( 2, TIM     ,  3, CH1_2     , TIM3    ), // TIM3_CH1_2
  //( 3, TIM     , 10, CH2_1     , TIM10   ), // TIM10_CH2_1
#if defined(MICROPY_HW_SPI3_SCK)
  AF( 6, SPI     ,  3, MISO      , SPI3    ), // SPI3_MISO
#endif
  //( 8, UART    ,  5, TX_1      , UART5   ), // UART5_TX_1
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_B4_obj = PIN(B, 4, pin_B4_af, 0, 0);

const pin_af_obj_t pin_B5_af[] = {
  //( 2, TIM     ,  3, CH2_2     , TIM3    ), // TIM3_CH2_2
  //( 3, TIM     , 10, CH3_1     , TIM10   ), // TIM10_CH3_1
  //( 4, I2C     ,  1, SMBA      , I2C1    ), // I2C1_SMBA
#if defined(MICROPY_HW_SPI1_SCK)
  AF( 5, SPI     ,  1, MISO      , SPI1    ), // SPI1_MISO
#endif
#if defined(MICROPY_HW_SPI3_SCK)
  AF( 6, SPI     ,  3, MOSI      , SPI3    ), // SPI3_MOSI
#endif
#if defined(MICROPY_HW_I2S3)
  AF( 6, I2S     ,  3, SD        , I2S3    ), // I2S3_SD
#endif
  //( 8, UART    ,  5, RX_1      , UART5   ), // UART5_RX_1
#if defined(MICROPY_HW_CAN2_TX)
  AF( 9, CAN     ,  2, RX        , CAN2    ), // CAN2_RX
#endif
  //(11, ETH     ,  0, MII_PPS_OUT, ETH     ), // ETH_MII_PPS_OUT
  //(11, ETH     ,  0, RMII_PPS_OUT, ETH     ), // ETH_RMII_PPS_OUT
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_B5_obj = PIN(B, 5, pin_B5_af, 0, 0);

const pin_af_obj_t pin_B6_af[] = {
  AF( 2, TIM     ,  4, CH1       , TIM4    ), // TIM4_CH1
  //( 3, TIM     ,  8, CH1_1     , TIM8    ), // TIM8_CH1_1
#if defined(MICROPY_HW_I2C1_SCL)
  AF( 4, I2C     ,  1, SCL       , I2C1    ), // I2C1_SCL
#endif
#if defined(MICROPY_HW_SPI1_SCK)
  AF( 5, SPI     ,  1, MOSI      , SPI1    ), // SPI1_MOSI
#endif
  //( 7, USART   ,  1, TX_1      , USART1  ), // USART1_TX_1
#if defined(MICROPY_HW_CAN2_TX)
  AF( 9, CAN     ,  2, TX        , CAN2    ), // CAN2_TX
#endif
  //(10, USBHS   ,  0, DM        , USBHS   ), // USBHS_DM
  //(10, USBHD   ,  0, DM        , USBHD   ), // USBHD_DM
  //(13, DVP     ,  0, D5        , DVP     ), // DVP_D5
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_B6_obj = PIN(B, 6, pin_B6_af, 0, 0);

const pin_af_obj_t pin_B7_af[] = {
  AF( 2, TIM     ,  4, CH2       , TIM4    ), // TIM4_CH2
  //( 3, TIM     ,  8, CH2_1     , TIM8    ), // TIM8_CH2_1
#if defined(MICROPY_HW_I2C1_SCL)
  AF( 4, I2C     ,  1, SDA       , I2C1    ), // I2C1_SDA
#endif
  //( 7, USART   ,  1, RX_1      , USART1  ), // USART1_RX_1
  //(10, USBHS   ,  0, DP        , USBHS   ), // USBHS_DP
  //(10, USBHD   ,  0, DP        , USBHD   ), // USBHD_DP
  //(12, FSMC    ,  0, NADV      , FSMC    ), // FSMC_NADV
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_B7_obj = PIN(B, 7, pin_B7_af, 0, 0);

const pin_af_obj_t pin_B8_af[] = {
  AF( 2, TIM     ,  4, CH3       , TIM4    ), // TIM4_CH3
  //( 3, TIM     ,  8, CH3_1     , TIM8    ), // TIM8_CH3_1
  AF( 3, TIM     , 10, CH1       , TIM10   ), // TIM10_CH1
#if defined(MICROPY_HW_I2C1_SCL)
  AF( 4, I2C     ,  1, SCL       , I2C1    ), // I2C1_SCL
#endif
  //( 8, UART    ,  6, TX_1      , UART6   ), // UART6_TX_1
#if defined(MICROPY_HW_CAN1_TX)
  AF( 9, CAN     ,  1, RX        , CAN1    ), // CAN1_RX
#endif
  //(11, ETH     ,  0, MII_TXD3  , ETH     ), // ETH_MII_TXD3
  //(12, SDIO    ,  0, D4        , SDIO    ), // SDIO_D4
  //(13, DVP     ,  0, D6        , DVP     ), // DVP_D6
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_B8_obj = PIN(B, 8, pin_B8_af, 0, 0);

const pin_af_obj_t pin_B9_af[] = {
  AF( 2, TIM     ,  4, CH4       , TIM4    ), // TIM4_CH4
  //( 3, TIM     ,  8, BKIN_1    , TIM8    ), // TIM8_BKIN_1
  AF( 3, TIM     , 10, CH2       , TIM10   ), // TIM10_CH2
#if defined(MICROPY_HW_I2C1_SCL)
  AF( 4, I2C     ,  1, SDA       , I2C1    ), // I2C1_SDA
#endif
  //( 8, UART    ,  6, RX_1      , UART6   ), // UART6_RX_1
#if defined(MICROPY_HW_CAN1_TX)
  AF( 9, CAN     ,  1, TX        , CAN1    ), // CAN1_TX
#endif
  //(12, SDIO    ,  0, D5        , SDIO    ), // SDIO_D5
  //(13, DVP     ,  0, D7        , DVP     ), // DVP_D7
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_B9_obj = PIN(B, 9, pin_B9_af, 0, 0);

// const pin_af_obj_t pin_E0_af[] = {
  //( 8, UART    ,  4, TX_2      , UART4   ), // UART4_TX_2
  //(12, FSMC    ,  0, NBL0      , FSMC    ), // FSMC_NBL0
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
// };

const pin_obj_t pin_E0_obj = PIN(E, 0, NULL, 0, 0);

// const pin_af_obj_t pin_E1_af[] = {
  //( 8, UART    ,  4, RX_2      , UART4   ), // UART4_RX_2
  //(12, FSMC    ,  0, NBL1      , FSMC    ), // FSMC_NBL1
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
// };

const pin_obj_t pin_E1_obj = PIN(E, 1, NULL, 0, 0);

STATIC const mp_rom_map_elem_t pin_cpu_pins_locals_dict_table[] = {
  { MP_ROM_QSTR(MP_QSTR_E2), MP_ROM_PTR(&pin_E2_obj) },
  { MP_ROM_QSTR(MP_QSTR_E3), MP_ROM_PTR(&pin_E3_obj) },
  { MP_ROM_QSTR(MP_QSTR_E4), MP_ROM_PTR(&pin_E4_obj) },
  { MP_ROM_QSTR(MP_QSTR_E5), MP_ROM_PTR(&pin_E5_obj) },
  { MP_ROM_QSTR(MP_QSTR_E6), MP_ROM_PTR(&pin_E6_obj) },
  { MP_ROM_QSTR(MP_QSTR_C13), MP_ROM_PTR(&pin_C13_obj) },
  { MP_ROM_QSTR(MP_QSTR_C14), MP_ROM_PTR(&pin_C14_obj) },
  { MP_ROM_QSTR(MP_QSTR_C15), MP_ROM_PTR(&pin_C15_obj) },
  { MP_ROM_QSTR(MP_QSTR_D0), MP_ROM_PTR(&pin_D0_obj) },
  { MP_ROM_QSTR(MP_QSTR_D1), MP_ROM_PTR(&pin_D1_obj) },
  { MP_ROM_QSTR(MP_QSTR_C0), MP_ROM_PTR(&pin_C0_obj) },
  { MP_ROM_QSTR(MP_QSTR_C1), MP_ROM_PTR(&pin_C1_obj) },
  { MP_ROM_QSTR(MP_QSTR_C2), MP_ROM_PTR(&pin_C2_obj) },
  { MP_ROM_QSTR(MP_QSTR_C3), MP_ROM_PTR(&pin_C3_obj) },
  { MP_ROM_QSTR(MP_QSTR_A0), MP_ROM_PTR(&pin_A0_obj) },
  { MP_ROM_QSTR(MP_QSTR_A1), MP_ROM_PTR(&pin_A1_obj) },
  { MP_ROM_QSTR(MP_QSTR_A2), MP_ROM_PTR(&pin_A2_obj) },
  { MP_ROM_QSTR(MP_QSTR_A3), MP_ROM_PTR(&pin_A3_obj) },
  { MP_ROM_QSTR(MP_QSTR_A4), MP_ROM_PTR(&pin_A4_obj) },
  { MP_ROM_QSTR(MP_QSTR_A5), MP_ROM_PTR(&pin_A5_obj) },
  { MP_ROM_QSTR(MP_QSTR_A6), MP_ROM_PTR(&pin_A6_obj) },
  { MP_ROM_QSTR(MP_QSTR_A7), MP_ROM_PTR(&pin_A7_obj) },
  { MP_ROM_QSTR(MP_QSTR_C4), MP_ROM_PTR(&pin_C4_obj) },
  { MP_ROM_QSTR(MP_QSTR_C5), MP_ROM_PTR(&pin_C5_obj) },
  { MP_ROM_QSTR(MP_QSTR_B0), MP_ROM_PTR(&pin_B0_obj) },
  { MP_ROM_QSTR(MP_QSTR_B1), MP_ROM_PTR(&pin_B1_obj) },
  { MP_ROM_QSTR(MP_QSTR_B2), MP_ROM_PTR(&pin_B2_obj) },
  { MP_ROM_QSTR(MP_QSTR_E7), MP_ROM_PTR(&pin_E7_obj) },
  { MP_ROM_QSTR(MP_QSTR_E8), MP_ROM_PTR(&pin_E8_obj) },
  { MP_ROM_QSTR(MP_QSTR_E9), MP_ROM_PTR(&pin_E9_obj) },
  { MP_ROM_QSTR(MP_QSTR_E10), MP_ROM_PTR(&pin_E10_obj) },
  { MP_ROM_QSTR(MP_QSTR_E11), MP_ROM_PTR(&pin_E11_obj) },
  { MP_ROM_QSTR(MP_QSTR_E12), MP_ROM_PTR(&pin_E12_obj) },
  { MP_ROM_QSTR(MP_QSTR_E13), MP_ROM_PTR(&pin_E13_obj) },
  { MP_ROM_QSTR(MP_QSTR_E14), MP_ROM_PTR(&pin_E14_obj) },
  { MP_ROM_QSTR(MP_QSTR_E15), MP_ROM_PTR(&pin_E15_obj) },
  { MP_ROM_QSTR(MP_QSTR_B10), MP_ROM_PTR(&pin_B10_obj) },
  { MP_ROM_QSTR(MP_QSTR_B11), MP_ROM_PTR(&pin_B11_obj) },
  { MP_ROM_QSTR(MP_QSTR_B12), MP_ROM_PTR(&pin_B12_obj) },
  { MP_ROM_QSTR(MP_QSTR_B13), MP_ROM_PTR(&pin_B13_obj) },
  { MP_ROM_QSTR(MP_QSTR_B14), MP_ROM_PTR(&pin_B14_obj) },
  { MP_ROM_QSTR(MP_QSTR_B15), MP_ROM_PTR(&pin_B15_obj) },
  { MP_ROM_QSTR(MP_QSTR_D8), MP_ROM_PTR(&pin_D8_obj) },
  { MP_ROM_QSTR(MP_QSTR_D9), MP_ROM_PTR(&pin_D9_obj) },
  { MP_ROM_QSTR(MP_QSTR_D10), MP_ROM_PTR(&pin_D10_obj) },
  { MP_ROM_QSTR(MP_QSTR_D11), MP_ROM_PTR(&pin_D11_obj) },
  { MP_ROM_QSTR(MP_QSTR_D12), MP_ROM_PTR(&pin_D12_obj) },
  { MP_ROM_QSTR(MP_QSTR_D13), MP_ROM_PTR(&pin_D13_obj) },
  { MP_ROM_QSTR(MP_QSTR_D14), MP_ROM_PTR(&pin_D14_obj) },
  { MP_ROM_QSTR(MP_QSTR_D15), MP_ROM_PTR(&pin_D15_obj) },
  { MP_ROM_QSTR(MP_QSTR_C6), MP_ROM_PTR(&pin_C6_obj) },
  { MP_ROM_QSTR(MP_QSTR_C7), MP_ROM_PTR(&pin_C7_obj) },
  { MP_ROM_QSTR(MP_QSTR_C8), MP_ROM_PTR(&pin_C8_obj) },
  { MP_ROM_QSTR(MP_QSTR_C9), MP_ROM_PTR(&pin_C9_obj) },
  { MP_ROM_QSTR(MP_QSTR_A8), MP_ROM_PTR(&pin_A8_obj) },
  { MP_ROM_QSTR(MP_QSTR_A9), MP_ROM_PTR(&pin_A9_obj) },
  { MP_ROM_QSTR(MP_QSTR_A10), MP_ROM_PTR(&pin_A10_obj) },
  { MP_ROM_QSTR(MP_QSTR_A11), MP_ROM_PTR(&pin_A11_obj) },
  { MP_ROM_QSTR(MP_QSTR_A12), MP_ROM_PTR(&pin_A12_obj) },
  { MP_ROM_QSTR(MP_QSTR_A13), MP_ROM_PTR(&pin_A13_obj) },
  { MP_ROM_QSTR(MP_QSTR_A14), MP_ROM_PTR(&pin_A14_obj) },
  { MP_ROM_QSTR(MP_QSTR_A15), MP_ROM_PTR(&pin_A15_obj) },
  { MP_ROM_QSTR(MP_QSTR_C10), MP_ROM_PTR(&pin_C10_obj) },
  { MP_ROM_QSTR(MP_QSTR_C11), MP_ROM_PTR(&pin_C11_obj) },
  { MP_ROM_QSTR(MP_QSTR_C12), MP_ROM_PTR(&pin_C12_obj) },
  { MP_ROM_QSTR(MP_QSTR_D2), MP_ROM_PTR(&pin_D2_obj) },
  { MP_ROM_QSTR(MP_QSTR_D3), MP_ROM_PTR(&pin_D3_obj) },
  { MP_ROM_QSTR(MP_QSTR_D4), MP_ROM_PTR(&pin_D4_obj) },
  { MP_ROM_QSTR(MP_QSTR_D5), MP_ROM_PTR(&pin_D5_obj) },
  { MP_ROM_QSTR(MP_QSTR_D6), MP_ROM_PTR(&pin_D6_obj) },
  { MP_ROM_QSTR(MP_QSTR_D7), MP_ROM_PTR(&pin_D7_obj) },
  { MP_ROM_QSTR(MP_QSTR_B3), MP_ROM_PTR(&pin_B3_obj) },
  { MP_ROM_QSTR(MP_QSTR_B4), MP_ROM_PTR(&pin_B4_obj) },
  { MP_ROM_QSTR(MP_QSTR_B5), MP_ROM_PTR(&pin_B5_obj) },
  { MP_ROM_QSTR(MP_QSTR_B6), MP_ROM_PTR(&pin_B6_obj) },
  { MP_ROM_QSTR(MP_QSTR_B7), MP_ROM_PTR(&pin_B7_obj) },
  { MP_ROM_QSTR(MP_QSTR_B8), MP_ROM_PTR(&pin_B8_obj) },
  { MP_ROM_QSTR(MP_QSTR_B9), MP_ROM_PTR(&pin_B9_obj) },
  { MP_ROM_QSTR(MP_QSTR_E0), MP_ROM_PTR(&pin_E0_obj) },
  { MP_ROM_QSTR(MP_QSTR_E1), MP_ROM_PTR(&pin_E1_obj) },
};
MP_DEFINE_CONST_DICT(pin_cpu_pins_locals_dict, pin_cpu_pins_locals_dict_table);

STATIC const mp_rom_map_elem_t pin_board_pins_locals_dict_table[] = {
  { MP_ROM_QSTR(MP_QSTR_PE2), MP_ROM_PTR(&pin_E2_obj) },
  { MP_ROM_QSTR(MP_QSTR_PE3), MP_ROM_PTR(&pin_E3_obj) },
  { MP_ROM_QSTR(MP_QSTR_PE4), MP_ROM_PTR(&pin_E4_obj) },
  { MP_ROM_QSTR(MP_QSTR_PE5), MP_ROM_PTR(&pin_E5_obj) },
  { MP_ROM_QSTR(MP_QSTR_PE6), MP_ROM_PTR(&pin_E6_obj) },
  { MP_ROM_QSTR(MP_QSTR_PC13), MP_ROM_PTR(&pin_C13_obj) },
  { MP_ROM_QSTR(MP_QSTR_PC14), MP_ROM_PTR(&pin_C14_obj) },
  { MP_ROM_QSTR(MP_QSTR_PC15), MP_ROM_PTR(&pin_C15_obj) },
  { MP_ROM_QSTR(MP_QSTR_PD0), MP_ROM_PTR(&pin_D0_obj) },
  { MP_ROM_QSTR(MP_QSTR_PD1), MP_ROM_PTR(&pin_D1_obj) },
  { MP_ROM_QSTR(MP_QSTR_PC0), MP_ROM_PTR(&pin_C0_obj) },
  { MP_ROM_QSTR(MP_QSTR_PC1), MP_ROM_PTR(&pin_C1_obj) },
  { MP_ROM_QSTR(MP_QSTR_PC2), MP_ROM_PTR(&pin_C2_obj) },
  { MP_ROM_QSTR(MP_QSTR_PC3), MP_ROM_PTR(&pin_C3_obj) },
  { MP_ROM_QSTR(MP_QSTR_PA0), MP_ROM_PTR(&pin_A0_obj) },
  { MP_ROM_QSTR(MP_QSTR_PA1), MP_ROM_PTR(&pin_A1_obj) },
  { MP_ROM_QSTR(MP_QSTR_PA2), MP_ROM_PTR(&pin_A2_obj) },
  { MP_ROM_QSTR(MP_QSTR_PA3), MP_ROM_PTR(&pin_A3_obj) },
  { MP_ROM_QSTR(MP_QSTR_PA4), MP_ROM_PTR(&pin_A4_obj) },
  { MP_ROM_QSTR(MP_QSTR_PA5), MP_ROM_PTR(&pin_A5_obj) },
  { MP_ROM_QSTR(MP_QSTR_PA6), MP_ROM_PTR(&pin_A6_obj) },
  { MP_ROM_QSTR(MP_QSTR_PA7), MP_ROM_PTR(&pin_A7_obj) },
  { MP_ROM_QSTR(MP_QSTR_PC4), MP_ROM_PTR(&pin_C4_obj) },
  { MP_ROM_QSTR(MP_QSTR_PC5), MP_ROM_PTR(&pin_C5_obj) },
  { MP_ROM_QSTR(MP_QSTR_PB0), MP_ROM_PTR(&pin_B0_obj) },
  { MP_ROM_QSTR(MP_QSTR_PB1), MP_ROM_PTR(&pin_B1_obj) },
  { MP_ROM_QSTR(MP_QSTR_PB2), MP_ROM_PTR(&pin_B2_obj) },
  { MP_ROM_QSTR(MP_QSTR_PE7), MP_ROM_PTR(&pin_E7_obj) },
  { MP_ROM_QSTR(MP_QSTR_PE8), MP_ROM_PTR(&pin_E8_obj) },
  { MP_ROM_QSTR(MP_QSTR_PE9), MP_ROM_PTR(&pin_E9_obj) },
  { MP_ROM_QSTR(MP_QSTR_PE10), MP_ROM_PTR(&pin_E10_obj) },
  { MP_ROM_QSTR(MP_QSTR_PE11), MP_ROM_PTR(&pin_E11_obj) },
  { MP_ROM_QSTR(MP_QSTR_PE12), MP_ROM_PTR(&pin_E12_obj) },
  { MP_ROM_QSTR(MP_QSTR_PE13), MP_ROM_PTR(&pin_E13_obj) },
  { MP_ROM_QSTR(MP_QSTR_PE14), MP_ROM_PTR(&pin_E14_obj) },
  { MP_ROM_QSTR(MP_QSTR_PE15), MP_ROM_PTR(&pin_E15_obj) },
  { MP_ROM_QSTR(MP_QSTR_PB10), MP_ROM_PTR(&pin_B10_obj) },
  { MP_ROM_QSTR(MP_QSTR_PB11), MP_ROM_PTR(&pin_B11_obj) },
  { MP_ROM_QSTR(MP_QSTR_PB12), MP_ROM_PTR(&pin_B12_obj) },
  { MP_ROM_QSTR(MP_QSTR_PB13), MP_ROM_PTR(&pin_B13_obj) },
  { MP_ROM_QSTR(MP_QSTR_PB14), MP_ROM_PTR(&pin_B14_obj) },
  { MP_ROM_QSTR(MP_QSTR_PB15), MP_ROM_PTR(&pin_B15_obj) },
  { MP_ROM_QSTR(MP_QSTR_PD8), MP_ROM_PTR(&pin_D8_obj) },
  { MP_ROM_QSTR(MP_QSTR_PD9), MP_ROM_PTR(&pin_D9_obj) },
  { MP_ROM_QSTR(MP_QSTR_PD10), MP_ROM_PTR(&pin_D10_obj) },
  { MP_ROM_QSTR(MP_QSTR_PD11), MP_ROM_PTR(&pin_D11_obj) },
  { MP_ROM_QSTR(MP_QSTR_PD12), MP_ROM_PTR(&pin_D12_obj) },
  { MP_ROM_QSTR(MP_QSTR_PD13), MP_ROM_PTR(&pin_D13_obj) },
  { MP_ROM_QSTR(MP_QSTR_PD14), MP_ROM_PTR(&pin_D14_obj) },
  { MP_ROM_QSTR(MP_QSTR_PD15), MP_ROM_PTR(&pin_D15_obj) },
  { MP_ROM_QSTR(MP_QSTR_PC6), MP_ROM_PTR(&pin_C6_obj) },
  { MP_ROM_QSTR(MP_QSTR_PC7), MP_ROM_PTR(&pin_C7_obj) },
  { MP_ROM_QSTR(MP_QSTR_PC8), MP_ROM_PTR(&pin_C8_obj) },
  { MP_ROM_QSTR(MP_QSTR_PC9), MP_ROM_PTR(&pin_C9_obj) },
  { MP_ROM_QSTR(MP_QSTR_PA8), MP_ROM_PTR(&pin_A8_obj) },
  { MP_ROM_QSTR(MP_QSTR_PA9), MP_ROM_PTR(&pin_A9_obj) },
  { MP_ROM_QSTR(MP_QSTR_PA10), MP_ROM_PTR(&pin_A10_obj) },
  { MP_ROM_QSTR(MP_QSTR_PA11), MP_ROM_PTR(&pin_A11_obj) },
  { MP_ROM_QSTR(MP_QSTR_PA12), MP_ROM_PTR(&pin_A12_obj) },
  { MP_ROM_QSTR(MP_QSTR_PA13), MP_ROM_PTR(&pin_A13_obj) },
  { MP_ROM_QSTR(MP_QSTR_PA14), MP_ROM_PTR(&pin_A14_obj) },
  { MP_ROM_QSTR(MP_QSTR_PA15), MP_ROM_PTR(&pin_A15_obj) },
  { MP_ROM_QSTR(MP_QSTR_PC10), MP_ROM_PTR(&pin_C10_obj) },
  { MP_ROM_QSTR(MP_QSTR_PC11), MP_ROM_PTR(&pin_C11_obj) },
  { MP_ROM_QSTR(MP_QSTR_PC12), MP_ROM_PTR(&pin_C12_obj) },
  { MP_ROM_QSTR(MP_QSTR_PD0), MP_ROM_PTR(&pin_D0_obj) },
  { MP_ROM_QSTR(MP_QSTR_PD1), MP_ROM_PTR(&pin_D1_obj) },
  { MP_ROM_QSTR(MP_QSTR_PD2), MP_ROM_PTR(&pin_D2_obj) },
  { MP_ROM_QSTR(MP_QSTR_PD3), MP_ROM_PTR(&pin_D3_obj) },
  { MP_ROM_QSTR(MP_QSTR_PD4), MP_ROM_PTR(&pin_D4_obj) },
  { MP_ROM_QSTR(MP_QSTR_PD5), MP_ROM_PTR(&pin_D5_obj) },
  { MP_ROM_QSTR(MP_QSTR_PD6), MP_ROM_PTR(&pin_D6_obj) },
  { MP_ROM_QSTR(MP_QSTR_PD7), MP_ROM_PTR(&pin_D7_obj) },
  { MP_ROM_QSTR(MP_QSTR_PB3), MP_ROM_PTR(&pin_B3_obj) },
  { MP_ROM_QSTR(MP_QSTR_PB4), MP_ROM_PTR(&pin_B4_obj) },
  { MP_ROM_QSTR(MP_QSTR_PB5), MP_ROM_PTR(&pin_B5_obj) },
  { MP_ROM_QSTR(MP_QSTR_PB6), MP_ROM_PTR(&pin_B6_obj) },
  { MP_ROM_QSTR(MP_QSTR_PB7), MP_ROM_PTR(&pin_B7_obj) },
  { MP_ROM_QSTR(MP_QSTR_PB8), MP_ROM_PTR(&pin_B8_obj) },
  { MP_ROM_QSTR(MP_QSTR_PB9), MP_ROM_PTR(&pin_B9_obj) },
  { MP_ROM_QSTR(MP_QSTR_PE0), MP_ROM_PTR(&pin_E0_obj) },
  { MP_ROM_QSTR(MP_QSTR_PE1), MP_ROM_PTR(&pin_E1_obj) },
  { MP_ROM_QSTR(MP_QSTR_USBHS_DP), MP_ROM_PTR(&pin_B7_obj) },
  { MP_ROM_QSTR(MP_QSTR_USBHS_DM), MP_ROM_PTR(&pin_B6_obj) },
  { MP_ROM_QSTR(MP_QSTR_USBFS_DP), MP_ROM_PTR(&pin_A12_obj) },
  { MP_ROM_QSTR(MP_QSTR_USBFS_DM), MP_ROM_PTR(&pin_A11_obj) },
  { MP_ROM_QSTR(MP_QSTR_ETH_TXP), MP_ROM_PTR(&pin_C8_obj) },
  { MP_ROM_QSTR(MP_QSTR_ETH_TXN), MP_ROM_PTR(&pin_C9_obj) },
  { MP_ROM_QSTR(MP_QSTR_ETH_RXP), MP_ROM_PTR(&pin_C6_obj) },
  { MP_ROM_QSTR(MP_QSTR_ETH_RXN), MP_ROM_PTR(&pin_C7_obj) },
  { MP_ROM_QSTR(MP_QSTR_SWDIO), MP_ROM_PTR(&pin_A13_obj) },
  { MP_ROM_QSTR(MP_QSTR_SWCLK), MP_ROM_PTR(&pin_A14_obj) },
};
MP_DEFINE_CONST_DICT(pin_board_pins_locals_dict, pin_board_pins_locals_dict_table);

const pin_obj_t * const pin_adc1[16] = {
  [0] = &pin_A0_obj,
  [1] = &pin_A1_obj,
  [2] = &pin_A2_obj,
  [3] = &pin_A3_obj,
  [4] = &pin_A4_obj,
  [5] = &pin_A5_obj,
  [6] = &pin_A6_obj,
  [7] = &pin_A7_obj,
  [8] = &pin_B0_obj,
  [9] = &pin_B1_obj,
  [10] = &pin_C0_obj,
  [11] = &pin_C1_obj,
  [12] = &pin_C2_obj,
  [13] = &pin_C3_obj,
  [14] = &pin_C4_obj,
  [15] = &pin_C5_obj,
};

const pin_obj_t * const pin_adc2[0] = {
};

const pin_obj_t * const pin_adc3[0] = {
};
