#ifndef MICROPY_INCLUDED_MBEDTLS_BOARD_CONFIG_H
#define MICROPY_INCLUDED_MBEDTLS_BOARD_CONFIG_H

#define MBEDTLS_ECP_NIST_OPTIM
#include "ports/stm32/mbedtls/mbedtls_config.h"

#endif /* MICROPY_INCLUDED_MBEDTLS_BOARD_CONFIG_H */
