freeze("$(PORT_DIR)/modules")
module("upip.py", base_path="$(MPY_DIR)/tools", opt=3)
module("upip_utarfile.py", base_path="$(MPY_DIR)/tools", opt=3)
module("ntptime.py", base_path="$(MPY_DIR)/extmod", opt=3)
include("$(MPY_DIR)/drivers/dht")
include("$(MPY_DIR)/drivers/onewire")
include("$(MPY_DIR)/extmod/webrepl")
include("$(MPY_DIR)/drivers/neopixel")
