MCU_SERIES = MIMXRT1052
MCU_VARIANT = MIMXRT1052DVL6B

MICROPY_FLOAT_IMPL = double
MICROPY_PY_MACHINE_SDCARD = 1
MICROPY_HW_FLASH_TYPE ?= hyperflash
MICROPY_HW_FLASH_SIZE ?= 0x4000000  # 64MB

MICROPY_HW_SDRAM_AVAIL = 1
MICROPY_HW_SDRAM_SIZE  = 0x2000000  # 32MB

JLINK_PATH ?= /media/RT1050-EVKB/

deploy: $(BUILD)/firmware.bin
	cp $< $(JLINK_PATH)
