#define GPIO_PORT_UART1	GPIOB
#define GPIO_PIN_UART1	(GPIO_PIN_6 | GPIO_PIN_7)

#define GPIO_PORT_UART2	GPIOA
#define GPIO_PIN_UART2	(GPIO_PIN_2 | GPIO_PIN_3)

#define GPIO_PORT_UART3	GPIOB
#define GPIO_PIN_UART3	(GPIO_PIN_10 | GPIO_PIN_11)

#define GPIO_PORT_UART4	GPIOA
#define GPIO_PIN_UART4	(GPIO_PIN_0 | GPIO_PIN_1)

#define GPIO_PORT_UART6	GPIOC
#define GPIO_PIN_UART6	(GPIO_PIN_6 | GPIO_PIN_7)


