USB_VID = 0x04D8
USB_PID = 0xEAD2

USB_PRODUCT = "DynOSSAT-EDU-OBC-v1.0"
USB_MANUFACTURER = "BH Dynamics"

CHIP_VARIANT = SAMD51J20A
CHIP_FAMILY = samd51

SPI_FLASH_FILESYSTEM = 1
EXTERNAL_FLASH_DEVICES = "GD25Q32C"
LONGINT_IMPL = MPZ
