USB_VID = 0
USB_PID = 0
USB_PRODUCT = "DynOSSAT-EDU OBC v1.0"
USB_MANUFACTURER = "Blackhand Dynamics SL"

CHIP_VARIANT = SAMD51J20A
CHIP_FAMILY = samd51

SPI_FLASH_FILESYSTEM = 1
EXTERNAL_FLASH_DEVICE_COUNT = 1
EXTERNAL_FLASH_DEVICES = GD25Q32C
LONGINT_IMPL = MPZ

CFLAGS_INLINE_LIMIT = 60
SUPEROPT_GC = 0
