import argparse
import re

parser = argparse.ArgumentParser(
    prog="generate_dynamic_pinctrl", description="convert preprocessed define list to table"
)

parser.add_argument("filename_out", type=argparse.FileType("wt"))
parser.add_argument("names", nargs=argparse.REMAINDER)
args = parser.parse_args()

args.filename_out.write("/* Generated by generate_dynamic_pinctrl.py\n * Do not Edit\n */\n")
for name in args.names:
    name_clean = re.sub(r"[\s\\]", "", name)
    args.filename_out.write(
        "static const machine_pin_pinmux_obj_t pinmux_{}_obj = ".format(str(name_clean))
    )
    args.filename_out.write("{\n")
    args.filename_out.write("   { &machine_pin_pinmux_type },\n")
    args.filename_out.write("   .pinmux = {},\n".format(str(name_clean)))
    args.filename_out.write('   .key = "{}",\n'.format(str(name_clean)))
    args.filename_out.write("};\n")

args.filename_out.write("static const qstr generated_dynamic_pinmuxes_names[] = {\n")
for name in args.names:
    name_clean = re.sub(r"[\s\\]", "", name)
    args.filename_out.write("   MP_QSTR_{},\n".format(str(name_clean)))
args.filename_out.write("};\n")

args.filename_out.write("static MP_DEFINE_ATTRTUPLE(\n")
args.filename_out.write("    generated_dynamic_pinmuxes_tobj,\n")
args.filename_out.write("    generated_dynamic_pinmuxes_names,\n")
args.filename_out.write("    ARRAY_SIZE(generated_dynamic_pinmuxes_names)")
for name in args.names:
    name_clean = re.sub(r"[\s\\]", "", name)
    args.filename_out.write(",\n   MP_ROM_PTR(&pinmux_{}_obj)".format(str(name_clean)))
args.filename_out.write(");\n")
