BOARD=ONYX_L452RE_P
USER_C_MODULES=../../../onyx/modules/
FROZEN_MANIFEST=boards/ONYX_L452RE_P/frozen_manifest.py
# CFLAGS_EXTRA=-DMODULE_ONYX_ENABLED=1 -DSPIDMA_MODES=1
CFLAGS_EXTRA=-DSPIDMA_MODES=1

#MAKE FILE
#CFLAGS += -Wno-error

## FILE SYSTEM
#MICROPY_VFS_FAT=1
#MICROPY_VFS_LFS2=1

## THREADING
#CFLAGS_EXTRA='-DMICROPY_PY_THREAD=1'

## REQUIRED
include Makefile
