None 0.00
press
synthio.NoteState.ATTACK 0.23
synthio.NoteState.ATTACK 0.46
synthio.NoteState.ATTACK 0.70
synthio.NoteState.ATTACK 0.93
synthio.NoteState.DECAY 1.00
synthio.NoteState.DECAY 0.91
synthio.NoteState.DECAY 0.81
synthio.NoteState.SUSTAIN 0.80
synthio.NoteState.SUSTAIN 0.80
release
synthio.NoteState.RELEASE 0.80
synthio.NoteState.RELEASE 0.71
synthio.NoteState.RELEASE 0.61
synthio.NoteState.RELEASE 0.52
synthio.NoteState.RELEASE 0.43
synthio.NoteState.RELEASE 0.34
synthio.NoteState.RELEASE 0.24
synthio.NoteState.RELEASE 0.15
synthio.NoteState.RELEASE 0.06
synthio.NoteState.RELEASE 0.00
None 0.00
