------------------------------------------------------------------------
Traceback (most recent call last):
  File "circuitpython/traceback_test_chained.py", line 25, in <module>
RuntimeError: 
------------------------------------------------------------------------

------------------------------------------------------------------------
Traceback (most recent call last):
  File "circuitpython/traceback_test_chained.py", line 23, in <module>
ZeroDivisionError: division by zero

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "circuitpython/traceback_test_chained.py", line 25, in <module>
RuntimeError: 
------------------------------------------------------------------------


------------------------------------------------------------------------
OSError: 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "circuitpython/traceback_test_chained.py", line 35, in <module>
RuntimeError: 
------------------------------------------------------------------------


------------------------------------------------------------------------
Traceback (most recent call last):
  File "circuitpython/traceback_test_chained.py", line 43, in <module>
ZeroDivisionError: division by zero

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "circuitpython/traceback_test_chained.py", line 45, in <module>
RuntimeError: 
------------------------------------------------------------------------


------------------------------------------------------------------------
Traceback (most recent call last):
  File "circuitpython/traceback_test_chained.py", line 54, in <module>
RuntimeError: 
------------------------------------------------------------------------

------------------------------------------------------------------------
Traceback (most recent call last):
  File "circuitpython/traceback_test_chained.py", line 60, in <module>
RuntimeError: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "circuitpython/traceback_test_chained.py", line 62, in <module>
ZeroDivisionError: division by zero
------------------------------------------------------------------------

------------------------------------------------------------------------
Traceback (most recent call last):
  File "circuitpython/traceback_test_chained.py", line 70, in <module>
  File "circuitpython/traceback_test_chained.py", line 68, in <module>
ZeroDivisionError: division by zero
------------------------------------------------------------------------

------------------------------------------------------------------------
Traceback (most recent call last):
  File "circuitpython/traceback_test_chained.py", line 70, in <module>
  File "circuitpython/traceback_test_chained.py", line 68, in <module>
ZeroDivisionError: division by zero
------------------------------------------------------------------------


------------------------------------------------------------------------
Traceback (most recent call last):
  File "circuitpython/traceback_test_chained.py", line 81, in <module>
Exception: inner

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "circuitpython/traceback_test_chained.py", line 83, in <module>
SomeException: outer
------------------------------------------------------------------------

------------------------------------------------------------------------
Traceback (most recent call last):
  File "circuitpython/traceback_test_chained.py", line 89, in <module>
Exception: inner

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "circuitpython/traceback_test_chained.py", line 92, in <module>
SomeException: outer
------------------------------------------------------------------------


------------------------------------------------------------------------
Traceback (most recent call last):
  File "circuitpython/traceback_test_chained.py", line 99, in <module>
RuntimeError: inner

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "circuitpython/traceback_test_chained.py", line 101, in <module>
Exception: outer
------------------------------------------------------------------------

------------------------------------------------------------------------
Traceback (most recent call last):
  File "circuitpython/traceback_test_chained.py", line 107, in <module>
RuntimeError: inner

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "circuitpython/traceback_test_chained.py", line 110, in <module>
Exception: outer
------------------------------------------------------------------------


------------------------------------------------------------------------
Traceback (most recent call last):
  File "circuitpython/traceback_test_chained.py", line 117, in <module>
RuntimeError: inner

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "circuitpython/traceback_test_chained.py", line 119, in <module>
SomeException: outer
------------------------------------------------------------------------

------------------------------------------------------------------------
Traceback (most recent call last):
  File "circuitpython/traceback_test_chained.py", line 125, in <module>
RuntimeError: inner

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "circuitpython/traceback_test_chained.py", line 128, in <module>
SomeException: outer
------------------------------------------------------------------------


