USB_VID = 0x2e8a
USB_PID = 0x100d
USB_PRODUCT = "Challenger NB RP2040 WiFi"
USB_MANUFACTURER = "Invector Labs"

CHIP_VARIANT = RP2040
CHIP_FAMILY = rp2

EXTERNAL_FLASH_DEVICES = "W25Q64JVxQ"

CIRCUITPY__EVE = 1
