module("_boot.py", opt=3)
module("apa102.py", base_path="modules", opt=3)
module("port_diag.py", base_path="modules", opt=3)
module("ntptime.py", base_path="$(MPY_DIR)/extmod", opt=3)
include("$(MPY_DIR)/drivers/dht")
include("$(MPY_DIR)/drivers/onewire")
include("$(MPY_DIR)/extmod/webrepl")
include("$(MPY_DIR)/drivers/neopixel")
