
BOARD_BRD = brd2704a
INTERNAL_FLASH_FILESYSTEM = 1
QSPI_FLASH_FILESYSTEM = 0
SPI_FLASH_FILESYSTEM = 0

MCU_SERIES = MG24
MCU_VARIANT = MGM240PB32VNA

CIRCUITPY_USB = 0
CIRCUITPY_SDCARDIO = 1

CIRCUITPY_CREATOR_ID = 0x19960000
CIRCUITPY_CREATION_ID = 0x00242704

FROZEN_MPY_DIRS += $(TOP)/frozen/Adafruit_CircuitPython_BLE
FROZEN_MPY_DIRS += $(TOP)/frozen/Adafruit_CircuitPython_Register
