#define MICROPY_HW_BOARD_NAME "i.MX RT1060 EVK"
#define MICROPY_HW_MCU_NAME   "MIMXRT1062DVJ6A"

#define BOARD_FLASH_SIZE (8 * 1024 * 1024)

#define MICROPY_HW_LED_PINMUX  IOMUXC_GPIO_AD_B0_09_GPIO1_IO09
#define MICROPY_HW_LED_PORT    GPIO1
#define MICROPY_HW_LED_PIN     9
