USB_VID = 0x239A
USB_PID = 0x80B6
USB_PRODUCT = "SAM E54 Xplained Pro"
USB_MANUFACTURER = "Microchip"

CHIP_VARIANT = SAME54P20A
CHIP_FAMILY = same54

QSPI_FLASH_FILESYSTEM = 1
EXTERNAL_FLASH_DEVICES = "N25Q256A"
LONGINT_IMPL = MPZ

CIRCUITPY_SDIOIO = 1
CIRCUITPY_CANIO = 1
