b'bar2'
KeyError
None
b'dflt'
KeyError
(b'bar1', b'foo1')
(b'foo1', b'bar1')
(b'foo3', b'bar3')
---
(b'bar1', b'foo1')
(b'foo1', b'bar1')
(b'foo3', b'bar3')
---
(b'foo1', b'bar1')
(b'foo3', b'bar3')
---
(b'foo1', b'bar1')
---
(b'bar1', b'foo1')
(b'foo1', b'bar1')
---
(b'foo1', b'bar1')
(b'foo3', b'bar3')
---
(b'foo3', b'bar3')
(b'foo1', b'bar1')
(b'bar1', b'foo1')
[b'bar1', b'foo1', b'foo3']
[b'foo1', b'bar1', b'bar3']
b'bar1'
b'foo1'
b'foo3'
