Stream.readinto 1
OSError(1,)
Stream.write <memoryview>
OSError(1,)
Stream.write <memoryview>
OSError(22,)
Stream.write <memoryview>
OSError(22,)
Stream.ioctl 4 0
OSError(22,)
Stream.write <memoryview>
Stream.write <memoryview>
Stream.write <memoryview>
Stream.write <memoryview>
Stream.write <memoryview>
Stream.write <memoryview>
Stream.write <memoryview>
Stream.write <memoryview>
OSError(1,)
Stream.write <memoryview>
Stream.write <memoryview>
Stream.write <memoryview>
Stream.write <memoryview>
Stream.write <memoryview>
OSError(1,)
