----------------------------
test_await_shield
awaiting t
waiting
waiting exited
True
True
awaiting t
waiting
waiting exited
True
True
----------------------------
test_cancel_event
waiting Event cancelled
stopping
----------------------------
test_cancel_wait
waiting
awaiting t
awaiting t
awaiting t
awaiting t
awaiting t
wait cancelled
awaiting cancelled
awaiting cancelled
awaiting cancelled
awaiting cancelled
awaiting cancelled
stopping
----------------------------
test_cancel_single_awaiter
waiting
awaiting t
awaiting t
awaiting t
awaiting t
awaiting t
awaiting cancelled
waiting exited
True
True
True
True
stopping
----------------------------
test_wait_for_shield
awaiting t
waiting
waiting exited
True
True
awaiting t
waiting
awaiting cancelled
timeout
waiting exited
----------------------------
test_cancel_wait_for_shield
awaiting t
waiting
wait cancelled
awaiting cancelled
cancelled
----------------------------
test_reuse_shield_task
awaiting t
waiting
waiting exited
True
True
waiting
wait cancelled
