----------------------------
test_await_shield
awaiting t
waiting
waiting exited
finally
True
True
awaiting t
waiting
waiting exited
finally
True
True
----------------------------
test_cancel_event
waiting Event cancelled
stopping
----------------------------
test_cancel_wait
waiting
awaiting t
awaiting t
awaiting t
awaiting t
awaiting t
wait cancelled
finally
awaiting cancelled
finally
awaiting cancelled
finally
awaiting cancelled
finally
awaiting cancelled
finally
awaiting cancelled
stopping
----------------------------
test_cancel_single_awaiter
waiting
awaiting t
awaiting t
awaiting t
awaiting t
awaiting t
finally
awaiting cancelled
waiting exited
finally
True
finally
True
finally
True
finally
True
stopping
----------------------------
test_wait_for_shield
awaiting t
waiting
waiting exited
finally
True
True
awaiting t
waiting
finally
awaiting cancelled
timeout
waiting exited
----------------------------
test_cancel_wait_for_shield
awaiting t
waiting
wait cancelled
finally
awaiting cancelled
cancelled
----------------------------
test_reuse_shield_task
awaiting t
waiting
waiting exited
finally
True
True
waiting
wait cancelled
