test <class 'VfsLfs1'>
mkfs OSError True
mount OSError True
ilistdir OSError ENOENT
remove OSError ENOENT
rmdir OSError ENOENT
rename OSError ENOENT
mkdir OSError EEXIST
chdir OSError ENOENT
/
chdir OSError ENOENT
/
stat OSError ENOENT
seek OSError EINVAL
test <class 'VfsLfs2'>
mkfs OSError True
mount OSError True
ilistdir OSError ENOENT
remove OSError ENOENT
rmdir OSError ENOENT
rename OSError ENOENT
mkdir OSError EEXIST
chdir OSError ENOENT
/
chdir OSError ENOENT
/
stat OSError ENOENT
seek OSError EINVAL
