<class 'VfsLfs2'>
readblocks
readblocks
readblocks
readblocks
readblocks
readblocks
readblocks
readblocks
readblocks
readblocks
readblocks
readblocks
readblocks
readblocks
readblocks
readblocks
readblocks
readblocks
readblocks
readblocks
readblocks
readblocks
readblocks
readblocks
readblocks
readblocks
readblocks
readblocks
readblocks
readblocks
opened
readblocks
readblocks
readblocks
readblocks
readblocks
readblocks
readblocks
readblocks
readblocks
readblocks
read 1 a
read rest aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
readblocks
OSError [Errno 5] EIO
readblocks
readblocks
readblocks
readblocks
readblocks
readblocks
readblocks
readblocks
readblocks
read 1 a
read rest aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
readblocks
OSError [Errno 22] EINVAL
readblocks
readblocks
readblocks
readblocks
readblocks
readblocks
readblocks
readblocks
readblocks
read 1 a
read rest aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
readblocks
OSError [Errno 22] EINVAL
readblocks
readblocks
readblocks
readblocks
readblocks
readblocks
readblocks
readblocks
readblocks
read 1 a
read rest aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
readblocks
OSError [Errno 22] EINVAL
readblocks
readblocks
readblocks
readblocks
readblocks
readblocks
readblocks
readblocks
readblocks
read 1 a
read rest aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
<class 'VfsFat'>
readblocks
readblocks
readblocks
readblocks
readblocks
opened
readblocks
read 1 a
read rest aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
readblocks
OSError [Errno 5] EIO
readblocks
readblocks
OSError [Errno 5] EIO
readblocks
OSError [Errno 5] EIO
readblocks
readblocks
OSError [Errno 5] EIO
readblocks
OSError [Errno 5] EIO
readblocks
readblocks
OSError [Errno 5] EIO
readblocks
OSError [Errno 5] EIO
readblocks
readblocks
OSError [Errno 5] EIO
