b'ping'
b'ping'
b'\x81\x04pong'
b'pingpingpingpingpingpingpingpingpingpingpingpingpingpingpingpingpingpingpingpingpingpingpingpingpingpingpingpingpingpingpingping'
b'\x81~\x00\x80pongpongpongpongpongpongpongpongpongpongpongpongpongpongpongpongpongpongpongpongpongpongpongpongpongpongpongpongpongpongpongpong'
b'\x00\x00\x00\x00'
b'\x81\x84\xec\x8c\x1e\x00\x88\xedja'
b''
b'\x81\x02\x88\x00'
b'\x89\x04ping'
b'\x89\x00'
b'pong'
0
1
2
ioctl: EINVAL: True
