USB_VID = 0x2E8A
USB_PID = 0x10A5
USB_PRODUCT = "Plasma 2350"
USB_MANUFACTURER = "Pimoroni"

CHIP_VARIANT = RP2350
CHIP_PACKAGE = A
CHIP_FAMILY = rp2

EXTERNAL_FLASH_DEVICES = "W25Q32JVxQ"

CIRCUITPY__EVE = 1
CIRCUITPY_ALARM = 0
