# Location of top-level MicroPython directory
MPY_DIR = ../../..

# Name of module
MOD = features5

# Source files (.c or .py)
SRC = features5.c

# Architecture to build for (x86, x64, armv7m, xtensa, xtensawin, rv32imc, rv64imc)
ARCH = rv32imc

# Link with libm.a and libgcc.a from the toolchain (required for sinf/cosf etc.)
LINK_RUNTIME = 1

# Include to get the rules for compiling and linking the module
include $(MPY_DIR)/py/dynruntime.mk
