USB_VID = 0x1B4F
USB_PID = 0x0039
USB_PRODUCT = "Pro Micro RP2350"
USB_MANUFACTURER = "SparkFun"

CHIP_VARIANT = RP2350
CHIP_PACKAGE = A
CHIP_FAMILY = rp2

EXTERNAL_FLASH_DEVICES = "W25Q128JVxQ"

CIRCUITPY_ALARM = 0
CIRCUITPY_RGBMATRIX = 0
CIRCUITPY_USB_HOST = 0

CIRCUITPY_FLOPPYIO = 0
CIRCUITPY_PICODVI = 1
