# Flash
CONFIG_FLASHMODE_QIO=y 
#CONFIG_ESPTOOLPY_FLASHMODE_QIO=y
CONFIG_ESPTOOLPY_FLASHMODE="dio"
CONFIG_ESPTOOLPY_FLASHFREQ_80M=y
CONFIG_ESPTOOLPY_AFTER_NORESET=y
CONFIG_ESPTOOLPY_FLASHSIZE_16MB=y

# Memory
CONFIG_SPIRAM=y
CONFIG_SPIRAM_MEMTEST=
CONFIG_SPIRAM_IGNORE_NOTFOUND=y
CONFIG_MBEDTLS_DEFAULT_MEM_ALLOC=y
CONFIG_SPIRAM_MALLOC_RESERVE_INTERNAL=50768


# ULP : not fixed
CONFIG_SOC_ULP_SUPPORTED=n
CONFIG_ULP_COPROC_ENABLED=n
CONFIG_ULP_COPROC_TYPE_FSM=n
