#include <mpconfigport.h>

#undef MICROPY_FSUSERMOUNT
#define MICROPY_FSUSERMOUNT             (0)
#undef MICROPY_VFS_FAT
#define MICROPY_VFS_FAT                 (0)

#undef MICROPY_PERSISTENT_CODE_LOAD
#define MICROPY_PERSISTENT_CODE_LOAD    (0)

#undef MICROPY_PY_IO_FILEIO
#define MICROPY_PY_IO_FILEIO            (0)

#undef MICROPY_PY_SYS_STDIO_BUFFER
#define MICROPY_PY_SYS_STDIO_BUFFER     (0)
#undef MICROPY_PY_BUILTINS_SLICE_ATTRS
#define MICROPY_PY_BUILTINS_SLICE_ATTRS (0)
#undef MICROPY_PY_ALL_SPECIAL_METHODS
#define MICROPY_PY_ALL_SPECIAL_METHODS  (0)
