# Networking config
CONFIG_NETWORKING=y
CONFIG_NET_IPV4=y
#CONFIG_NET_IPV6=y
CONFIG_NET_UDP=y
CONFIG_NET_TCP=y
CONFIG_NET_SOCKETS=y
CONFIG_NET_HOSTNAME_ENABLE=y
CONFIG_NET_HOSTNAME_DYNAMIC=y
CONFIG_ENTROPY_GENERATOR=y
# When no entropy driver
#CONFIG_TEST_RANDOM_GENERATOR=y
# Enable TLS sockets
CONFIG_NET_SOCKETS_SOCKOPT_TLS=y
# More than 1 context allows the gc to be late on cleaning up disused TLS sockets
CONFIG_NET_SOCKETS_TLS_MAX_CONTEXTS=2
CONFIG_NET_SOCKETS_INET_RAW=y
# Allow polling more sockets at once, the default might even be too low to allow basic functionality
CONFIG_ZVFS_POLL_MAX=10
# When using more than one interface (wifi sta + lan, wifi sta + ap), have as many IP slots as can be necessary
#CONFIG_NET_IF_MAX_IPV6_COUNT=2
#CONFIG_NET_IF_MAX_IPV4_COUNT=2

# Get MAC from device ID
CONFIG_HWINFO=y

# Buffers big enough for basic TLS with micropython.org and mip for setup without extra memory
# 16KB is the standard max TLS size for the contents, however 8KB is often sufficient
# Without CONFIG_MBEDTLS_ENABLE_HEAP=y, the LIBC malloca arena is the allocation area used
CONFIG_COMMON_LIBC_MALLOC=y
CONFIG_COMMON_LIBC_MALLOC_ARENA_SIZE=32768
CONFIG_MBEDTLS_SSL_VARIABLE_BUFFER_LENGTH=y
CONFIG_MBEDTLS_SSL_IN_CONTENT_LEN=10240
CONFIG_MBEDTLS_SSL_OUT_CONTENT_LEN=4096

# Or use external / not boot memory space via DTS
# LIBC malloc should still be bound and configured for safety instead of using whatever ram space is left
# as the default setting is (-1)
#CONFIG_COMMON_LIBC_MALLOC=y
#CONFIG_COMMON_LIBC_MALLOC_ARENA_SIZE=16384

# DNS
CONFIG_DNS_RESOLVER=y
CONFIG_DNS_RESOLVER_AUTO_INIT=y
CONFIG_DNS_RESOLVER_ADDITIONAL_QUERIES=2
CONFIG_DNS_RESOLVER_MAX_SERVERS=2
CONFIG_NET_SOCKETS_DNS_TIMEOUT=4000

# DHCP configuration.
CONFIG_NET_DHCPV4=y
#CONFIG_NET_DHCPV6=y
# Recommended for WiFi APs
CONFIG_NET_DHCPV4_SERVER=y
#CONFIG_NET_DHCPV6_SERVER=y

# Required for socket.pkt_get_info()
CONFIG_NET_BUF_POOL_USAGE=y

# Do provide a decent amount of zephyr heap, yet less than recommended if often enough:
# Most features won't be used all at the same time
#CONFIG_HEAP_MEM_POOL_SIZE=32768
#CONFIG_HEAP_MEM_POOL_IGNORE_MIN=y

# Enable heap statistics module to watch out for issues
#CONFIG_SYS_HEAP_RUNTIME_STATS=y

# Required for zephyr.shell_exec("net iface")
#CONFIG_NET_SHELL=y

# Don't use a ton of RAM for nothing with MbedTLS
#CONFIG_MBEDTLS_PSA_STATIC_KEY_SLOTS=n

# Or use static network settings
#CONFIG_NET_CONFIG_SETTINGS=y
#CONFIG_NET_CONFIG_INIT_TIMEOUT=3
#CONFIG_NET_CONFIG_NEED_IPV6=y
#CCONFIG_NET_CONFIG_NEED_IPV4=y
#CONFIG_NET_CONFIG_MY_IPV6_ADDR="2001:db8::1"
#CONFIG_NET_CONFIG_MY_IPV4_ADDR="192.0.2.1"
#CONFIG_NET_CONFIG_MY_IPV4_GW="192.0.2.2"
#CONFIG_DNS_SERVER1="192.0.2.2"

# Uncomment to enable "INFO" level net_buf logging
#CONFIG_NET_LOG=y
#CONFIG_NET_DEBUG_NET_BUF=y
# Change to 4 for "DEBUG" level
#CONFIG_SYS_LOG_NET_LEVEL=3

# Network might require manually enabling TLS features
#CONFIG_MBEDTLS_SSL_PROTO_TLS1_2=y
#CONFIG_MBEDTLS_X509_USE_C=y
#CONFIG_MBEDTLS_X509_CRT_PARSE_C=y
#CONFIG_MBEDTLS_PEM_PARSE_C=y
#CONFIG_MBEDTLS_BASE64_C=y
#CONFIG_MBEDTLS_ENTROPY_C=y
#CONFIG_MBEDTLS_CIPHER=y
#CONFIG_MBEDTLS_CIPHERSUITE_TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256=y
#CONFIG_MBEDTLS_HASH_ALL_ENABLED=y
#CONFIG_PSA_WANT_ALG_SHA_1=y
