CFLAGS_MCU += -mtune=cortex-m0plus -mcpu=cortex-m0plus -msoft-float

CFLAGS_MCU += -DCFG_TUSB_MCU=OPT_MCU_SAMD21

MPY_CROSS_MCU_ARCH = armv6m

MICROPY_HW_CODESIZE ?= 184K

ifeq ($(MICROPY_HW_CODESIZE), 236K)
FROZEN_MANIFEST ?= mcu/$(MCU_SERIES_LOWER)/manifest.py
MICROPY_HW_ROMFS_BYTES ?= 12K
CFLAGS_MCU += -DSAMD21_EXTRA_FEATURES=1
else
MICROPY_HW_ROMFS_BYTES ?= 0
CFLAGS_MCU += -DSAMD21_EXTRA_FEATURES=0
endif

MICROPY_VFS_LFS1 ?= 1

SRC_S += shared/runtime/gchelper_thumb1.s

UF2CONV_FLAGS += -f 0x68ed2b88
