USB_VID = 0x239A
USB_PID = 0x807C
USB_PRODUCT = "ARAMCON2 Badge"
USB_MANUFACTURER = "ARAMCON Badge Team"

MCU_CHIP = nrf52840

QSPI_FLASH_FILESYSTEM = 1
EXTERNAL_FLASH_DEVICES = "W25Q128JVxQ"

CIRCUITPY_DISPLAYIO = 1
