LONGINT_IMPL ?= MPZ
INTERNAL_LIBM ?= 1
USB_NUM_ENDPOINT_PAIRS ?= 0

CIRCUITPY_ANALOGIO ?= 1
CIRCUITPY_BLEIO ?= 1
CIRCUITPY_BUSDEVICE ?= 1
CIRCUITPY_BUSIO ?= 1
CIRCUITPY_DIGITALIO ?= 1
CIRCUITPY_DISPLAYIO ?= 1
CIRCUITPY_FRAMEBUFFERIO ?= 1
CIRCUITPY_NVM ?= 1
CIRCUITPY_PWMIO ?= 1
CIRCUITPY_RTC ?= 1
CIRCUITPY_WATCHDOG ?=1

ifeq ($(MCU_SERIES),MG24)
        # Not yet implemented common-hal modules:
        CIRCUITPY_AUDIOIO ?= 0
        CIRCUITPY_AUDIOCORE ?= 0
        CIRCUITPY_AUDIOPWMIO ?= 0
        CIRCUITPY_AUDIOBUSIO ?= 0
        CIRCUITPY_BITBANGIO ?= 0
        CIRCUITPY_BLEIO_HCI ?= 0
        CIRCUITPY_COUNTIO ?= 0
        CIRCUITPY_FREQUENCYIO ?= 0
        CIRCUITPY_I2CTARGET ?= 0
        CIRCUITPY_KEYPAD ?= 0
        CIRCUITPY_NEOPIXEL_WRITE ?= 0
        CIRCUITPY_PARALLELDISPLAY ?= 0
        CIRCUITPY_PULSEIO ?= 0
        CIRCUITPY_ROTARYIO ?= 0
        CIRCUITPY_TOUCHIO ?= 0
        CIRCUITPY_USB ?= 0
endif

CIRCUITPY_BUILD_EXTENSIONS ?= bin
