USB_VID = 0x239A
USB_PID = 0x80DE
USB_PRODUCT = "nanoESP32-S2 w/Wroom"
USB_MANUFACTURER = "Muselab"

IDF_TARGET = esp32s2

CIRCUITPY_ESP_FLASH_MODE = dio
CIRCUITPY_ESP_FLASH_FREQ = 40m
CIRCUITPY_ESP_FLASH_SIZE = 4MB
CIRCUITPY_ESPCAMERA = 0
