USB_VID = 0x239A
USB_PID = 0x8096
USB_PRODUCT = "UARTLogger II"
USB_MANUFACTURER = "Szymon Klause"

CHIP_VARIANT = SAMD51J19A
CHIP_FAMILY = samd51

QSPI_FLASH_FILESYSTEM = 1
EXTERNAL_FLASH_DEVICES = "W25Q32JVxQ"
LONGINT_IMPL = MPZ
