#freeze("../../modules/mch2022")
#freeze("$(MPY_DIR)/tools", ("upip.py", "upip_utarfile.py"))
#freeze("$(MPY_DIR)/drivers/dht", "dht.py")
#freeze("$(MPY_DIR)/drivers/onewire")
#freeze("$(MPY_DIR)/drivers/neopixel")
#include("$(MPY_DIR)/extmod/uasyncio/manifest.py")
#include("$(MPY_DIR)/extmod/webrepl/manifest.py")
#freeze("../../modules/generics", ("buttons.py"))
#freeze("../../modules/common", ("interface.py", "rtc.py", "upysh.py", "valuestore.py", "shell.py", "term.py", "virtualtimers.py", "system.py", "ntp.py", "_boot.py", "audio.py"))
#freeze("../../modules/common", "tasks/powermanagement.py")
#freeze("../../modules/common", "tasks/otacheck.py")
#freeze("../../modules/common", "umqtt")
#freeze("../../modules/woezel")
#freeze("../../modules/common", "dashboard/_installer_exec.py")
#freeze("../../modules/common", "dashboard/resources/woezel_repo.py")
#freeze("../../modules/core")
