# Makefile for static module example
# This demonstrates a native module using static definition pattern

# Location of top-level MicroPython directory
MPY_DIR = ../../..

# Name of module (auto-detected from MP_REGISTER_MODULE in source)
# MOD = static_module  # Not needed anymore!

# Source files
SRC = static_module.c

# Architecture to build for (x86, x64, armv7m, xtensa, xtensawin)
ARCH = x64

# Include dynruntime build rules
include $(MPY_DIR)/py/dynruntime.mk