USB_VID = 0x31e2
USB_PID = 0x2001
USB_PRODUCT = "VINA-D21"
USB_MANUFACTURER = "BDMICRO LLC"

CHIP_VARIANT = SAMD21G18A
CHIP_FAMILY = samd21

SPI_FLASH_FILESYSTEM = 1
EXTERNAL_FLASH_DEVICES = "MX25L51245G","GD25S512MD"
LONGINT_IMPL = MPZ

CIRCUITPY_BITBANGIO = 0
CIRCUITPY_BITMAPTOOLS = 0
CIRCUITPY_COUNTIO = 0
CIRCUITPY_I2CPERIPHERAL = 0
CIRCUITPY_MSGPACK = 0
CIRCUITPY_VECTORIO = 0
CIRCUITPY_BUSDEVICE = 0

CFLAGS_INLINE_LIMIT = 60
SUPEROPT_GC = 0

CFLAGS_BOARD = --param max-inline-insns-auto=15
