# More than one revision of this board is available.
# This board specifies PCB Revision 10

USB_VID = 0x31e2
USB_PID = 0x2021
USB_PRODUCT = "VINA-D51"
USB_MANUFACTURER = "BDMICRO LLC"

CHIP_VARIANT = SAMD51N20A
CHIP_FAMILY = samd51

QSPI_FLASH_FILESYSTEM = 1
EXTERNAL_FLASH_DEVICES = "MX25L51245G","GD25S512MD"
LONGINT_IMPL = MPZ
