USB_VID = 0x239A	# TODO: change to PCTEL vendor id
USB_PID = 0x80FF	# TODO: change to a PCTEL product id
USB_PRODUCT = "WSC-1450"
USB_MANUFACTURER = "PCTEL"

MCU_CHIP = nrf52840

QSPI_FLASH_FILESYSTEM = 1
EXTERNAL_FLASH_DEVICE_COUNT = 1

# External flash is Winbond W25Q32JV_IQ
EXTERNAL_FLASH_DEVICES = "W25Q32JVxQ"
