USB_VID = 0x1209
USB_PID = 0x4DDE
USB_PRODUCT = "CP Sapling M0 w/ SPI Flash"
USB_MANUFACTURER = "Oak Development Technologies"

CHIP_VARIANT = SAMD21E18A
CHIP_FAMILY = samd21

INTERNAL_FLASH_FILESYSTEM = 0
LONGINT_IMPL = MPZ
SPI_FLASH_FILESYSTEM = 1
EXTERNAL_FLASH_DEVICES = AT25DF081A

CIRCUITPY_AUDIOIO = 0
CIRCUITPY_AUDIOBUSIO = 0
