USB_VID = 0x239A
USB_PID = 0x809E
USB_PRODUCT = "Nucleo F746zg - CPy"
USB_MANUFACTURER = "STMicroelectronics"

INTERNAL_FLASH_FILESYSTEM = 1

MCU_SERIES = F7
MCU_VARIANT = STM32F746xx
MCU_PACKAGE = LQFP144

LD_COMMON = boards/common_tcm.ld
LD_FILE = boards/STM32F746xG_fs.ld
