USB_VID = 0x239A
USB_PID = 0x80C2
USB_PRODUCT = "PicoPlanet"
USB_MANUFACTURER = "bleeptrack"

CHIP_VARIANT = SAMD21E18A
CHIP_FAMILY = samd21

INTERNAL_FLASH_FILESYSTEM = 1
LONGINT_IMPL = NONE
CIRCUITPY_FULL_BUILD = 0
