USB_VID = 0x303a
USB_PID = 0x80B7
USB_PRODUCT = "MORPHESP-240"
USB_MANUFACTURER = "MORPHEANS"

IDF_TARGET = esp32s2

CIRCUITPY_ESP_FLASH_MODE = dio
CIRCUITPY_ESP_FLASH_FREQ = 40m
CIRCUITPY_ESP_FLASH_SIZE = 4MB
CIRCUITPY_ESPCAMERA = 0
