LD_FILE = boards/samd21x18-bootloader.ld
USB_VID = 0xBAB1
USB_PID = 0x1209
USB_PRODUCT = "Meow Meow"
USB_MANUFACTURER = "Electronic Cats"

INTERNAL_FLASH_FILESYSTEM = 1
LONGINT_IMPL = NONE
CIRCUITPY_SMALL_BUILD = 1

CHIP_VARIANT = SAMD21G18A
CHIP_FAMILY = samd21
