USB_VID = 0x1209
USB_PID = 0xBAB1
USB_PRODUCT = "Meow Meow"
USB_MANUFACTURER = "Electronic Cats"

CHIP_VARIANT = SAMD21G18A
CHIP_FAMILY = samd21

CIRCUITPY_PWMIO = 0

INTERNAL_FLASH_FILESYSTEM = 1
LONGINT_IMPL = NONE
CIRCUITPY_FULL_BUILD = 0
