USB_VID = 0x303A
USB_PID = 0x80F5
USB_PRODUCT = "Lolin C3 Mini"
USB_MANUFACTURER = "Wemos"

IDF_TARGET = esp32c3

INTERNAL_FLASH_FILESYSTEM = 1

CIRCUITPY_ESP_FLASH_MODE=qio
CIRCUITPY_ESP_FLASH_FREQ=80m
CIRCUITPY_ESP_FLASH_SIZE=4MB
