USB_VID = 0x303a
USB_PID = 0x810a
USB_PRODUCT = "ESP32-S2-Pico"
USB_MANUFACTURER = "Waveshare Electronics"

IDF_TARGET = esp32s2

CIRCUITPY_ESP_FLASH_MODE = qio
CIRCUITPY_ESP_FLASH_FREQ = 80m
CIRCUITPY_ESP_FLASH_SIZE = 4MB
