#define MICROPY_HW_BOARD_NAME "Pimoroni Interstate 75"
#define MICROPY_HW_MCU_NAME "rp2040"

#define CIRCUITPY_RGB_STATUS_INVERTED_PWM
#define CIRCUITPY_RGB_STATUS_R (&pin_GPIO16)
#define CIRCUITPY_RGB_STATUS_G (&pin_GPIO17)
#define CIRCUITPY_RGB_STATUS_B (&pin_GPIO18)

#define MICROPY_HW_USER_SW (&pin_GPIO23)

// These pins are unconnected
#define IGNORE_PIN_GPIO15   1
#define IGNORE_PIN_GPIO22   1
#define IGNORE_PIN_GPIO24   1
#define IGNORE_PIN_GPIO25   1
