USB_VID = 0x239A
USB_PID = 0x80B8
USB_PRODUCT = "LoC BeR M4 base board"
USB_MANUFACTURER = "Zoomax"

CHIP_VARIANT = SAMD51G19A
CHIP_FAMILY = samd51

INTERNAL_FLASH_FILESYSTEM = 1
CIRCUITPY_FULL_BUILD = 0

LONGINT_IMPL = MPZ

# No I2S on SAMD51G
CIRCUITPY_AUDIOBUSIO = 0

CIRCUITPY_BITBANG_APA102 = 1
# Override optimization to keep binary small
OPTIMIZATION_FLAGS = -Os
