<class 'SyntaxError'> annotation must be an identifier
<class 'SyntaxError'> annotation must be an identifier
<class 'ViperTypeError'> unknown type 'unknown_type'
<class 'ViperTypeError'> local 'x' used before type known
<class 'ViperTypeError'> local 'x' has type 'int' but source is 'object'
<class 'ViperTypeError'> can't implicitly convert 'ptr' to 'bool'
<class 'ViperTypeError'> return expected 'int' but got 'object'
<class 'ViperTypeError'> can't do unary op of 'ptr'
<class 'ViperTypeError'> can't do binary op between 'int' and 'object'
<class 'ViperTypeError'> comparison of int and uint
<class 'ViperTypeError'> can't load from 'int'
<class 'ViperTypeError'> can't load from 'int'
<class 'ViperTypeError'> can't store to 'int'
<class 'ViperTypeError'> can't store to 'int'
<class 'ViperTypeError'> can't store to 'int'
<class 'ViperTypeError'> can't store 'None'
<class 'ViperTypeError'> can't store 'None'
<class 'ViperTypeError'> must raise an object
<class 'ViperTypeError'> 'not' not implemented
<class 'ViperTypeError'> div/mod not implemented for uint
<class 'ViperTypeError'> div/mod not implemented for uint
<class 'ViperTypeError'> binary op  not implemented
<class 'NotImplementedError'> native raise
<class 'NotImplementedError'> native raise
<class 'NotImplementedError'> native yield
<class 'NotImplementedError'> native yield
<class 'NotImplementedError'> conversion to object
<class 'NotImplementedError'> casting
