name: Documentation issue
description: Report areas of the documentation or examples that need improvement
title: "docs: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        This form is for reporting issues with the documentation or examples provided with MicroPython.

        If you have a general question \"How Do I ...?\", please post it on [GitHub Discussions](https://github.com/orgs/micropython/discussions/) or [Discord](https://discord.gg/RB8HZSAExQ) instead of here.
  - type: checkboxes
    id: terms
    attributes:
      label: Checks
      description: |
        Before submitting your bug report, please go over these check points:
      options:
      - label: |
           I agree to follow the MicroPython [Code of Conduct](https://github.com/micropython/micropython/blob/master/CODEOFCONDUCT.md) to ensure a safe and respectful space for everyone.
        required: true
      - label: |
          I've searched for [existing issues](https://github.com/micropython/micropython/issues) and didn't find any that matched.
        required: true
  - type: input
    id: page
    attributes:
      label: Documentation URL
      description: |
        Does this issue relate to a particular page in the [online documentation](https://docs.micropython.org/en/latest/)? If yes, please paste the URL of the page:
      placeholder: |
        https://docs.micropython.org/en/latest/
  - type: textarea
    id: version
    attributes:
      label: Description
      description: |
        Please describe what was missing from the documentation and/or what was incorrect/incomplete.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to help improve MicroPython.
