USB_VID = 0x303a
USB_PID = 0x8168
USB_PRODUCT = "LOLIN S3 MINI 4MB Flash 2MB PSRAM"
USB_MANUFACTURER = "WEMOS"

IDF_TARGET = esp32s3

CIRCUITPY_ESP_FLASH_MODE = qio
CIRCUITPY_ESP_FLASH_FREQ = 80m
CIRCUITPY_ESP_FLASH_SIZE = 4MB

# OPTIMIZATION_FLAGS = -Os
CIRCUITPY_ESPCAMERA = 0

# Include these Python libraries in firmware.
FROZEN_MPY_DIRS += $(TOP)/frozen/Adafruit_CircuitPython_NeoPixel
