USB_VID = 0x239A
USB_PID = 0x802A
USB_PRODUCT = "Pitaya Go"
USB_MANUFACTURER = "Makerdiary"

MCU_CHIP = nrf52840

QSPI_FLASH_FILESYSTEM = 1
EXTERNAL_FLASH_DEVICE_COUNT = 1
EXTERNAL_FLASH_DEVICES = "MX25R6435F"
