USB_VID = 0x303A
USB_PID = 0x8145

USB_PRODUCT = "Deneyap Mini v2"
USB_MANUFACTURER = "Turkish Technology Team Foundation"

IDF_TARGET = esp32s2

CIRCUITPY_ESP_FLASH_SIZE = 4MB
CIRCUITPY_ESP_FLASH_MODE = qio
CIRCUITPY_ESP_FLASH_FREQ = 80m

CIRCUITPY_ESP_PSRAM_SIZE = 2MB
CIRCUITPY_ESP_PSRAM_MODE = qio
CIRCUITPY_ESP_PSRAM_FREQ = 80m

CIRCUITPY_LEGACY_4MB_FLASH_LAYOUT = 1
