#define BLACK   0x000000
#define GREEN   0x003000
#define BLUE    0x000030
#define CYAN    0x003030
#define RED     0x300000
#define ORANGE  0x302000
#define YELLOW  0x303000
#define PURPLE  0x300030
#define WHITE   0x303030

#define BOOT_RUNNING BLUE
#define MAIN_RUNNING GREEN
#define SAFE_MODE    YELLOW
#define ALL_DONE     GREEN
#define REPL_RUNNING WHITE

#define ACTIVE_WRITE 0x200000

#define ALL_GOOD_CYCLE_MS 2000u

#define LINE_NUMBER_TOGGLE_LENGTH 300u
#define EXCEPTION_TYPE_LENGTH_MS 1000u

#define THOUSANDS WHITE
#define HUNDREDS  BLUE
#define TENS      YELLOW
#define ONES      CYAN

#define INDENTATION_ERROR GREEN
#define SYNTAX_ERROR      CYAN
#define NAME_ERROR        WHITE
#define OS_ERROR          ORANGE
#define VALUE_ERROR       PURPLE
#define MPY_ERROR         BLUE
#define OTHER_ERROR       YELLOW
