
gmtime() at default returned [Year/Month/Day - WeekDay - HH:MM:SS] : 1970/01/01 - Thu - 00:00:00 

mktime() SUCCESSFULLY created right dtime from secs

time.localtime( 0 ) returned (1970, 1, 1, 0, 0, 0, 3, 1) (Test : PASSED)
time.localtime( 1 ) returned (1970, 1, 1, 0, 0, 1, 3, 1) (Test : PASSED)
time.localtime( 59 ) returned (1970, 1, 1, 0, 0, 59, 3, 1) (Test : PASSED)
time.localtime( 60 ) returned (1970, 1, 1, 0, 1, 0, 3, 1) (Test : PASSED)
time.localtime( 3599 ) returned (1970, 1, 1, 0, 59, 59, 3, 1) (Test : PASSED)
time.localtime( 3600 ) returned (1970, 1, 1, 1, 0, 0, 3, 1) (Test : PASSED)
time.localtime( -1 ) returned (1969, 12, 31, 23, 59, 59, 2, 365) (Test : PASSED)
time.localtime( 447549467 ) returned (1984, 3, 7, 23, 17, 47, 2, 67) (Test : PASSED)
time.localtime( -940984933 ) returned (1940, 3, 7, 23, 17, 47, 3, 67) (Test : PASSED)
time.localtime( -1072915199 ) returned (1936, 1, 2, 0, 0, 1, 3, 2) (Test : PASSED)
time.localtime( -1072915200 ) returned (1936, 1, 2, 0, 0, 0, 3, 2) (Test : PASSED)
time.localtime( -1072915201 ) returned (1936, 1, 1, 23, 59, 59, 2, 1) (Test : PASSED)
