*** RTC Tests ***

RTC init successful: 	 True

datetime is accurate: 	 True

1. Setting periodic short alarm to be triggered repeatedly in few ms in future
Alarm period set to (ms):  3000
Alarm expired :  True
Alarm set again...
Alarm expired :  True
Alarm cancelled successfully :  True

2. Setting one-shot short alarm to be triggered in few ms in future
Alarm expired :  True
Entered Cback : True

3. Setting one-shot alarm to be triggered at specified date-time
Alarm expired :  True
Entered Cback : True

4. Setting periodic alarm to be triggered at specified date-time should fail
invalid argument(s) value

RTC reset done:  True

datetime to be retrieved post soft-reset :  (2023, 1, 1, 0, 0, 0, 0, 0)
