USB_VID = 0x239A
USB_PID = 0x80D7
USB_PRODUCT = "Blip"
USB_MANUFACTURER = "Electronut Labs"

MCU_CHIP = nrf52840

INTERNAL_FLASH_FILESYSTEM = 1
CIRCUITPY_AUDIOIO = 0
CIRCUITPY_DISPLAYIO = 1
CIRCUITPY_GAMEPAD = 1
CIRCUITPY_STAGE = 1
