CMSIS_MCU = RA6M5
MCU_SERIES = m33
LD_FILES = boards/VK_RA6M5/vk_ra6m5.ld

CFLAGS += -DCFG_TUH_MAX_SPEED=OPT_MODE_HIGH_SPEED \
          -DCFG_TUD_MAX_SPEED=OPT_MODE_FULL_SPEED \
          -DCFG_TUSB_RHPORT0_MODE=OPT_MODE_DEVICE \
          -DCFG_TUSB_RHPORT1_MODE=0

# MicroPython settings
MICROPY_VFS_FAT = 1
MICROPY_HW_ENABLE_RNG = 1
MICROPY_PY_LWIP = 1
MICROPY_PY_SSL = 1
MICROPY_SSL_MBEDTLS = 1

# FSP settings
USE_FSP_OSPI = 1
USE_FSP_QSPI = 1
USE_FSP_SDHI = 1
USE_FSP_ETH = 1

CFLAGS+=-DDEFAULT_DBG_CH=9
