name: Fetch nrf port deps

runs:
  using: composite
  steps:
    - name: Get nrfutil 7+
      run: |
        wget https://developer.nordicsemi.com/.pc-tools/nrfutil/x64-linux/nrfutil
        chmod +x nrfutil
        ./nrfutil install nrf5sdk-tools
        mkdir -p $HOME/.local/bin
        mv nrfutil $HOME/.local/bin
        echo "$HOME/.local/bin" >> $GITHUB_PATH
      shell: bash
    - name: Print nrfutil version
      run: nrfutil -V
      shell: bash
