-----
ls :
-----
touch :a.py
touch :b.py
ls :
           0 a.py
           0 b.py
sha256sum :a.py
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  -
-----
cp ${TMP}/a.py :
cp ${TMP}/a.py :b.py
cp ${TMP}/a.py :c.py
cp :a.py :d.py
ls :
          30 a.py
          30 b.py
          30 c.py
          30 d.py
Hello
World
Hello
World
Hello
World
sha256sum :a.py
50f0a701dd6cd6125387b96515300c9d5294c006518f8e62fa9eea3b66587f21
50f0a701dd6cd6125387b96515300c9d5294c006518f8e62fa9eea3b66587f21  -
-----
mkdir :aaa
mkdir :bbb
cp ${TMP}/a.py :aaa
cp ${TMP}/a.py :bbb/b.py
print("Hello")
print("World")
print("Hello")
print("World")
-----
cp ${TMP}/a.py :aaa
print("Hello")
print("World")
-----
cp ${TMP}/a.py :aaa/
Up to date: aaa/a.py
cp ${TMP}/a.py :aaa/a.py/
mpremote: cp: destination is not a directory
expect error
-----
rm :b.py
rm :c.py
ls :
          30 a.py
          30 d.py
           0 aaa/
           0 bbb/
rm :aaa/a.py
rm :bbb/b.py
rmdir :aaa
rmdir :bbb
ls :
          30 a.py
          30 d.py
-----
edit :d.py
sha256sum :d.py
612c7ddb88390ac86b4174b26a6e5b52fc2f2838b234efd8f6f7c41631a49d04
Goodbye
World
-----
cp ${TMP}/package :
ls :
           0 package/
ls :package
           0 subpackage/
          43 __init__.py
          22 x.py
ls :package/subpackage
          17 __init__.py
          22 y.py
x
y
-----
cp ${TMP}/package :package2
ls :
           0 package2/
ls :package2
           0 subpackage/
          43 __init__.py
          22 x.py
ls :package2/subpackage
          17 __init__.py
          22 y.py
x
y
-----
mkdir :test
cp ${TMP}/package :test
ls :test
           0 package/
ls :test/package
           0 subpackage/
          43 __init__.py
          22 x.py
ls :test/package/subpackage
          17 __init__.py
          22 y.py
-----
cp ${TMP}/package :test/package2
ls :test
           0 package/
           0 package2/
ls :test/package2
           0 subpackage/
          43 __init__.py
          22 x.py
ls :test/package2/subpackage
          17 __init__.py
          22 y.py
-----
cp :test/package ${TMP}/copy
${TMP}/copy:
package

${TMP}/copy/package:
__init__.py
subpackage
x.py

${TMP}/copy/package/subpackage:
__init__.py
y.py
-----
cp :test/package ${TMP}/copy/package2
${TMP}/copy:
package
package2

${TMP}/copy/package2:
__init__.py
subpackage
x.py

${TMP}/copy/package2/subpackage:
__init__.py
y.py
-----
cp ${TMP}/package :
cp :package :package3
ls :
           0 package/
           0 package3/
ls :package3
           0 subpackage/
          43 __init__.py
          22 x.py
ls :package3/subpackage
          17 __init__.py
          22 y.py
-----
cp ${TMP}/package :
mkdir :package4
cp :package :package4
ls :
           0 package/
           0 package4/
ls :package4
           0 package/
ls :package4/package
           0 subpackage/
          43 __init__.py
          22 x.py
ls :package4/package/subpackage
          17 __init__.py
          22 y.py
-----
cp ${TMP}/package :
Up to date: ./package/__init__.py
Up to date: ./package/subpackage/__init__.py
Up to date: ./package/x.py
ls :
           0 package/
           0 package4/
ls :package
           0 subpackage/
          43 __init__.py
          22 x.py
ls :package/subpackage
          17 __init__.py
          23 y.py
x
y2
-----
touch :a.py
touch :b.py
cp ${TMP}/package :
rm :
removed: './a.py'
removed: './b.py'
removed: './package/subpackage/__init__.py'
removed: './package/subpackage/y.py'
removed directory: './package/subpackage'
removed: './package/__init__.py'
removed: './package/x.py'
removed directory: './package'
ls :
ls :/ramdisk
-----
touch :a.py
mkdir :testdir
cp ${TMP}/package :testdir/package
ls :testdir
           0 package/
ls :testdir/package
           0 subpackage/
          43 __init__.py
          22 x.py
rm :testdir/package
ls :/ramdisk
           0 a.py
           0 testdir/
ls :testdir
-----
ls :
rm :nonexistent
mpremote: rm: nonexistent: No such file or directory.
expect error
-----
touch :a.py
touch :b.py
cp ${TMP}/package :
cp ${TMP}/package :package2
rm :/
mpremote: rm -r: cannot remove :/ Operation not permitted
expect error
ls :
ls :/ramdisk
-----
touch :a.py
touch :b.py
cp ${TMP}/package :
rm :ramdisk
removed: 'ramdisk/a.py'
removed: 'ramdisk/b.py'
removed: 'ramdisk/package/subpackage/__init__.py'
removed: 'ramdisk/package/subpackage/y.py'
removed directory: 'ramdisk/package/subpackage'
removed: 'ramdisk/package/__init__.py'
removed: 'ramdisk/package/x.py'
removed directory: 'ramdisk/package'
skipped: 'ramdisk' (vfs mountpoint)
ls :/ramdisk
-----
touch :a.py
touch :b.py
cp ${TMP}/package :
rm :/ramdisk
removed: '/ramdisk/a.py'
removed: '/ramdisk/b.py'
removed: '/ramdisk/package/subpackage/__init__.py'
removed: '/ramdisk/package/subpackage/y.py'
removed directory: '/ramdisk/package/subpackage'
removed: '/ramdisk/package/__init__.py'
removed: '/ramdisk/package/x.py'
removed directory: '/ramdisk/package'
skipped: '/ramdisk' (vfs mountpoint)
ls :/ramdisk
-----
Local directory ${TMP} is mounted at /remote
rm :package
mpremote: rm -r not permitted on /remote directory
expect error
-----
expect error: 2
-----
