USB_VID = 0x303A
USB_PID = 0x7009
USB_PRODUCT = "ESP32-S2-DevKitC-1-N4R2"
USB_MANUFACTURER = "Espressif"

IDF_TARGET = esp32s2

CIRCUITPY_ESP_FLASH_SIZE = 4MB
CIRCUITPY_ESP_FLASH_MODE = qio
CIRCUITPY_ESP_FLASH_FREQ = 80m

CIRCUITPY_ESP_PSRAM_SIZE = 2MB
CIRCUITPY_ESP_PSRAM_MODE = qio
CIRCUITPY_ESP_PSRAM_FREQ = 80m
