/**
 * @file module_board.c
 *
 * @section License
 * Copyright (C) 2016, Erik Moqvist
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * This file is part of the Pumbaa project.
 */

#include "pumbaa.h"

/**
 * Function called when this module is imported.
 */
static mp_obj_t module_init(void)
{
    return (mp_const_none);
}

static MP_DEFINE_CONST_FUN_OBJ_0(module_init_obj, module_init);

static const mp_rom_map_elem_t module_board_globals_table[] = {
    { MP_ROM_QSTR(MP_QSTR___name__), MP_ROM_QSTR(MP_QSTR_board) },
    { MP_ROM_QSTR(MP_QSTR___init__), MP_ROM_PTR(&module_init_obj) },

    { MP_ROM_QSTR(MP_QSTR_PIN_D0), MP_ROM_INT(SAM_PA+8) },
    { MP_ROM_QSTR(MP_QSTR_PIN_D1), MP_ROM_INT(SAM_PA+9) },
    { MP_ROM_QSTR(MP_QSTR_PIN_D2), MP_ROM_INT(SAM_PB+25) },
    { MP_ROM_QSTR(MP_QSTR_PIN_D3), MP_ROM_INT(SAM_PC+28) },
    { MP_ROM_QSTR(MP_QSTR_PIN_D4), MP_ROM_INT(SAM_PC+26) },
    { MP_ROM_QSTR(MP_QSTR_PIN_D5), MP_ROM_INT(SAM_PC+25) },
    { MP_ROM_QSTR(MP_QSTR_PIN_D6), MP_ROM_INT(SAM_PC+24) },
    { MP_ROM_QSTR(MP_QSTR_PIN_D7), MP_ROM_INT(SAM_PC+23) },
    { MP_ROM_QSTR(MP_QSTR_PIN_D8), MP_ROM_INT(SAM_PC+22) },
    { MP_ROM_QSTR(MP_QSTR_PIN_D9), MP_ROM_INT(SAM_PC+21) },
    { MP_ROM_QSTR(MP_QSTR_PIN_D10), MP_ROM_INT(SAM_PA+28) },
    { MP_ROM_QSTR(MP_QSTR_PIN_D11), MP_ROM_INT(SAM_PD+7) },
    { MP_ROM_QSTR(MP_QSTR_PIN_D12), MP_ROM_INT(SAM_PD+8) },
    { MP_ROM_QSTR(MP_QSTR_PIN_D13), MP_ROM_INT(SAM_PB+27) },

    { MP_ROM_QSTR(MP_QSTR_PIN_D14), MP_ROM_INT(SAM_PD+4) },
    { MP_ROM_QSTR(MP_QSTR_PIN_D15), MP_ROM_INT(SAM_PD+5) },
    { MP_ROM_QSTR(MP_QSTR_PIN_D16), MP_ROM_INT(SAM_PA+13) },
    { MP_ROM_QSTR(MP_QSTR_PIN_D17), MP_ROM_INT(SAM_PA+12) },
    { MP_ROM_QSTR(MP_QSTR_PIN_D18), MP_ROM_INT(SAM_PA+11) },
    { MP_ROM_QSTR(MP_QSTR_PIN_D19), MP_ROM_INT(SAM_PA+10) },
    { MP_ROM_QSTR(MP_QSTR_PIN_D20), MP_ROM_INT(SAM_PB+12) },
    { MP_ROM_QSTR(MP_QSTR_PIN_D21), MP_ROM_INT(SAM_PB+13) },
    { MP_ROM_QSTR(MP_QSTR_PIN_D22), MP_ROM_INT(SAM_PB+26) },
    { MP_ROM_QSTR(MP_QSTR_PIN_D23), MP_ROM_INT(SAM_PA+14) },
    { MP_ROM_QSTR(MP_QSTR_PIN_D24), MP_ROM_INT(SAM_PA+15) },
    { MP_ROM_QSTR(MP_QSTR_PIN_D25), MP_ROM_INT(SAM_PD+0) },
    { MP_ROM_QSTR(MP_QSTR_PIN_D26), MP_ROM_INT(SAM_PD+1) },
    { MP_ROM_QSTR(MP_QSTR_PIN_D27), MP_ROM_INT(SAM_PD+2) },
    { MP_ROM_QSTR(MP_QSTR_PIN_D28), MP_ROM_INT(SAM_PD+3) },
    { MP_ROM_QSTR(MP_QSTR_PIN_D29), MP_ROM_INT(SAM_PD+6) },
    { MP_ROM_QSTR(MP_QSTR_PIN_D30), MP_ROM_INT(SAM_PD+9) },
    { MP_ROM_QSTR(MP_QSTR_PIN_D31), MP_ROM_INT(SAM_PA+7) },
    { MP_ROM_QSTR(MP_QSTR_PIN_D32), MP_ROM_INT(SAM_PD+10) },
    { MP_ROM_QSTR(MP_QSTR_PIN_D33), MP_ROM_INT(SAM_PC+1) },
    { MP_ROM_QSTR(MP_QSTR_PIN_D34), MP_ROM_INT(SAM_PC+2) },
    { MP_ROM_QSTR(MP_QSTR_PIN_D35), MP_ROM_INT(SAM_PC+3) },
    { MP_ROM_QSTR(MP_QSTR_PIN_D36), MP_ROM_INT(SAM_PC+4) },
    { MP_ROM_QSTR(MP_QSTR_PIN_D37), MP_ROM_INT(SAM_PC+5) },
    { MP_ROM_QSTR(MP_QSTR_PIN_D38), MP_ROM_INT(SAM_PC+6) },
    { MP_ROM_QSTR(MP_QSTR_PIN_D39), MP_ROM_INT(SAM_PC+7) },
    { MP_ROM_QSTR(MP_QSTR_PIN_D40), MP_ROM_INT(SAM_PC+8) },
    { MP_ROM_QSTR(MP_QSTR_PIN_D41), MP_ROM_INT(SAM_PC+9) },
    { MP_ROM_QSTR(MP_QSTR_PIN_D42), MP_ROM_INT(SAM_PA+19) },
    { MP_ROM_QSTR(MP_QSTR_PIN_D43), MP_ROM_INT(SAM_PA+20) },
    { MP_ROM_QSTR(MP_QSTR_PIN_D44), MP_ROM_INT(SAM_PC+19) },
    { MP_ROM_QSTR(MP_QSTR_PIN_D45), MP_ROM_INT(SAM_PC+18) },
    { MP_ROM_QSTR(MP_QSTR_PIN_D46), MP_ROM_INT(SAM_PC+17) },
    { MP_ROM_QSTR(MP_QSTR_PIN_D47), MP_ROM_INT(SAM_PC+16) },
    { MP_ROM_QSTR(MP_QSTR_PIN_D48), MP_ROM_INT(SAM_PC+15) },
    { MP_ROM_QSTR(MP_QSTR_PIN_D49), MP_ROM_INT(SAM_PC+14) },
    { MP_ROM_QSTR(MP_QSTR_PIN_D50), MP_ROM_INT(SAM_PC+13) },
    { MP_ROM_QSTR(MP_QSTR_PIN_D51), MP_ROM_INT(SAM_PC+12) },
    { MP_ROM_QSTR(MP_QSTR_PIN_D52), MP_ROM_INT(SAM_PB+21) },
    { MP_ROM_QSTR(MP_QSTR_PIN_D53), MP_ROM_INT(SAM_PB+14) },

    { MP_ROM_QSTR(MP_QSTR_PIN_A0), MP_ROM_INT(SAM_PA+16) },
    { MP_ROM_QSTR(MP_QSTR_PIN_A1), MP_ROM_INT(SAM_PA+24) },
    { MP_ROM_QSTR(MP_QSTR_PIN_A2), MP_ROM_INT(SAM_PA+23) },
    { MP_ROM_QSTR(MP_QSTR_PIN_A3), MP_ROM_INT(SAM_PA+22) },
    { MP_ROM_QSTR(MP_QSTR_PIN_A4), MP_ROM_INT(SAM_PA+6) },
    { MP_ROM_QSTR(MP_QSTR_PIN_A5), MP_ROM_INT(SAM_PA+4) },
    { MP_ROM_QSTR(MP_QSTR_PIN_A6), MP_ROM_INT(SAM_PA+3) },
    { MP_ROM_QSTR(MP_QSTR_PIN_A7), MP_ROM_INT(SAM_PA+2) },
    { MP_ROM_QSTR(MP_QSTR_PIN_A8), MP_ROM_INT(SAM_PB+17) },
    { MP_ROM_QSTR(MP_QSTR_PIN_A9), MP_ROM_INT(SAM_PB+18) },
    { MP_ROM_QSTR(MP_QSTR_PIN_A10), MP_ROM_INT(SAM_PB+19) },
    { MP_ROM_QSTR(MP_QSTR_PIN_A11), MP_ROM_INT(SAM_PB+20) },

    { MP_ROM_QSTR(MP_QSTR_PIN_LED), MP_ROM_INT(SAM_PB+27) },

    { MP_ROM_QSTR(MP_QSTR_PIN_DAC0), MP_ROM_INT(SAM_PB+15) },
    { MP_ROM_QSTR(MP_QSTR_PIN_DAC1), MP_ROM_INT(SAM_PB+16) },

    /* Interrupts. */
    { MP_ROM_QSTR(MP_QSTR_EXTI_D0), MP_ROM_INT(SAM_PA+8) },
    { MP_ROM_QSTR(MP_QSTR_EXTI_D1), MP_ROM_INT(SAM_PA+9) },
    { MP_ROM_QSTR(MP_QSTR_EXTI_D2), MP_ROM_INT(SAM_PB+25) },
    { MP_ROM_QSTR(MP_QSTR_EXTI_D3), MP_ROM_INT(SAM_PC+28) },
    { MP_ROM_QSTR(MP_QSTR_EXTI_D4), MP_ROM_INT(SAM_PC+26) },
    { MP_ROM_QSTR(MP_QSTR_EXTI_D5), MP_ROM_INT(SAM_PC+25) },
    { MP_ROM_QSTR(MP_QSTR_EXTI_D6), MP_ROM_INT(SAM_PC+24) },
    { MP_ROM_QSTR(MP_QSTR_EXTI_D7), MP_ROM_INT(SAM_PC+23) },
    { MP_ROM_QSTR(MP_QSTR_EXTI_D8), MP_ROM_INT(SAM_PC+22) },
    { MP_ROM_QSTR(MP_QSTR_EXTI_D9), MP_ROM_INT(SAM_PC+21) },
    { MP_ROM_QSTR(MP_QSTR_EXTI_D10), MP_ROM_INT(SAM_PA+28) },
    { MP_ROM_QSTR(MP_QSTR_EXTI_D11), MP_ROM_INT(SAM_PD+7) },
    { MP_ROM_QSTR(MP_QSTR_EXTI_D12), MP_ROM_INT(SAM_PD+8) },
    { MP_ROM_QSTR(MP_QSTR_EXTI_D13), MP_ROM_INT(SAM_PB+27) },

    { MP_ROM_QSTR(MP_QSTR_EXTI_D14), MP_ROM_INT(SAM_PD+4) },
    { MP_ROM_QSTR(MP_QSTR_EXTI_D15), MP_ROM_INT(SAM_PD+5) },
    { MP_ROM_QSTR(MP_QSTR_EXTI_D16), MP_ROM_INT(SAM_PA+13) },
    { MP_ROM_QSTR(MP_QSTR_EXTI_D17), MP_ROM_INT(SAM_PA+12) },
    { MP_ROM_QSTR(MP_QSTR_EXTI_D18), MP_ROM_INT(SAM_PA+11) },
    { MP_ROM_QSTR(MP_QSTR_EXTI_D19), MP_ROM_INT(SAM_PA+10) },
    { MP_ROM_QSTR(MP_QSTR_EXTI_D20), MP_ROM_INT(SAM_PB+12) },
    { MP_ROM_QSTR(MP_QSTR_EXTI_D21), MP_ROM_INT(SAM_PB+13) },
    { MP_ROM_QSTR(MP_QSTR_EXTI_D22), MP_ROM_INT(SAM_PB+26) },
    { MP_ROM_QSTR(MP_QSTR_EXTI_D23), MP_ROM_INT(SAM_PA+14) },
    { MP_ROM_QSTR(MP_QSTR_EXTI_D24), MP_ROM_INT(SAM_PA+15) },
    { MP_ROM_QSTR(MP_QSTR_EXTI_D25), MP_ROM_INT(SAM_PD+0) },
    { MP_ROM_QSTR(MP_QSTR_EXTI_D26), MP_ROM_INT(SAM_PD+1) },
    { MP_ROM_QSTR(MP_QSTR_EXTI_D27), MP_ROM_INT(SAM_PD+2) },
    { MP_ROM_QSTR(MP_QSTR_EXTI_D28), MP_ROM_INT(SAM_PD+3) },
    { MP_ROM_QSTR(MP_QSTR_EXTI_D29), MP_ROM_INT(SAM_PD+6) },
    { MP_ROM_QSTR(MP_QSTR_EXTI_D30), MP_ROM_INT(SAM_PD+9) },
    { MP_ROM_QSTR(MP_QSTR_EXTI_D31), MP_ROM_INT(SAM_PA+7) },
    { MP_ROM_QSTR(MP_QSTR_EXTI_D32), MP_ROM_INT(SAM_PD+10) },
    { MP_ROM_QSTR(MP_QSTR_EXTI_D33), MP_ROM_INT(SAM_PC+1) },
    { MP_ROM_QSTR(MP_QSTR_EXTI_D34), MP_ROM_INT(SAM_PC+2) },
    { MP_ROM_QSTR(MP_QSTR_EXTI_D35), MP_ROM_INT(SAM_PC+3) },
    { MP_ROM_QSTR(MP_QSTR_EXTI_D36), MP_ROM_INT(SAM_PC+4) },
    { MP_ROM_QSTR(MP_QSTR_EXTI_D37), MP_ROM_INT(SAM_PC+5) },
    { MP_ROM_QSTR(MP_QSTR_EXTI_D38), MP_ROM_INT(SAM_PC+6) },
    { MP_ROM_QSTR(MP_QSTR_EXTI_D39), MP_ROM_INT(SAM_PC+7) },
    { MP_ROM_QSTR(MP_QSTR_EXTI_D40), MP_ROM_INT(SAM_PC+8) },
    { MP_ROM_QSTR(MP_QSTR_EXTI_D41), MP_ROM_INT(SAM_PC+9) },
    { MP_ROM_QSTR(MP_QSTR_EXTI_D42), MP_ROM_INT(SAM_PA+19) },
    { MP_ROM_QSTR(MP_QSTR_EXTI_D43), MP_ROM_INT(SAM_PA+20) },
    { MP_ROM_QSTR(MP_QSTR_EXTI_D44), MP_ROM_INT(SAM_PC+19) },
    { MP_ROM_QSTR(MP_QSTR_EXTI_D45), MP_ROM_INT(SAM_PC+18) },
    { MP_ROM_QSTR(MP_QSTR_EXTI_D46), MP_ROM_INT(SAM_PC+17) },
    { MP_ROM_QSTR(MP_QSTR_EXTI_D47), MP_ROM_INT(SAM_PC+16) },
    { MP_ROM_QSTR(MP_QSTR_EXTI_D48), MP_ROM_INT(SAM_PC+15) },
    { MP_ROM_QSTR(MP_QSTR_EXTI_D49), MP_ROM_INT(SAM_PC+14) },
    { MP_ROM_QSTR(MP_QSTR_EXTI_D50), MP_ROM_INT(SAM_PC+13) },
    { MP_ROM_QSTR(MP_QSTR_EXTI_D51), MP_ROM_INT(SAM_PC+12) },
    { MP_ROM_QSTR(MP_QSTR_EXTI_D52), MP_ROM_INT(SAM_PB+21) },
    { MP_ROM_QSTR(MP_QSTR_EXTI_D53), MP_ROM_INT(SAM_PB+14) },

    { MP_ROM_QSTR(MP_QSTR_EXTI_A0), MP_ROM_INT(SAM_PA+16) },
    { MP_ROM_QSTR(MP_QSTR_EXTI_A1), MP_ROM_INT(SAM_PA+24) },
    { MP_ROM_QSTR(MP_QSTR_EXTI_A2), MP_ROM_INT(SAM_PA+23) },
    { MP_ROM_QSTR(MP_QSTR_EXTI_A3), MP_ROM_INT(SAM_PA+22) },
    { MP_ROM_QSTR(MP_QSTR_EXTI_A4), MP_ROM_INT(SAM_PA+6) },
    { MP_ROM_QSTR(MP_QSTR_EXTI_A5), MP_ROM_INT(SAM_PA+4) },
    { MP_ROM_QSTR(MP_QSTR_EXTI_A6), MP_ROM_INT(SAM_PA+3) },
    { MP_ROM_QSTR(MP_QSTR_EXTI_A7), MP_ROM_INT(SAM_PA+2) },
    { MP_ROM_QSTR(MP_QSTR_EXTI_A8), MP_ROM_INT(SAM_PB+17) },
    { MP_ROM_QSTR(MP_QSTR_EXTI_A9), MP_ROM_INT(SAM_PB+18) },
    { MP_ROM_QSTR(MP_QSTR_EXTI_A10), MP_ROM_INT(SAM_PB+19) },
    { MP_ROM_QSTR(MP_QSTR_EXTI_A11), MP_ROM_INT(SAM_PB+20) },

    { MP_ROM_QSTR(MP_QSTR_EXTI_LED), MP_ROM_INT(SAM_PB+27) },

    { MP_ROM_QSTR(MP_QSTR_EXTI_DAC0), MP_ROM_INT(SAM_PB+15) },
    { MP_ROM_QSTR(MP_QSTR_EXTI_DAC1), MP_ROM_INT(SAM_PB+16) },

    /* PWM d4 and d13 cannot be used since the timer is used for the
       system tick. */
    { MP_ROM_QSTR(MP_QSTR_PWM_D2), MP_ROM_INT(0) },
    { MP_ROM_QSTR(MP_QSTR_PWM_D3), MP_ROM_INT(1) },
    { MP_ROM_QSTR(MP_QSTR_PWM_D5), MP_ROM_INT(2) },
    { MP_ROM_QSTR(MP_QSTR_PWM_D6), MP_ROM_INT(3) },
    { MP_ROM_QSTR(MP_QSTR_PWM_D7), MP_ROM_INT(4) },
    { MP_ROM_QSTR(MP_QSTR_PWM_D8), MP_ROM_INT(5) },
    { MP_ROM_QSTR(MP_QSTR_PWM_D9), MP_ROM_INT(6) },
    { MP_ROM_QSTR(MP_QSTR_PWM_D10), MP_ROM_INT(7) },
    { MP_ROM_QSTR(MP_QSTR_PWM_D11), MP_ROM_INT(8) },
    { MP_ROM_QSTR(MP_QSTR_PWM_D12), MP_ROM_INT(9) },

    { MP_ROM_QSTR(MP_QSTR_ADC_0), MP_ROM_INT(0) },
    { MP_ROM_QSTR(MP_QSTR_DAC_0), MP_ROM_INT(0) },

    { MP_ROM_QSTR(MP_QSTR_FLASH_0), MP_ROM_INT(0) },

    { MP_ROM_QSTR(MP_QSTR_SPI_0), MP_ROM_INT(0) },
};

static MP_DEFINE_CONST_DICT(module_board_globals, module_board_globals_table);

/**
 * Board class type.
 */
const mp_obj_module_t module_board = {
    { &mp_type_module },
    .globals = (mp_obj_t)&module_board_globals,
};
