USB_VID = 0x2b04
USB_PID = 0xc00c
USB_PRODUCT = "Argon"
USB_MANUFACTURER = "Particle"

MCU_CHIP = nrf52840

QSPI_FLASH_FILESYSTEM = 1
EXTERNAL_FLASH_DEVICE_COUNT = 1
EXTERNAL_FLASH_DEVICES = "MX25L3233F"

# Support for the Ethernet FeatherWing
CIRCUITPY_NETWORK = 1
MICROPY_PY_WIZNET5K = 5500
