USB_VID = 0x1209
USB_PID = 0x4DF6
USB_PRODUCT = "RPGA Feather"
USB_MANUFACTURER = "Oak Dev Tech"

CHIP_VARIANT = RP2040
CHIP_FAMILY = rp2

EXTERNAL_FLASH_DEVICES = "W25Q16JVxQ"

CIRCUITPY__EVE = 1
CIRCUITPY_FLOPPYIO = 0
