SyntaxError: cannot combine 'b' and 't' prefixes
SyntaxError: cannot combine 'f' and 't' prefixes
SyntaxError: unclosed string
PEP 750: str(t) returns default object repr
TypeError: Templates do not support ordering
SyntaxError: Cannot mix t-string and regular string in implicit concatenation
SyntaxError: Cannot mix regular string and t-string in implicit concatenation
SyntaxError: Cannot mix t-string and regular string in multiple concatenation