Traceback (most recent call last):
  File  , line 62, in ftop
  File  , line 57, in f3
  File  , line 53, in f2
  File  , line 49, in f1
  File  , line 45, in f0
ValueError: value

limit 4
Traceback (most recent call last):
  File  , line 62, in ftop
  File  , line 57, in f3
  File  , line 53, in f2
  File  , line 49, in f1
ValueError: value

limit 3
Traceback (most recent call last):
  File  , line 62, in ftop
  File  , line 57, in f3
  File  , line 53, in f2
ValueError: value

limit 2
Traceback (most recent call last):
  File  , line 62, in ftop
  File  , line 57, in f3
ValueError: value

limit 1
Traceback (most recent call last):
  File  , line 62, in ftop
ValueError: value

limit 0
ValueError: value

limit -1
ValueError: value

True
False
