USB_VID = 0x1209
USB_PID = 0x4DDD
USB_PRODUCT = "CP Sapling"
USB_MANUFACTURER = "Oak Development Technologies"

CHIP_VARIANT = SAMD21E18A
CHIP_FAMILY = samd21

INTERNAL_FLASH_FILESYSTEM = 1
LONGINT_IMPL = NONE
CIRCUITPY_FULL_BUILD = 0
