# Location of top-level MicroPython directory
MPY_DIR = ../../..

# Name of module
MOD = Render

# Source files (.c or .py)
SRC = Game.c

# Architecture to build for (x86, x64, armv7m, xtensa, xtensawin)
ARCH = armv8m

# Include to get the rules for compiling and linking the module
include $(MPY_DIR)/py/dynruntime.mk
