USB_VID = 0x0483
USB_PID = 0xdf11
USB_PRODUCT = "Thunderpack"
USB_MANUFACTURER = "Jeremy Gillick"
USB_DEVICES = "CDC,MSC,HID"

INTERNAL_FLASH_FILESYSTEM = 1
LONGINT_IMPL = NONE

MCU_SERIES = m4
MCU_VARIANT = stm32f4
MCU_SUB_VARIANT = stm32f412cx_thunderpack
MCU_PACKAGE = 48
CMSIS_MCU = STM32F412Cx
LD_FILE = boards/STM32F412ZGTx_FLASH.ld


