CIRCUITPY_CREATOR_ID =  0xC3C30000
CIRCUITPY_CREATION_ID = 0x00320004

IDF_TARGET = esp32

CIRCUITPY_ESP_FLASH_MODE = qio
CIRCUITPY_ESP_FLASH_FREQ = 80m
CIRCUITPY_ESP_FLASH_SIZE = 4MB

CIRCUITPY_LEGACY_4MB_FLASH_LAYOUT = 1

CIRCUITPY_ESPCAMERA = 0
