*** PWM tests ***
Expected freq matches calc freq! 
 freq: 1
Exp dc(%) matches calc dc(%)! 
 dc: 50
Expected freq matches calc freq! 
 freq: 10
Exp dc(%) matches calc dc(%)! 
 dc: 75
Expected freq matches calc freq! 
 freq: 100
Exp dc(%) matches calc dc(%)! 
 dc: 25
PWM frequency must not exceed 500000 Hz
PWM frequency must be greater than 0
PWM duty in ns is larger than the period 20000000 ns
PWM duty should be specified only in one format
PWM frequency must be greater than 0
PWM duty should be specified in either ns or u16
Pin(P0_0) doesn't exist
freq_get after init (duty_u16): 1000
freq_get after init (duty_ns): 500
Expected freq matches calc freq! 
 freq: 50
Exp dc(%) matches calc dc(%)! 
 dc: 50
Expected freq matches calc freq! 
 freq: 200
Exp dc(%) matches calc dc(%)! 
 dc: 50
freq_get after freq_set: 250
PWM frequency must be greater than 0
PWM frequency must be greater than 0
PWM frequency must not exceed 500000 Hz
PWM duty in ns is larger than the period 5000000 ns
duty_u16_get after init: 32767
duty_u16_get from duty_ns: 32767
Expected freq matches calc freq! 
 freq: 100
Exp dc(%) matches calc dc(%)! 
 dc: 25
duty_u16_get after duty_u16_set: 16383
duty_ns_get after init: 2500000
duty_ns_get from duty_u16: 5000000
Expected freq matches calc freq! 
 freq: 100
Exp dc(%) matches calc dc(%)! 
 dc: 25
duty_ns_get after duty_ns_set: 2500000
PWM duty in ns is larger than the period 10000000 ns
pwm_vs_pwm_same_pin_conflict: PWM instance for Pin P16_1 already exists, call deinit() first
pwm_vs_timer_conflict: TCPWM0 counter 2 is already in use by another Timer or PWM instance
