#define MICROPY_HW_BOARD_NAME "QT Py"
#define MICROPY_HW_MCU_NAME   "SAMD21E18A"

#define MICROPY_HW_DFLL_USB_SYNC    (1)

#define MICROPY_HW_DEFAULT_UART_ID  (0)
#define MICROPY_HW_DEFAULT_I2C_ID   (1)
#define MICROPY_HW_DEFAULT_SPI_ID   (0)

#define MICROPY_HW_SPIFLASH_ID (3)
