# Location of top-level MicroPython directory
MPY_DIR = ../../..

# Name of module
MOD = features2

# Source files (.c or .py)
SRC = main.c prod.c test.py

# Architecture to build for (x86, x64, armv7m, xtensa, xtensawin)
ARCH = x64

# Link with libm.a and libgcc.a from the toolchain
LINK_RUNTIME = 1

# Include to get the rules for compiling and linking the module
include $(MPY_DIR)/py/dynruntime.mk
