USB_VID = 0x1209
USB_PID = 0xBAB0
USB_PRODUCT = "Bast WiFi"
USB_MANUFACTURER = "ElectronicCats"

IDF_TARGET = esp32s2

CIRCUITPY_NEOPIXEL_WRITE = 0

CIRCUITPY_ESP_FLASH_MODE = dio
CIRCUITPY_ESP_FLASH_FREQ = 40m
CIRCUITPY_ESP_FLASH_SIZE = 4MB
CIRCUITPY_ESPCAMERA = 0
