USB_VID = 0x1D50
USB_PID = 0x6152
USB_PRODUCT = "BlueMicro833"
USB_MANUFACTURER = "nrf52.jpconstantineau.com"

MCU_CHIP = nrf52833

INTERNAL_FLASH_FILESYSTEM = 1

CIRCUITPY_AUDIOBUSIO = 0
CIRCUITPY_AUDIOPWMIO = 0
CIRCUITPY_AUDIOMIXER = 0
CIRCUITPY_KEYPAD = 1
CIRCUITPY_NVM = 0
CIRCUITPY_ONEWIREIO = 0
CIRCUITPY_PIXELBUF = 1
CIRCUITPY_PIXELMAP = 0
CIRCUITPY_TOUCHIO = 0
