USB_VID = 0x2886
USB_PID = 0x002f
USB_PRODUCT = "Seeeduino XIAO"
USB_MANUFACTURER = "Seeed"

CHIP_VARIANT = SAMD21G18A
CHIP_FAMILY = samd21

INTERNAL_FLASH_FILESYSTEM = 1
LONGINT_IMPL = NONE
CIRCUITPY_FULL_BUILD = 0
