USB_VID = 0x1209
USB_PID = 0x3252
USB_PRODUCT = "Targett Module Clip w/Wroom"
USB_MANUFACTURER = "Targett"

IDF_TARGET = esp32s2

CIRCUITPY_ESP_FLASH_MODE = dio
CIRCUITPY_ESP_FLASH_FREQ = 40m
CIRCUITPY_ESP_FLASH_SIZE = 4MB

CIRCUITPY_ESPCAMERA = 0
