# cmake file for Pimoroni Pico LiPo 4MB

if(NOT DEFINED MICROPY_HW_FLASH_STORAGE_BYTES)
    set(MICROPY_HW_FLASH_STORAGE_BYTES 3145728)  # PICO_FLASH_SIZE_BYTES - (1 * 1024 * 1024) = 4MB - 1MB
endif()
