LD_FILE = boards/samd51x19-bootloader-external-flash.ld
USB_VID = 0x239A
USB_PID = 0x802E
USB_PRODUCT = "PyGamer"
USB_MANUFACTURER = "Adafruit Industries LLC"

QSPI_FLASH_FILESYSTEM = 1
EXTERNAL_FLASH_DEVICE_COUNT = 1
EXTERNAL_FLASH_DEVICES = GD25Q64C
LONGINT_IMPL = MPZ

# No touch on SAMD51 yet
CIRCUITPY_TOUCHIO = 0

CIRCUITPY_GAMEPADSHIFT = 1

CHIP_VARIANT = SAMD51J19A
CHIP_FAMILY = samd51

CIRCUITPY_STAGE = 1
CIRCUITPY_GAMEPAD = 1
CIRCUITPY_DISPLAYIO = 1
CIRCUITPY_AUDIOIO = 1

FROZEN_MPY_DIRS += $(TOP)/frozen/circuitpython-stage/pybadge
