USB_VID = 0x303A
USB_PID = 0x700D
USB_PRODUCT = "ESP32-S3-Box-Lite"
USB_MANUFACTURER = "Espressif"

IDF_TARGET = esp32s3

CIRCUITPY_ESP_FLASH_MODE=dio
CIRCUITPY_ESP_FLASH_FREQ=40m
CIRCUITPY_ESP_FLASH_SIZE=16MB
