#define MICROPY_HW_BOARD_NAME "ESP32-S2-WROVER"
#define MICROPY_HW_MCU_NAME "ESP32-S2"

#define MICROPY_PY_BLUETOOTH                (0)
#define MICROPY_HW_ENABLE_SDCARD            (0)

#define MICROPY_HW_I2C0_SCL (7)
#define MICROPY_HW_I2C0_SDA (6)

#define MICROPY_HW_SPI1_MOSI (35)  // SDO
#define MICROPY_HW_SPI1_MISO (36)  // SDI
#define MICROPY_HW_SPI1_SCK (34)

#define MICROPY_HW_SPI2_MOSI (18)
#define MICROPY_HW_SPI2_MISO (16)
#define MICROPY_HW_SPI2_SCK (17)
