USB_VID = 0x303A
USB_PID = 0x81B9
USB_PRODUCT = "senseBox MCU-S2 ESP32S2"
USB_MANUFACTURER = "Espressif"

IDF_TARGET = esp32s2

CIRCUITPY_ESP_FLASH_SIZE = 4MB
CIRCUITPY_ESP_FLASH_MODE = qio
CIRCUITPY_ESP_FLASH_FREQ = 80m

CIRCUITPY_ESPCAMERA = 0

CIRCUITPY_REQUIRE_I2C_PULLUPS = 0
CIRCUITPY_I2C_ALLOW_STRAPPING_PINS = 1

# Include these Python libraries in firmware.
FROZEN_MPY_DIRS += $(TOP)/frozen/Adafruit_CircuitPython_NeoPixel
