USB_VID = 0x239A
USB_PID = 0x80A4
USB_PRODUCT = "OpenMV-H7 R1"
USB_MANUFACTURER = "OpenMV, LLC"

INTERNAL_FLASH_FILESYSTEM = 1

MCU_SERIES = H7
MCU_VARIANT = STM32H743xx
MCU_PACKAGE = LQFP100_x7

LD_COMMON = boards/common_tcm.ld
LD_FILE = boards/STM32H743_fs.ld
