USB_VID = 0x239A
USB_PID = 0x806C
USB_PRODUCT = "shIRtty"
USB_MANUFACTURER = "@sarfata"

CHIP_VARIANT = SAMD21E18A
CHIP_FAMILY = samd21

INTERNAL_FLASH_FILESYSTEM = 1
LONGINT_IMPL = NONE
CIRCUITPY_FULL_BUILD = 0
