#define MICROPY_HW_BOARD_NAME "Deneyap Kart"
#define MICROPY_HW_MCU_NAME "ESP32"
#define MICROPY_PY_NETWORK_HOSTNAME_DEFAULT "DeneyapKart"

#define MICROPY_HW_I2C0_SCL (15)
#define MICROPY_HW_I2C0_SDA (4)

#define MICROPY_HW_SPI1_SCK (19)
#define MICROPY_HW_SPI1_MOSI (5)
#define MICROPY_HW_SPI1_MISO (18)
