BTN_HOME=0
BTN_MENU=1
BTN_START=2
BTN_SELECT=7
BTN_ACCEPT=3
BTN_A=BTN_ACCEPT
BTN_BACK=4
BTN_B=BTN_BACK
BTN_LEFT=8
BTN_PRESS=9
BTN_DOWN=10
BTN_UP=11
BTN_RIGHT=12

ALL_BUTTONS = [BTN_HOME, BTN_MENU, BTN_START, BTN_SELECT, BTN_ACCEPT, BTN_BACK, BTN_LEFT, BTN_PRESS, BTN_DOWN, BTN_UP, BTN_RIGHT]
DEFAULT_MAPPING = { BTN_UP: None, BTN_DOWN: None, BTN_LEFT: None, BTN_RIGHT: None, BTN_PRESS: None, BTN_A: None, BTN_B: None, BTN_SELECT: None, BTN_START: None, BTN_HOME: None, BTN_MENU: None}