USB_VID = 0x612B
USB_PID = 0x80A7
USB_PRODUCT = "ESP 12k NodeMCU"
USB_MANUFACTURER = "Ai-Thinker"

IDF_TARGET = esp32s2

CIRCUITPY_ESP_FLASH_MODE = dio
CIRCUITPY_ESP_FLASH_FREQ = 40m
CIRCUITPY_ESP_FLASH_SIZE = 4MB
