USB_VID = 0x303a
USB_PID = 0x8117
USB_PRODUCT = "LOLIN S3 16MB Flash 8MB PSRAM"
USB_MANUFACTURER = "WEMOS"

IDF_TARGET = esp32s3

CIRCUITPY_ESP_FLASH_MODE = qio
CIRCUITPY_ESP_FLASH_FREQ = 80m
CIRCUITPY_ESP_FLASH_SIZE = 16MB

CIRCUITPY_ESPCAMERA = 0
