# TODO: alif_ensemble-cmsis-dfp only supports AE722F80F55D5XX at the moment.
MCU_SERIES = E7
MCU_VARIANT = AE722F80F55D5XX
JLINK_DEV = AE302F80F55D5_HP
LD_FILE = boards/OPENMV_AE3/board.ld.S
PORT = /dev/ttyUSB0

ALIF_TOOLKIT_CFG_PART = AE302F80F55D5AE
ALIF_TOOLKIT_CFG_FILE = \"app-device-config-ae3.json\"

CORE_M55_HP := $(if $(filter M55_HP,$(MCU_CORE)),1,0)

# MicroPython settings
MICROPY_FLOAT_IMPL = float
MICROPY_PY_BLUETOOTH = $(CORE_M55_HP)
MICROPY_BLUETOOTH_NIMBLE = $(CORE_M55_HP)
MICROPY_PY_LWIP = $(CORE_M55_HP)
MICROPY_PY_NETWORK_CYW43 = $(CORE_M55_HP)
MICROPY_PY_SSL = $(CORE_M55_HP)
MICROPY_SSL_MBEDTLS = $(CORE_M55_HP)
MICROPY_PY_OPENAMP = 1
MICROPY_PY_OPENAMP_REMOTEPROC = 1
