#define MICROPY_HW_BOARD_NAME   "OpenMV-AE3"
#define MICROPY_HW_MCU_NAME     "AE302F80F55D5AE"

#define MICROPY_HW_USB_MSC      (CORE_M55_HP)
#define MICROPY_HW_ENABLE_OSPI  (CORE_M55_HP)
#define MICROPY_HW_ENABLE_UART_REPL (0)

#define MICROPY_HW_USB_VID      0x37C5
#define MICROPY_HW_USB_PID      0x16E3

#define MICROPY_HW_USB_MANUFACTURER_STRING  "OpenMV"
#define MICROPY_HW_USB_PRODUCT_FS_STRING    "OpenMV Camera"
#define MICROPY_HW_USB_MSC_INQUIRY_VENDOR_STRING "OpenMV"

extern void board_startup(void);
#define MICROPY_BOARD_STARTUP   board_startup

// This is used for alif.Flash() and USB MSC.
#define MICROPY_HW_FLASH_STORAGE_BASE_ADDR      (0)
#define MICROPY_HW_FLASH_STORAGE_BYTES          (16 * 1024 * 1024)
