# Define an equivalent for MICROPY_LONGINT_IMPL, to pass to $(MPY-TOOL) in py/mkrules.mk
# $(MPY-TOOL) needs to know what kind of longint to use (if any) to freeze long integers.
# This should correspond to the MICROPY_LONGINT_IMPL definition in mpconfigport.h.
MPY_TOOL_LONGINT_IMPL = -mlongint-impl=mpz

INTERNAL_LIBM = 1

USB_SERIAL_NUMBER_LENGTH = 16

# All nRF ports have longints.
LONGINT_IMPL = MPZ

# No DAC, so no regular audio.
CIRCUITPY_AUDIOIO = 0

# No I2S yet.
CIRCUITPY_AUDIOBUSIO = 0

# No I2CSlave implementation
CIRCUITPY_I2CSLAVE = 0

# enable NVM
CIRCUITPY_NVM = 1

# enable RTC
CIRCUITPY_RTC = 1

#LUCIAN HATES FEATURES
MICROPY_HW_LED_RX = 0
MICROPY_HW_LED_TX = 0
CIRCUITPY_DISPLAYIO = 0
CIRCUITPY_ANALOGIO = 0
CIRCUITPY_AUDIOBUSIO = 0
CIRCUITPY_AUDIOIO = 0
CIRCUITPY_BITBANGIO = 0
CIRCUITPY_BLEIO = 0
CIRCUITPY_BOARD = 0
CIRCUITPY_BUSIO = 0
CIRCUITPY_DIGITALIO = 0
CIRCUITPY_DISPLAYIO = 0
CIRCUITPY_FREQUENCYIO = 0
CIRCUITPY_GAMEPAD = 0
CIRCUITPY_GAMEPADSHIFT = 0
CIRCUITPY_I2CSLAVE = 0
CIRCUITPY_MATH = 0
CIRCUITPY_MICROCONTROLLER = 0
CIRCUITPY_NEOPIXEL_WRITE = 0
CIRCUITPY_NETWORK = 0
CIRCUITPY_NVM = 0
CIRCUITPY_OS = 0
CIRCUITPY_PIXELBUF = 0
CIRCUITPY_PULSEIO = 0
CIRCUITPY_PS2IO = 0
CIRCUITPY_RANDOM = 0
CIRCUITPY_ROTARYIO = 0
CIRCUITPY_RTC = 0
CIRCUITPY_SAMD = 0
CIRCUITPY_STAGE = 0
CIRCUITPY_STORAGE = 0
CIRCUITPY_STRUCT = 0
CIRCUITPY_SUPERVISOR = 0
CIRCUITPY_TIME = 0
CIRCUITPY_TOUCHIO = 0
CIRCUITPY_UHEAP = 0
CIRCUITPY_USB_HID = 0
CIRCUITPY_USB_MIDI = 0
CIRCUITPY_USTACK = 0
CIRCUITPY_PEW = 0

# frequencyio not yet implemented
CIRCUITPY_FREQUENCYIO = 0

# CircuitPython doesn't yet support NFC so force the NFC antenna pins to be GPIO.
# See https://github.com/adafruit/circuitpython/issues/1300
# Defined here because system_nrf52840.c doesn't #include any of our own include files.
CFLAGS += -DCONFIG_NFCT_PINS_AS_GPIOS
