# test basic usage
DMA(0)
ahb_err 0
bswap 0
busy 0
chain_to 0
enable 1
high_pri 0
inc_read 1
inc_write 1
irq_quiet 1
read_err 0
ring_sel 0
ring_size 0
size 2
sniff_en 0
treq_sel 63
write_err 0
0 0 0 25 0 <memoryview>
ValueError
# test memory copy
True
bytearray(b'\x00\x01\x02\x03\x04\x05\x06\x07') bytearray(b'\xf8\xf9\xfa\xfb\xfc\xfd\xfe\xff')
# test timing
True
bytearray(b'\x00\x01\x02\x03\x04\x05\x06\x07') bytearray(b'\xf8\xf9\xfa\xfb\xfc\xfd\xfe\xff')
# test immediate trigger
bytearray(b'\x00\x01\x02\x03\x04\x05\x06\x07') bytearray(b'\xf8\xf9\xfa\xfb\xfc\xfd\xfe\xff')
# test irq
irq fired 1
bytearray(b'\x00\x01\x02\x03\x04\x05\x06\x07') bytearray(b'\xf8\xf9\xfa\xfb\xfc\xfd\xfe\xff')
