.. warning::

   Though this MicroPython-based library is available for use in CircuitPython,
   its functionality may change in the future, perhaps significantly.
   As CircuitPython continues to develop, it may be changed
   to comply more closely with the corresponding standard Python library.
   You may need to change your code later if you rely
   on any non-standard functionality it currently provides.
