LD_FILE = boards/samd21x18-bootloader.ld
USB_VID = 0x239A
USB_PID = 0x801D
USB_PRODUCT = "Gemma M0"
USB_MANUFACTURER = "Adafruit Industries LLC"

INTERNAL_FLASH_FILESYSTEM = 1

CHIP_VARIANT = SAMD21E18A
CHIP_FAMILY = samd21
