USB_VID = 0x1B4F
USB_PID = 0xabcd
$(warning SparkFun nRF52840 MicroMod needss USB PID!)
USB_PRODUCT = "SFE_nRF52840_MicroMod"
USB_MANUFACTURER = "SparkFun Electronics"

MCU_CHIP = nrf52840

QSPI_FLASH_FILESYSTEM = 1
EXTERNAL_FLASH_DEVICE_COUNT = 1
EXTERNAL_FLASH_DEVICES = "W25Q128JV_PM"
