USB_VID = 0x2E8A
USB_PID = 0x000B
USB_PRODUCT = "Pico 2"
USB_MANUFACTURER = "Raspberry Pi"

CHIP_VARIANT = RP2350
CHIP_PACKAGE = A
CHIP_FAMILY = rp2

EXTERNAL_FLASH_DEVICES = "W25Q32JVxQ"

CIRCUITPY__EVE = 1
CIRCUITPY_ALARM = 0
CIRCUITPY_RGBMATRIX = 0
CIRCUITPY_USB_HOST = 0
