USB_VID = 0x303A
USB_PID = 0x81DA
USB_PRODUCT = "M5Stack Cardputer - CircuitPython"
USB_MANUFACTURER = "M5STACK"

IDF_TARGET = esp32s3

CIRCUITPY_ESP_FLASH_MODE = qio
CIRCUITPY_ESP_FLASH_FREQ = 80m
CIRCUITPY_ESP_FLASH_SIZE = 8MB
CIRCUITPY_ESPCAMERA = 0

CIRCUITPY_GIFIO = 1
CIRCUITPY_MAX3421E = 0
