CIRCUITPY_CREATOR_ID = 0xBA000000
CIRCUITPY_CREATION_ID = 0x0BA20001
MCU_CHIP = nrf52840

SPI_FLASH_FILESYSTEM = 1
EXTERNAL_FLASH_DEVICES = "XT25F64B,GD25Q64C"

CIRCUITPY_USB = 0

CIRCUITPY_FULL_BUILD = 1
CIRCUITPY_AUDIOBUSIO = 0
CIRCUITPY_AUDIOPWMIO = 0
CIRCUITPY_COUNTIO = 0
CIRCUITPY_NEOPIXEL_WRITE = 0
CIRCUITPY_ROTARYIO = 0
CIRCUITPY_SYNTHIO = 0
CIRCUITPY_AESIO = 0
CIRCUITPY_ANALOGIO = 1
CIRCUITPY_AUDIOCORE = 0
CIRCUITPY_AUDIOMIXER = 0
CIRCUITPY_RAINBOWIO = 0
CIRCUITPY_RGBMATRIX = 0
CIRCUITPY_ONEWIREIO = 0

CIRCUITPY_BUILD_EXTENSIONS = espruino.zip

CIRCUITPY_DISPLAYIO = 1
