USB_VID = 0x1209
USB_PID = 0x7382
USB_PRODUCT = "iLabs Challenger 840"
USB_MANUFACTURER = "Invector Labs AB"

MCU_CHIP = nrf52840

SPI_FLASH_FILESYSTEM = 1
EXTERNAL_FLASH_DEVICES = "W25Q16JVxQ,W25Q32FV,W25Q32JVxQ,W25Q64FV,W25Q64JVxQ"

FROZEN_MPY_DIRS += $(TOP)/ports/nordic/boards/challenger_840
FROZEN_MPY_DIRS += $(TOP)/frozen/Adafruit_CircuitPython_BLE
FROZEN_MPY_DIRS += $(TOP)/frozen/Adafruit_CircuitPython_NeoPixel
