set(PICO_BOARD "pimoroni_tiny2040_2mb")

# Override the MicroPython board name
list(APPEND MICROPY_DEF_BOARD
    MICROPY_HW_BOARD_NAME="Pimoroni Tiny 2040 2MB"
)

if(NOT DEFINED MICROPY_HW_FLASH_STORAGE_BYTES)
    set(MICROPY_HW_FLASH_STORAGE_BYTES 1048576)  # PICO_FLASH_SIZE_BYTES - (1 * 1024 * 1024) = 2MB - 1MB
endif()
