set(PICO_BOARD "pimoroni_tiny2040")

# Override the MicroPython board name
list(APPEND MICROPY_DEF_BOARD
    MICROPY_HW_BOARD_NAME="Pimoroni Tiny 2040 8MB"
)

if(NOT DEFINED MICROPY_HW_FLASH_STORAGE_BYTES)
    set(MICROPY_HW_FLASH_STORAGE_BYTES 7340032)  # PICO_FLASH_SIZE_BYTES - (1 * 1024 * 1024) = 8MB - 1MB
endif()
