# mp_printf
-123 +123  123
-0123
123
123
1ABCDEF
ab abc

false true
(null)
-2147483648
2147483648
80000000
80000000
abc
# vstr
tests
sts

test
tes
RuntimeError: 
RuntimeError: 
# repl
ame__

__name__        path            argv            version
version_info    implementation  platform        byteorder
maxsize         exit            stdin           stdout
stderr          modules         exc_info        getsizeof
print_exception
ementation
# attrtuple
(start=1, stop=2, step=3)
# str
1
# mpz
1
12345678
0
0
# runtime utils
TypeError: unsupported type for __abs__: 'str'
TypeError: unsupported types for __divmod__: 'str', 'str'
Warning: test
# format float
?
+1e+00
+1e+00
# binary
122
456
# scheduler
sched(0)=1
sched(1)=1
sched(2)=1
sched(3)=1
sched(4)=0
unlocked
3
2
1
0
0123456789 b'0123456789'
7300
7300
7300
7300
None
None
None
None
None
None
b'123'
b'123'
b'123'
OSError
0
OSError
None
None
frzstr1
frzmpy1
frzstr_pkg1.__init__
1
frzmpy_pkg1.__init__
1
frzstr_pkg2.mod
1
frzmpy_pkg2.mod
1
ZeroDivisionError
