USB_VID = 0x1209
USB_PID = 0xD1B6
USB_PRODUCT = "uGame22"
USB_MANUFACTURER = "Radomir Dopieralski"

CHIP_VARIANT = RP2040
CHIP_FAMILY = rp2

EXTERNAL_FLASH_DEVICES = "W25Q16JVxM"

CIRCUITPY_STAGE = 1
CIRCUITPY_AUDIOIO = 1
CIRCUITPY_AUDIOPWMIO = 1
CIRCUITPY_KEYPAD = 1

FROZEN_MPY_DIRS += $(TOP)/frozen/circuitpython-stage/ugame22
