USB_VID = 0x2E8A
USB_PID = 0x1002
USB_PRODUCT = "Pimoroni Pico LiPo (4MB)"
USB_MANUFACTURER = "Pimoroni"

CHIP_VARIANT = RP2040
CHIP_FAMILY = rp2

EXTERNAL_FLASH_DEVICES = "W25Q32JVxQ"

CIRCUITPY__EVE = 1
