MicroPython \.\+ version
Use \.\+
>>> # check REPL allows to continue input
>>> 1 \\\\
... + 2
3
>>> '"'
'"'
>>> "'"
"'"
>>> '\\\\''
"'"
>>> "\\\\""
'"'
>>> '\\\\'('
"'("
>>> "\\\\"("
'"('
>>> print("\\\\"(")
"(
>>> print('\\\\'(')
'(
>>> print("\\\\'(")
'(
>>> print('\\\\"(')
"(
>>> 'abc'
'abc'
>>> "abc"
'abc'
>>> '''abc
... def'''
'abc\\\\ndef'
>>> """ABC
... DEF"""
'ABC\\\\nDEF'
>>> print(
... 1 + 2)
3
>>> l = [1,
... 2]
>>> print(l)
[1, 2]
>>> d = {1:'one',
... 2:'two'}
>>> print(d[2])
two
>>> def f(x):
...     print(x)
...     [K
>>> f(3)
3
>>> if1=1
>>> if1 = 2
>>> print(if1)
2
>>> 
