MicroPython v1.25.0-preview.532.g8c012467d7 on 2025-04-10; linux [GCC 14.2.1] version
Use Ctrl-D to exit, Ctrl-E for paste mode
>>> # Test REPL autocompletion for underscore attributes in frozen modules
>>> 
>>> try:
...        import asyncio
... except ImportError:
...     print("SKIP")
...     raise SystemExit
... 
>>> # Simulate typing 'asyncio.' and pressing tab
>>> # The tab character after `asyncio.` below triggers the completion
>>> asyncio.
CancelledError  Task            TaskQueue       __dict__
__file__        __path__        cur_task        lock
select          sleep           sleep_ms        sys
ticks_add       ticks_diff      IOQueue         Lock
Loop            SingletonGenerator              StreamReader
StreamWriter    TimeoutError    __version__     core
create_task     current_task    funcs           gather
get_event_loop  new_event_loop  open_connection
run             run_until_complete              start_server
stream          ticks           wait_for        wait_for_ms
>>> asyncio.ticks
<function>
>>> 
