MicroPython \.\+ version
Use \.\+
>>> # tests for autocompletion
>>> import sys
>>> not_exist.[K[K[K[K[K[K[K[K[K[K
>>> not_exist[K[K[K[K[K[K[K[K[K
>>> x = '123'
>>> 1, x.isdigit()
(1, True)
>>> i = str
>>> i.lower('ABC')
'abc'
>>> x = 5
>>> x.
bit_length      from_bytes      to_bytes
>>> x.[K[K
>>> x.__class__
<class 'int'>
>>> None.[K[K[K[K[K
>>> 
