# All broadcom ports have longints.
LONGINT_IMPL = MPZ

CIRCUITPY_FULL_BUILD = 1

# Modules in FULL_BUILD that we don't support.
CIRCUITPY_ANALOGIO = 0
CIRCUITPY_AUDIOBUSIO = 0
CIRCUITPY_AUDIOIO = 0
CIRCUITPY_COUNTIO = 0
CIRCUITPY_FREQUENCYIO = 0
CIRCUITPY_I2CTARGET = 0
CIRCUITPY_NVM = 0
CIRCUITPY_PARALLELDISPLAY = 0
CIRCUITPY_PULSEIO = 0
CIRCUITPY_PWMIO = 0
CIRCUITPY_ROTARYIO = 0

CIRCUITPY_SDIOIO = 1
CIRCUITPY_VIDEOCORE = 1

INTERNAL_FLASH_FILESYSTEM = 1

USB_NUM_ENDPOINT_PAIRS = 8
USB_HIGHSPEED = 1

CIRCUITPY_BUILD_EXTENSIONS ?= disk.img.zip,kernel8.img
