USB_VID = 0x1209
USB_PID = 0x2031
USB_PRODUCT = "ES3ink"
USB_MANUFACTURER = "Czech maker"

IDF_TARGET = esp32s3

CIRCUITPY_ESP_FLASH_MODE=dio
CIRCUITPY_ESP_FLASH_FREQ=80m
CIRCUITPY_ESP_FLASH_SIZE=16MB
