USB_VID = 0x1209
USB_PID = 0xB182
USB_PRODUCT = "BBQ20 Keyboard"
USB_MANUFACTURER = "Solder Party"

CHIP_VARIANT = RP2040
CHIP_FAMILY = rp2

EXTERNAL_FLASH_DEVICES = "GD25Q16C"

CIRCUITPY__EVE = 1

FROZEN_MPY_DIRS += $(TOP)/frozen/Adafruit_CircuitPython_HID
