MCU_SERIES = MIMXRT1052
MCU_VARIANT = MIMXRT1052DVL6B

MICROPY_FLOAT_IMPL = double
MICROPY_PY_MACHINE_SDCARD = 1

JLINK_PATH ?= /media/RT1050-EVKB/

SRC_C += \
	hal/flexspi_hyper_flash.c

deploy: $(BUILD)/firmware.bin
	cp $< $(JLINK_PATH)
