USB_VID = 0x2E8A
USB_PID = 0x104A
USB_PRODUCT = "BLOK"
USB_MANUFACTURER = "Boardsource"

CHIP_VARIANT = RP2040
CHIP_FAMILY = rp2

EXTERNAL_FLASH_DEVICES = "W25Q16JVxQ"

FROZEN_MPY_DIRS += $(TOP)/frozen/Adafruit_CircuitPython_NeoPixel


# CIRCUITPY__EVE = 1
