USB_VID = 0x303A
USB_PID = 0x8148

USB_PRODUCT = "Deneyap Kart 1A v2"
USB_MANUFACTURER = "Turkish Technology Team Foundation"

IDF_TARGET = esp32s3

CIRCUITPY_ESP_FLASH_MODE = qio
CIRCUITPY_ESP_FLASH_FREQ = 80m
CIRCUITPY_ESP_FLASH_SIZE = 4MB

CIRCUITPY_ESP_PSRAM_SIZE = 8MB
CIRCUITPY_ESP_PSRAM_MODE = opi
CIRCUITPY_ESP_PSRAM_FREQ = 80m

CIRCUITPY_ESPCAMERA = 0
CIRCUITPY_BITMAPFILTER = 0
CIRCUITPY_CODEOP = 0
CIRCUITPY_PARALLELDISPLAYBUS = 0

OPTIMIZATION_FLAGS = -Os
