ValueError -1
ValueError 0
CAN 1
ValueError 3
CAN(1)
True
CAN(1, CAN.LOOPBACK, auto_restart=False)
False
True
[0, 0, 0, 0, 0, 0, 0, 0]
True [0, 0, 0, 0, 0, 0, 1, 0]
(123, False, False, 0, b'abcd')
(2047, False, False, 0, b'abcd')
(0, False, False, 0, b'abcd')
passed
[42, False, False, 0, <memoryview>] 0 bytearray(b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')
[42, False, False, 0, <memoryview>] 4 bytearray(b'1234\x00\x00\x00\x00\x00\x00')
[42, False, False, 0, <memoryview>] 8 bytearray(b'01234567\x00\x00')
[42, False, False, 0, <memoryview>] 3 bytearray(b'abc34567\x00\x00')
b'abc'
b'def'
TypeError
ValueError
TypeError
ValueError
ValueError
==== TEST extframe=True ====
CAN(1, CAN.LOOPBACK, auto_restart=False)
passed
('0x8', '0x1c', '0xa', True, b'ok')
('0x800', '0x1c00', '0xa00', True, b'ok')
('0x80000', '0x1c0000', '0xa0000', True, b'ok')
('0x8000000', '0x1c000000', '0xa000000', True, b'ok')
==== TEST rx callbacks ====
cb0
pending
cb0
full
cb0a
overflow
cb1
pending
cb1
full
cb1a
overflow
(1, False, False, 0, b'11111111')
(2, False, False, 1, b'22222222')
(4, False, False, 3, b'44444444')
(5, False, False, 0, b'55555555')
(6, False, False, 1, b'66666666')
(8, False, False, 3, b'88888888')
cb0a
pending
cb1a
pending
(1, False, False, 0, b'11111111')
(5, False, False, 0, b'55555555')
==== TEST async send ====
False
(1, False, False, 0, b'abcde')
passed
(2, False, False, 0, b'abcde')
(3, False, False, 0, b'abcde')
(4, False, False, 0, b'abcde')
==== TEST rtr messages ====
False
(5, False, True, 4, b'')
(6, False, True, 5, b'')
(7, False, True, 6, b'')
False
(32, False, True, 9, b'')
==== TEST errors ====
OSError(110,)
