USB_VID = 0x239A
USB_PID = 0x8009
USB_PRODUCT = "ATMegaZero ESP32-S2"
USB_MANUFACTURER = "ATMegaZero"

IDF_TARGET = esp32s2

CIRCUITPY_ESP_FLASH_MODE = qio
CIRCUITPY_ESP_FLASH_FREQ = 40m
CIRCUITPY_ESP_FLASH_SIZE = 16MB
