USB_VID = 0x239A
USB_PID = 0x807A
USB_PRODUCT = "ARAMCON Badge 2019"
USB_MANUFACTURER = "ARAMCON Badge Team"

MCU_CHIP = nrf52840

QSPI_FLASH_FILESYSTEM = 1
EXTERNAL_FLASH_DEVICES = "GD25Q16C"

CIRCUITPY_DISPLAYIO = 1

CIRCUITPY_REQUIRE_I2C_PULLUPS = 0
