LD_FILE = boards/samd21x18-bootloader-external-flash-crystalless.ld
USB_VID = 0x1B4F
USB_PID = 0x8D24
USB_PRODUCT = "SparkFun Qwiic Micro"
USB_MANUFACTURER = "SparkFun Electronics"

CHIP_VARIANT = SAMD21E18A
CHIP_FAMILY = samd21

INTERNAL_FLASH_FILESYSTEM = 1
LONGINT_IMPL = NONE

CIRCUITPY_SMALL_BUILD = 1
SUPEROPT_GC = 0
