USB_VID = 0x303A
USB_PID = 0x4001
USB_PRODUCT = "Flipper Zero Wi-Fi Dev"
USB_MANUFACTURER = "Flipper Devices Inc."

IDF_TARGET = esp32s2

CIRCUITPY_ESP_FLASH_MODE = dio
CIRCUITPY_ESP_FLASH_FREQ = 40m
CIRCUITPY_ESP_FLASH_SIZE = 4MB

CIRCUITPY_ESP_PSRAM_SIZE = 2MB
CIRCUITPY_ESP_PSRAM_MODE = qio
CIRCUITPY_ESP_PSRAM_FREQ = 40m
