USB_VID = 0x2E8A
USB_PID = 0x101F
USB_PRODUCT = "RP2040-One"
USB_MANUFACTURER = "Waveshare Electronics"

CHIP_VARIANT = RP2040
CHIP_FAMILY = rp2

EXTERNAL_FLASH_DEVICES = "W25Q32JVSSIQ"

CIRCUITPY__EVE = 1
CIRCUITPY_BUILD_EXTENSIONS = bin,uf2,u2if
