USB_VID = 0x303A
USB_PID = 0x80AA
USB_PRODUCT = "Franzininho WIFI w/Wroom"
USB_MANUFACTURER = "Espressif"

IDF_TARGET = esp32s2

CIRCUITPY_ESP_FLASH_MODE = dio
CIRCUITPY_ESP_FLASH_FREQ = 40m
CIRCUITPY_ESP_FLASH_SIZE = 4MB
CIRCUITPY_ESPCAMERA = 0
