USB_VID = 0x303A
USB_PID = 0x80AD
USB_PRODUCT = "Franzininho WIFI w/Wrover"
USB_MANUFACTURER = "Espressif"

IDF_TARGET = esp32s2

CIRCUITPY_ESP_FLASH_MODE = dio
CIRCUITPY_ESP_FLASH_FREQ = 40m
CIRCUITPY_ESP_FLASH_SIZE = 4MB
