USB_VID = 0x239A
USB_PID = 0x8126
USB_PRODUCT = "MatrixPortal S3"
USB_MANUFACTURER = "Adafruit"

IDF_TARGET = esp32s3

CIRCUITPY_ESP_FLASH_MODE = dio
CIRCUITPY_ESP_FLASH_FREQ = 40m
CIRCUITPY_ESP_FLASH_SIZE = 8MB

CIRCUITPY_ESP32_CAMERA = 0
