USB_VID = 0x1209
USB_PID = 0xBAB8
USB_PRODUCT = "NFC Copy Cat"
USB_MANUFACTURER = "Electronic Cats"

CHIP_VARIANT = SAMD21E18A
CHIP_FAMILY = samd21

SPI_FLASH_FILESYSTEM = 1
EXTERNAL_FLASH_DEVICES = "GD25Q16C"
LONGINT_IMPL = NONE

CIRCUITPY_FULL_BUILD = 0
