USB_VID = 0x239A
USB_PID = 0x8070
USB_PRODUCT = "Bluebird"
USB_MANUFACTURER = "Teknikio"

MCU_CHIP = nrf52840

INTERNAL_FLASH_FILESYSTEM = 1
CIRCUITPY_ANALOGIO = 1
CIRCUITPY_AUDIOCORE = 1
CIRCUITPY_AUDIOPWMIO = 1
CIRCUITPY_DIGITALIO = 1
CIRCUITPY_NEOPIXEL_WRITE = 1
CIRCUITPY_TIME = 1
