USB_VID = 0x239A
USB_PID = 0x8069
USB_PRODUCT = "Thunderpack STM32F411"
USB_MANUFACTURER = "Jeremy Gillick"

INTERNAL_FLASH_FILESYSTEM = 1
LONGINT_IMPL = NONE

CIRCUITPY_NVM = 1
CIRCUITPY_BLEIO_HCI = 0

MCU_SERIES = F4
MCU_VARIANT = STM32F411xE
MCU_PACKAGE = UFQFPN48

LD_COMMON = boards/common_nvm.ld
LD_FILE = boards/STM32F411_nvm.ld

CIRCUITPY_ULAB = 0
