USB_VID = 0x1209
USB_PID = 0xF500
USB_PRODUCT = "M4-Shim"
USB_MANUFACTURER = "Silicognition LLC"

CHIP_VARIANT = SAMD51J19A
CHIP_FAMILY = samd51

QSPI_FLASH_FILESYSTEM = 1
EXTERNAL_FLASH_DEVICES = GD25Q16C
LONGINT_IMPL = MPZ
