USB_VID = 0x303A
USB_PID = 0x7001
USB_PRODUCT = "ESP32-S2-HMI-DevKit-1"
USB_MANUFACTURER = "Espressif"

IDF_TARGET = esp32s2

CIRCUITPY_ESP_FLASH_MODE = dio
CIRCUITPY_ESP_FLASH_FREQ = 80m
CIRCUITPY_ESP_FLASH_SIZE = 4MB
