// Board and hardware specific configuration
#define MICROPY_HW_BOARD_NAME "Waveshare RP2350-PiZero"

#define MICROPY_HW_PSRAM_CS_PIN (47)
#define MICROPY_HW_ENABLE_PSRAM (1)

#define PICO_FLASH_SIZE_BYTES (16 * 1024 * 1024)

#define MICROPY_HW_FLASH_STORAGE_BYTES (14 * 1024 * 1024)
#define MICROPY_HW_FLASH_FS_LABEL "RPIFLASH"

#define MICROPY_HW_UART0_TX (0)
#define MICROPY_HW_UART0_RX (1)
#define MICROPY_HW_UART0_CTS (-1)
#define MICROPY_HW_UART0_RTS (-1)

#define MICROPY_HW_USB_MSC (1)
#define MICROPY_HW_USB_PRODUCT_FS_STRING MICROPY_HW_BOARD_NAME
#define MICROPY_HW_USB_PRODUCT_HS_STRING MICROPY_HW_BOARD_NAME
