# Location of top-level MicroPython directory
MPY_DIR = ../../..

# Name of module
MOD = audio

# Source files (.c or .py)
SRC = pwm_audio.c

# Architecture to build for (x86, x64, armv7m, xtensa, xtensawin)
ARCH = xtensawin

# Include to get the rules for compiling and linking the module
include $(MPY_DIR)/py/dynruntime.mk
