USB_VID = 0x303A
USB_PID = 0x80B2
USB_PRODUCT = "nanoESP32-S2  w/Wrover"
USB_MANUFACTURER = "Muselab"

IDF_TARGET = esp32s2

CIRCUITPY_ESP_FLASH_MODE = dio
CIRCUITPY_ESP_FLASH_FREQ = 40m
CIRCUITPY_ESP_FLASH_SIZE = 4MB
