USB_VID = 0x239A
USB_PID = 0x807E
USB_PRODUCT = "The Open Book Feather"
USB_MANUFACTURER = "Oddly Specific Objects"

CHIP_VARIANT = SAMD51J19A
CHIP_FAMILY = samd51

QSPI_FLASH_FILESYSTEM = 1
EXTERNAL_FLASH_DEVICES = GD25Q16C
LONGINT_IMPL = MPZ

CIRCUITPY_GAMEPADSHIFT = 1
