MCU_SERIES = E7
MCU_VARIANT = AE722F80F55D5XX
JLINK_DEV = AE722F80F55D5_HP
LD_FILE = boards/ALIF_ENSEMBLE/board.ld.S

MICROPY_FLOAT_IMPL = float
MICROPY_PY_OPENAMP = 1
MICROPY_PY_OPENAMP_REMOTEPROC = 1
