MCU_SERIES = E7
MCU_VARIANT = AE722F80F55D5XX
JLINK_DEV = AE722F80F55D5_HP
LD_FILE = boards/ALIF_ENSEMBLE/board.ld.S

ALIF_TOOLKIT_CFG_PART = AE722F80F55D5LS
ALIF_TOOLKIT_CFG_FILE = \"app-device-config-ae7.json\"

MICROPY_FLOAT_IMPL = float
MICROPY_PY_OPENAMP = 1
MICROPY_PY_OPENAMP_REMOTEPROC = 1
