USB_VID = 0x2886
USB_PID = 0x802d
USB_PRODUCT = "Seeeduino Wio Terminal"
USB_MANUFACTURER = "Seeed"

CHIP_VARIANT = SAMD51P19A
CHIP_FAMILY = samd51

QSPI_FLASH_FILESYSTEM = 1
EXTERNAL_FLASH_DEVICES = "W25Q32JV_IQ"
LONGINT_IMPL = MPZ

CIRCUITPY_VECTORIO = 1
