USB_VID = 0x1209
USB_PID = 0x7150
USB_PRODUCT = "Hunter Cat NFC"
USB_MANUFACTURER = "Electronic Cats"

CHIP_VARIANT = SAMD21E18A
CHIP_FAMILY = samd21

SPI_FLASH_FILESYSTEM = 1
EXTERNAL_FLASH_DEVICES = "W25Q16JVxQ"
LONGINT_IMPL = MPZ
