/*
 * This file is part of the MicroPython project, http://micropython.org/
 *
 * The MIT License (MIT)
 *
 * Copyright (c) 2024 Angus Gratton
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
#ifndef MICROPY_INCLUDED_RP2_CLOCKS_EXTRA_H
#define MICROPY_INCLUDED_RP2_CLOCKS_EXTRA_H

#include "hardware/clocks.h"

void runtime_init_clocks_optional_usb(bool init_usb, uint32_t sleep_en0, uint32_t sleep_en1);

// Clocks which are dependant on CLK_SYS
#define CLOCKS_SLEEP_EN0_CLK_SYS_DEPENDANTS_BITS   ( \
		CLOCKS_SLEEP_EN0_CLK_SYS_SRAM3_BITS | \
		CLOCKS_SLEEP_EN0_CLK_SYS_SRAM2_BITS | \
		CLOCKS_SLEEP_EN0_CLK_SYS_SRAM1_BITS | \
		CLOCKS_SLEEP_EN0_CLK_SYS_SRAM0_BITS | \
		CLOCKS_SLEEP_EN0_CLK_SYS_SPI1_BITS | \
		CLOCKS_SLEEP_EN0_CLK_SYS_SPI0_BITS | \
		CLOCKS_SLEEP_EN0_CLK_SYS_SIO_BITS | \
		CLOCKS_SLEEP_EN0_CLK_SYS_RTC_BITS | \
		CLOCKS_SLEEP_EN0_CLK_SYS_ROSC_BITS | \
		CLOCKS_SLEEP_EN0_CLK_SYS_ROM_BITS | \
		CLOCKS_SLEEP_EN0_CLK_SYS_RESETS_BITS | \
		CLOCKS_SLEEP_EN0_CLK_SYS_PWM_BITS | \
		CLOCKS_SLEEP_EN0_CLK_SYS_PSM_BITS | \
		CLOCKS_SLEEP_EN0_CLK_SYS_PLL_USB_BITS | \
		CLOCKS_SLEEP_EN0_CLK_SYS_PLL_SYS_BITS | \
		CLOCKS_SLEEP_EN0_CLK_SYS_PIO1_BITS | \
		CLOCKS_SLEEP_EN0_CLK_SYS_PIO0_BITS | \
		CLOCKS_SLEEP_EN0_CLK_SYS_PADS_BITS | \
		CLOCKS_SLEEP_EN0_CLK_SYS_VREG_AND_CHIP_RESET_BITS | \
		CLOCKS_SLEEP_EN0_CLK_SYS_JTAG_BITS | \
		CLOCKS_SLEEP_EN0_CLK_SYS_IO_BITS | \
		CLOCKS_SLEEP_EN0_CLK_SYS_I2C1_BITS | \
		CLOCKS_SLEEP_EN0_CLK_SYS_I2C0_BITS | \
		CLOCKS_SLEEP_EN0_CLK_SYS_DMA_BITS | \
		CLOCKS_SLEEP_EN0_CLK_SYS_BUSFABRIC_BITS | \
		CLOCKS_SLEEP_EN0_CLK_SYS_BUSCTRL_BITS | \
		CLOCKS_SLEEP_EN0_CLK_SYS_ADC_BITS | \
		CLOCKS_SLEEP_EN0_CLK_SYS_CLOCKS_BITS )

#define CLOCKS_SLEEP_EN1_CLK_SYS_DEPENDANTS_BITS   ( \
		CLOCKS_SLEEP_EN1_CLK_SYS_XOSC_BITS | \
		CLOCKS_SLEEP_EN1_CLK_SYS_XIP_BITS | \
		CLOCKS_SLEEP_EN1_CLK_SYS_WATCHDOG_BITS | \
		CLOCKS_SLEEP_EN1_CLK_SYS_USBCTRL_BITS | \
		CLOCKS_SLEEP_EN1_CLK_SYS_UART1_BITS | \
		CLOCKS_SLEEP_EN1_CLK_SYS_UART0_BITS | \
		CLOCKS_SLEEP_EN1_CLK_SYS_TIMER_BITS | \
		CLOCKS_SLEEP_EN1_CLK_SYS_TBMAN_BITS | \
		CLOCKS_SLEEP_EN1_CLK_SYS_SYSINFO_BITS | \
		CLOCKS_SLEEP_EN1_CLK_SYS_SYSCFG_BITS | \
		CLOCKS_SLEEP_EN1_CLK_SYS_SRAM5_BITS | \
		CLOCKS_SLEEP_EN1_CLK_SYS_SRAM4_BITS )

#endif // MICROPY_INCLUDED_RP2_CLOCKS_EXTRA_H
