USB_VID = 0x2341
USB_PID = 0x0070

USB_PRODUCT = "Arduino Nano ESP32"
USB_MANUFACTURER = "Arduino"

IDF_TARGET = esp32s3

CIRCUITPY_ESP_FLASH_MODE = dio
CIRCUITPY_ESP_FLASH_FREQ = 80m
CIRCUITPY_ESP_FLASH_SIZE = 8MB

INTERNAL_FLASH_FILESYSTEM = 0
QSPI_FLASH_FILESYSTEM = 1
EXTERNAL_FLASH_DEVICES = GD25WQ128E

CIRCUITPY_ESPCAMERA = 0
