# Location of top-level MicroPython directory
MPY_DIR = ../../..

# Name of module (different to built-in uzlib so it can coexist)
MOD = deflate_$(ARCH)

# Source files (.c or .py)
SRC = deflate.c

# Architecture to build for (x86, x64, armv7m, xtensa, xtensawin, rv32imc)
ARCH = x64

include $(MPY_DIR)/py/dynruntime.mk
