LD_FILE = boards/samd51x20-bootloader.ld
USB_VID = 0x239A
USB_PID = 0x8021
USB_PRODUCT = "SAM32"
USB_MANUFACTURER = "maholli"

QSPI_FLASH_FILESYSTEM = 0
INTERNAL_FLASH_FILESYSTEM = 1
LONGINT_IMPL = MPZ

CHIP_VARIANT = SAMD51J20A
CHIP_FAMILY = samd51