LD_FILE = boards/samd51x20-bootloader.ld
USB_VID = 0x04D8
USB_PID = 0xEDBE
USB_PRODUCT = "SAM32"
USB_MANUFACTURER = "maholli"

INTERNAL_FLASH_FILESYSTEM = 1
LONGINT_IMPL = MPZ

# No touch on SAMD51 yet
CIRCUITPY_TOUCHIO = 0

CHIP_VARIANT = SAMD51J20A
CHIP_FAMILY = samd51
