USB_VID = 0x04D8
USB_PID = 0xEDBE
USB_PRODUCT = "SAM32"
USB_MANUFACTURER = "maholli"

CHIP_VARIANT = SAMD51J20A
CHIP_FAMILY = samd51

INTERNAL_FLASH_FILESYSTEM = 1
LONGINT_IMPL = MPZ

FROZEN_MPY_DIRS += $(TOP)/frozen/Adafruit_CircuitPython_NeoPixel
