USB_VID = 0x239A
USB_PID = 0x8088
USB_PRODUCT = "Feather Bluefruit Sense"
USB_MANUFACTURER = "Adafruit Industries LLC"

MCU_CHIP = nrf52840

QSPI_FLASH_FILESYSTEM = 1
EXTERNAL_FLASH_DEVICES = "GD25Q16C"
