USB_VID = 0x303A
USB_PID = 0x800D
USB_PRODUCT = "Cucumber RS"
USB_MANUFACTURER = "Gravitech"

IDF_TARGET = esp32s2

CIRCUITPY_ESP_FLASH_MODE = dio
CIRCUITPY_ESP_FLASH_FREQ = 40m
CIRCUITPY_ESP_FLASH_SIZE = 4MB
