#define MICROPY_HW_BOARD_NAME "FRDM_MCXN947"
#define MICROPY_HW_MCU_NAME   "MCXN947VDF"

#define MICROPY_HW_ENABLE_UART_REPL (1)
#define MICROPY_HW_UART_REPL        (4)

#define MICROPY_HW_ENABLE_USBDEV    (1)
#define MICROPY_HW_USBDEV           (1)

#define MICROPY_HW_ENABLE_IFS       (1)
#define MICROPY_HW_IFS_START        (0x100000U)
#define MICROPY_HW_IFS_LENGTH       (0x100000U)
