TARGET_MCU_SERIES       = MCXN947
TARGET_MCU_PART         = MCXN947VDF
TARGET_MCU_CORE         = cm33_core0
TARGET_MCU_CORE_HAS_DSP = 1
TARGET_MCU_CORE_HAS_FPU = 1
TARGET_MCU_AF_FILE      = boards/mcxn947_af.csv

TARGET_HEAP_SIZE        = 0x20000
TARGET_STACK_SIZE       = 0x8000

# Extmod settings
MICROPY_VFS_LFS2 = 1