name: Check examples

on:
  push:
    paths: &paths
      - ".github/workflows/*.yml"
      - "examples/**"
      - "ports/unix/**"
      - "py/**"
      - "shared/**"
  pull_request:
    paths: *paths

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  embedding:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Build
        run: tools/ci.sh embedding_build
