name: Python package for MicroPython

on:
  push:
  release:
    types: [published]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_wheels:
    name: Build wheels for ${{ matrix.cibw_platform }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            cibw_platform: linux
          - os: macos-latest
            cibw_platform: macos
          - os: ubuntu-latest
            cibw_platform: pyodide
          - os: windows-latest
            cibw_platform: windows
    steps:
      - uses: actions/checkout@v6

      - name: Setup MSBuild
        if: matrix.os == 'windows-latest'
        uses: microsoft/setup-msbuild@v2

      - name: Build wheels
        uses: pypa/cibuildwheel@v4.0.0
        env:
          CIBW_BEFORE_ALL: "make -C ports/unix submodules && make -C mpy-cross"
          CIBW_PLATFORM: ${{ matrix.cibw_platform }}
          CIBW_SKIP: "cp38-* cp39-* *_i686"
          CIBW_ENABLE: pyodide-prerelease
          CIBW_TEST_COMMAND: "python {package}/test_micropython_module.py"
        with:
          package-dir: ports/python

      - uses: actions/upload-artifact@v7
        with:
          name: wheels-${{ matrix.cibw_platform }}
          path: wheelhouse/*.whl

  make_sdist:
    name: Make SDist
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        persist-credentials: false # good security practice

    - name: Build SDist
      run: pipx run build --sdist

    - uses: actions/upload-artifact@v4
      with:
        name: sdist
        path: dist/*.tar.gz

  publish:
    needs: [build_wheels, make_sdist]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v8
        with:
          path: dist
          merge-multiple: true

      # avoid trying to upload old pyodide tagged wheels - not supported by PyPi
      - run: rm -f dist/*pyodide*.whl

      - uses: pypa/gh-action-pypi-publish@release/v1
