name: baochip port

on:
  push:
    paths:
      - '.github/workflows/*.yml'
      - 'tools/**'
      - 'py/**'
      - 'extmod/**'
      - 'shared/**'
      - 'lib/**'
      - 'drivers/**'
      - 'ports/baochip/**'
  pull_request:
    paths:
      - '.github/workflows/*.yml'
      - 'tools/**'
      - 'py/**'
      - 'extmod/**'
      - 'shared/**'
      - 'lib/**'
      - 'drivers/**'
      - 'ports/baochip/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_baochip:
    strategy:
      fail-fast: false
      matrix:
        ci_func:  # names are functions in ci.sh
          - baochip_build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Install packages
      run: tools/ci.sh baochip_setup
    - name: Build ci_${{ matrix.ci_func }}
      run: tools/ci.sh ${{ matrix.ci_func }}
