name: esp32 port

on:
  push:
  pull_request:
    paths:
      - '.github/workflows/*.yml'
      - 'tools/**'
      - 'py/**'
      - 'extmod/**'
      - 'shared/**'
      - 'lib/**'
      - 'drivers/**'
      - 'ports/esp32/**'
  schedule:
     # Scheduled run exists to keep master branch ESP-IDF cache entry hot
     # and prevent creating many redundant per-branch cache entries instead.
     - cron: "20 0 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_idf:
    strategy:
      fail-fast: false
      matrix:
        # Build for both oldest and newest supported ESP-IDF versions, as per ports/esp32/README.md
        # (if updating here, also update "IDF_LATEST_VER" below)
        idf_ver:
          - "v5.3"
          - "v5.5.1"
        ci_func:  # names are functions in ci.sh
          - esp32_build_cmod_spiram_s2
          - esp32_build_s3_c3
          - esp32_build_c2_c5_c6
          - esp32_build_p4
    env:
        IDF_LATEST_VER: "v5.5.1"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    # Only the latest IDF version will build the ESP-IDF lockfiles correctly,
    # so we need to disable MICROPY_MAINTAINER_BUILD on older versions.
    - name: Disable extra checks for older ESP-IDF
      id: check_latest_ver
      if: ${{ matrix.idf_ver != env.IDF_LATEST_VER }}
      run: echo "MICROPY_MAINTAINER_BUILD=0" >> ${GITHUB_ENV}

    - name: Setup ESP-IDF
      uses: ./.github/actions/setup_esp32
      with:
        idf_ver: ${{ matrix.idf_ver }}
        ccache_key: ${{ matrix.ci_func }}


    - name: Build ci_${{matrix.ci_func }} on ESP-IDF ${{ matrix.idf_ver }}
      run: tools/ci.sh ${{ matrix.ci_func }}
