name: quectel port

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install tools
        run: tools/ci.sh quectel_setup

      - name: Build Firmware
        run: tools/ci.sh quectel_build
