// This file is part of the CircuitPython project: https://circuitpython.org
//
// SPDX-FileCopyrightText: Copyright (c) 2019 Lucian Copeland for Adafruit Industries
// SPDX-FileCopyrightText: Copyright (c) 2019 Artur Pacholec
// SPDX-FileCopyrightText: Copyright (c) 2023 Scott Shawcroft for Adafruit Industries
//
// SPDX-License-Identifier: MIT

#pragma once


// define FORMAT_PIN(pin_name) and then include this file.

FORMAT_PIN(GPIO_AD_14)
FORMAT_PIN(GPIO_AD_13)
FORMAT_PIN(GPIO_AD_12)
FORMAT_PIN(GPIO_AD_11)
FORMAT_PIN(GPIO_AD_10)
FORMAT_PIN(GPIO_AD_09)
FORMAT_PIN(GPIO_AD_08)
FORMAT_PIN(GPIO_AD_07)
FORMAT_PIN(GPIO_AD_06)
FORMAT_PIN(GPIO_AD_05)
FORMAT_PIN(GPIO_AD_04)
FORMAT_PIN(GPIO_AD_03)
FORMAT_PIN(GPIO_AD_02)
FORMAT_PIN(GPIO_AD_01)
FORMAT_PIN(GPIO_AD_00)

FORMAT_PIN(GPIO_SD_13)
FORMAT_PIN(GPIO_SD_12)
FORMAT_PIN(GPIO_SD_11)
FORMAT_PIN(GPIO_SD_10)
FORMAT_PIN(GPIO_SD_09)
FORMAT_PIN(GPIO_SD_08)
FORMAT_PIN(GPIO_SD_07)
FORMAT_PIN(GPIO_SD_06)
FORMAT_PIN(GPIO_SD_05)
FORMAT_PIN(GPIO_SD_04)
FORMAT_PIN(GPIO_SD_03)
FORMAT_PIN(GPIO_SD_02)
FORMAT_PIN(GPIO_SD_01)
FORMAT_PIN(GPIO_SD_00)

FORMAT_PIN(GPIO_13)
FORMAT_PIN(GPIO_12)
FORMAT_PIN(GPIO_11)
FORMAT_PIN(GPIO_10)
FORMAT_PIN(GPIO_09)
FORMAT_PIN(GPIO_08)
FORMAT_PIN(GPIO_07)
FORMAT_PIN(GPIO_06)
FORMAT_PIN(GPIO_05)
FORMAT_PIN(GPIO_04)
FORMAT_PIN(GPIO_03)
FORMAT_PIN(GPIO_02)
FORMAT_PIN(GPIO_01)
FORMAT_PIN(GPIO_00)
FORMAT_PIN(USB_OTG1_DN)
FORMAT_PIN(USB_OTG1_DP)
