USB_VID = 0x239A
USB_PID = 0x80BE
USB_PRODUCT = "TinkeringTech ScoutMakes Azul"
USB_MANUFACTURER = "TinkeringTech LLC"

MCU_CHIP = nrf52840

QSPI_FLASH_FILESYSTEM = 1
EXTERNAL_FLASH_DEVICES = "GD25Q16C"
